import type { Destination } from "./destinations";

export const DESTINATIONS: Destination[] = [
  {
    slug: "marrakech",
    name: "Marrakech",
    subtitle: "La Città Rossa",
    region: "Marrakech-Safi",
    lat: 31.6295,
    lng: -7.9811,
    heroImage: "https://images.unsplash.com/photo-1708823081494-3e5bbd2ce931?w=1400&q=85",
    about:
      "Marrakech è la città più vibrante del Marocco, un labenirinto millenario di souk, palazzi e teatro di strada costruito in pietra color rosa. La medina di Marrakech è Patrimonio dell'Umanità UNESCO e una delle aree urbane più densamente popolate al mondo, con oltre 90.000 abitanti in uno spazio inferiore a due chilometri quadrati. Nel suo cuore si trova Jemaa el-Fna, la piazza pubblica più straordinaria del pianeta: di giorno mercato di spezie e chioschi di succhi di frutta, di notte un carnevale di cantastorie, acrobati e musicisti gnawa che va in scena ogni singola sera da 900 anni.",
    knownFor: [
      "Jemaa el-Fna, il più grande teatro a cielo aperto del mondo",
      "14 souk delle corporazioni artigiane nel cuore della medina antica",
      "La moschea Koutoubia e le Tombe Saadiane",
      "Il Giardino Majorelle e il Museo delle Arti Berbere",
      "Riad nascosti e cultura tradizionale dell'hammam",
      "Porta d'accesso all'Alto Atlante (a un'ora di distanza)",
    ],
    highlights: [
      { title: "La Medina", desc: "Una città fortificata patrimonio UNESCO con oltre 9.000 vicoli, ognuno dei quali conduce a qualcosa di inaspettato. Ospita i souk, le concerie e i mercati di spezie più famosi del Marocco." },
      { title: "Jemaa el-Fna", desc: "La grande piazza si trasforma completamente due volte al giorno. Le stesse famiglie gestiscono gli stessi banchi di cibo da generazioni: merguez alla griglia, zuppa harira e succo d'arancia appena spremuto." },
      { title: "Il Giardino Majorelle", desc: "Progettato dal pittore francese Jacques Majorelle negli anni '20 e successivamente restaurato da Yves Saint Laurent, il giardino è un'oasi di blu cobalto, boschetti di bambù e cactus rari." },
      { title: "Base per le escursioni", desc: "Marrakech è la base ideale per esplorare l'intera regione: l'Alto Atlante e la vetta del Toubkal (1 ora), le cascate di Ouzoud (3 ore), il Sahara (10 ore in auto o in escursione notturna) ed Essaouira sulla costa atlantica (3 ore)." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da marzo a maggio è alta stagione: caldo, verde, fiori selvatici sull'Atlante. Prenotate con anticipo." },
      { name: "Estate", emoji: "☀️", rating: 2, note: "Da giugno ad agosto le temperature in città superano i 40°C. Non ideale per i tour a piedi." },
      { name: "Autunno", emoji: "🍂", rating: 5, note: "Da settembre a novembre è eccellente: caldo piacevole, stagione del raccolto, meno affollamento." },
      { name: "Inverno", emoji: "❄️", rating: 3, note: "Da dicembre a febbraio è mite e soleggiato in città. I sentieri dell'Atlante possono avere neve oltre i 2.000 m." },
    ],
    travelTips: [
      "La medina si scopre meglio a piedi: assumete una guida locale per accedere ai quartieri oltre le vie turistiche principali.",
      "Negoziate i prezzi nei souk: la prima offerta è raramente il prezzo reale.",
      "Indossate abiti leggeri e traspiranti. Un abbigliamento sobrio (spalle e ginocchia coperte) è apprezzato nella medina e nelle moschee.",
      "Portate con voi monete da dirham di piccolo taglio per i banchi di cibo e le mance.",
      "Molti dei riad più belli sono invisibili dall'esterno: una porta semplice in un muro anonimo.",
    ],
    faqs: [
      { q: "Come si arriva dall'aeroporto di Marrakech alla medina?", a: "Un taxi dall'aeroporto della Menara alla medina costa circa 100-150 MAD (9-13 €) e impiega 15-20 minuti. Concordate il prezzo prima di salire. Alcuni riad offrono il transfer dall'aeroporto." },
      { q: "Marrakech è sicura per chi viaggia da solo?", a: "Sì, Marrakech è generalmente sicura e dispone di una solida infrastruttura turistica. I problemi più comuni sono i procacciatori insistenti nella medina e gli scooter nelle strade strette. Restate vigili nella folla e custodite bene gli oggetti di valore." },
      { q: "Qual è la zona migliore dove alloggiare a Marrakech?", a: "La medina (città vecchia) è la più suggestiva. I quartieri della Kasbah e di Mouassine offrono i riad più tranquilli, con distanze brevi dai principali siti. Gueliz (la città nuova) è più occidentalizzata e offre parcheggi più comodi." },
      { q: "Serve il visto per il Marocco?", a: "I cittadini dell'UE, del Regno Unito, degli Stati Uniti, del Canada, dell'Australia e della maggior parte dei paesi occidentali non necessitano di visto per soggiorni inferiori a 90 giorni. Il passaporto deve avere una validità residua di almeno 6 mesi dalla data di ingresso." },
      { q: "Quale valuta si usa e posso pagare con la carta?", a: "Il Marocco utilizza il dirham (MAD). Le carte sono accettate nella maggior parte degli hotel e dei ristoranti più grandi, ma i souk e i piccoli commercianti accettano solo contanti. Gli sportelli bancomat sono ampiamente disponibili nella medina e a Gueliz." },
    ],
    relatedCategories: ["cultural", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guida di viaggio a Marrakech — Migliori tour, consigli e avventure | Marrakech Eco Tours",
    seoDescription: "Guida completa a Marrakech: passeggiate nella medina, souk, Jemaa el-Fna ed escursioni di un giorno verso l'Atlante e il Sahara. Prenota tour in piccoli gruppi con guide berbere locali.",
  },
  {
    slug: "high-atlas",
    name: "Alto Atlante",
    subtitle: "Il tetto del Nord Africa",
    region: "Marrakech-Safi",
    lat: 31.0573,
    lng: -7.9149,
    heroImage: "https://images.unsplash.com/photo-1611859836043-a9177f500a27?w=1400&q=85",
    about:
      "L'Alto Atlante è una delle grandi catene montuose dell'Africa: una spina dorsale di 2.400 km di vette glaciali, villaggi berberi e antichi sentieri per muli che si estende dall'Atlantico al confine algerino. Al suo punto più alto si erge il Jbel Toubkal (4.167 m), il tetto del Nord Africa e la vetta di 4.000 metri più accessibile del continente. Da millenni, le comunità berbere coltivano le valli terrazzate e attraversano gli alti valichi lungo percorsi rimasti invariati fin dai tempi delle carovane medievali.",
    knownFor: [
      "Jbel Toubkal, la vetta più alta del Nord Africa a 4.167 m",
      "Il villaggio di Imlil, punto di partenza tradizionale per la scalata al Toubkal",
      "Comunità berbere di montagna con secoli di tradizione",
      "Laghi alpini, gole e valli glaciali",
      "La traversata del massiccio del M'Goun, il trekking più remoto del Marocco",
      "Viste spettacolari dalle creste, dal Marocco fino alla Spagna",
    ],
    highlights: [
      { title: "Vetta del Toubkal", desc: "Il trekking di 4 giorni verso il Toubkal è la sfida montana più iconica del Marocco. Partendo da Imlil a 1.740 m, la salita attraversa villaggi berberi, rifugi di montagna e il passo di Tizi n'Ouanoums prima dell'ultimo sforzo verso la vetta a 4.167 m." },
      { title: "La valle di Imlil", desc: "Il villaggio porta d'accesso per tutto il trekking dell'Alto Atlante. Circondata da noceti e campi di grano terrazzati, Imlil ospita una comunità di guide di montagna le cui famiglie lavorano su questi sentieri da generazioni." },
      { title: "Villaggi berberi", desc: "L'Atlante è la casa delle comunità indigene amazigh (berbere) che hanno conservato lingua, cultura e architettura nel corso di secoli di storia. Molti villaggi non hanno accesso stradale, solo sentieri per muli." },
      { title: "Massiccio del M'Goun", desc: "Per trekker esperti in cerca di solitudine, la traversata del M'Goun (7-10 giorni) attraversa alcuni dei paesaggi di gole e creste più spettacolari del Nord Africa, con infrastrutture turistiche quasi inesistenti." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da aprile a giugno: fiori selvatici, neve in ritiro sui passi alti, condizioni di trekking ideali." },
      { name: "Estate", emoji: "☀️", rating: 4, note: "Da luglio ad agosto: sentieri di vetta liberi, caldo nelle valli ma fresco in quota. Alta stagione." },
      { name: "Autunno", emoji: "🍂", rating: 5, note: "Da settembre a ottobre: probabilmente le condizioni migliori, cieli stabili, colori vivaci, meno trekker." },
      { name: "Inverno", emoji: "❄️", rating: 3, note: "Da novembre a marzo: la vetta del Toubkal richiede ramponi e piccozza. Bellissima ma impegnativa." },
    ],
    travelTips: [
      "Acclimatatevi a Marrakech (a 460 m) per almeno un giorno prima di salire a Imlil (1.740 m).",
      "Il Toubkal richiede buona forma fisica ma nessuna tecnica di arrampicata in estate. In inverno è un vero e proprio obiettivo alpinistico.",
      "Assumete una guida berbera locale autorizzata: conosce ogni pietra della montagna ed è obbligatoria nel Parco Nazionale del Toubkal.",
      "I muli possono trasportare l'equipaggiamento sulla maggior parte dei percorsi dell'Atlante: approfittatene per viaggiare più leggeri.",
      "Portate strati caldi anche in estate: le temperature al rifugio del Toubkal possono scendere sotto lo zero di notte.",
    ],
    faqs: [
      { q: "Quanto è difficile il trekking al Toubkal?", a: "Il Toubkal è un obiettivo di trekking impegnativo (non un'arrampicata tecnica) che richiede una buona forma cardiovascolare. Dovreste essere a vostro agio a camminare 6-8 ore al giorno con uno zaino da trekking. In estate non serve equipaggiamento speciale. In inverno ramponi e piccozza sono essenziali." },
      { q: "Quanto tempo serve per raggiungere la vetta del Toubkal?", a: "Il percorso standard da Imlil alla vetta e ritorno richiede 3-4 giorni. Giorno 1: Imlil al rifugio (4-5 ore). Giorno 2: tentativo di vetta dal rifugio (3-4 ore di salita, 2,5 ore di discesa). Giorni 3-4: discesa e visite opzionali ai villaggi berberi." },
      { q: "È obbligatoria una guida per il trekking al Toubkal?", a: "Una guida autorizzata non è legalmente obbligatoria ma è fortemente consigliata e richiesta dalla maggior parte degli operatori responsabili. Il terreno è impegnativo, il meteo cambia rapidamente e le guide locali offrono sicurezza, conoscenza del percorso e un prezioso contesto culturale." },
      { q: "Qual è la base migliore per il trekking nell'Alto Atlante?", a: "Il villaggio di Imlil (1.740 m), a 62 km da Marrakech, è il punto di partenza classico per il Toubkal. Azilal è la base per i trekking del massiccio del M'Goun. Entrambi richiedono una guida e una preparazione adeguata." },
    ],
    relatedCategories: ["trekking", "hiking"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guida di viaggio all'Alto Atlante — Trekking al Toubkal e villaggi berberi | Marrakech Eco Tours",
    seoDescription: "Esplora l'Alto Atlante con guide locali certificate: trekking alla vetta del Toubkal (4.167 m), passeggiate nei villaggi berberi e traversate di più giorni sull'Atlante. Piccoli gruppi da Marrakech.",
  },
  {
    slug: "sahara",
    name: "Deserto del Sahara",
    subtitle: "Le dune dorate dell'Erg Chebbi",
    region: "Drâa-Tafilalet",
    lat: 31.1513,
    lng: -3.9785,
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1400&q=85",
    about:
      "L'Erg Chebbi, vicino al villaggio di Merzouga, è la sezione più spettacolare del mare di sabbia sahariano in Marocco: un campo di dune stellate di 50 km² che si innalza fino a 150 metri sopra la hamada piatta (pianura di ghiaia). Le dune sono composte interamente da sabbia fine color rosso-arancio, scolpita dai venti dominanti di nord-ovest in classiche forme di barcane a mezzaluna. Al tramonto e all'alba, la luce trasforma l'Erg in un paesaggio di oro e rame fuso che non esiste in nessun altro luogo al mondo.",
    knownFor: [
      "Dune che raggiungono i 150 m, tra le più alte del Marocco",
      "Trekking in cammello al tramonto verso il cuore dell'Erg",
      "Autentiche notti in campo nomade berbero sotto le stelle",
      "Osservazione della Via Lattea, lontano da ogni inquinamento luminoso",
      "Il villaggio di Merzouga, porta d'accesso al deserto",
      "Escursioni in quad e in 4×4 nel deserto",
    ],
    highlights: [
      { title: "Le dune dell'Erg Chebbi", desc: "Il campo di dune è più spettacolare all'ora dorata: arrivate al tramonto per lo spettacolo di luce che colora la sabbia in ogni sfumatura di rame, ambra e rosa. All'alba i colori si invertono, con i blu freddi che lasciano spazio all'oro caldo mentre il sole sale sulla cresta delle dune." },
      { title: "Trekking in cammello", desc: "La tradizionale traversata dell'Erg si compie in groppa a un cammello: un viaggio lento e meditativo nel cuore del deserto che vi connette a millenni di rotte carovaniere. Le nostre guide berbere seguono gli stessi sentieri percorsi dai loro antenati." },
      { title: "Notti nel campo del deserto", desc: "Dormire in una tenda berbera nel cuore dell'Erg, lontano da qualsiasi strada o insediamento, è una delle esperienze più profonde che si possano vivere viaggiando. Il silenzio è assoluto. La Via Lattea, in un cielo non toccato da alcun inquinamento luminoso, è straordinaria." },
      { title: "Attività nel deserto", desc: "Oltre al classico trekking in cammello, l'Erg e la hamada circostante offrono sandboard sui versanti delle dune, escursioni in quad sulle pianure ghiaiose ed escursioni in 4×4 verso oasi desertiche e siti fossiliferi." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da marzo a maggio: temperature ideali (20-28°C), occasionali fiori selvatici nella hamada dopo le piogge invernali." },
      { name: "Estate", emoji: "☀️", rating: 1, note: "Da giugno ad agosto: caldo estremo (40-48°C). I viaggi nel deserto non sono consigliati in piena estate." },
      { name: "Autunno", emoji: "🍂", rating: 5, note: "Da settembre a novembre: giornate calde, notti fresche, condizioni perfette per il campeggio nel deserto." },
      { name: "Inverno", emoji: "❄️", rating: 4, note: "Da dicembre a febbraio: notti fredde (vicine allo zero a gennaio) ma cieli tersi e mozzafiato. Portate abiti caldi per il campo." },
    ],
    travelTips: [
      "Portate abiti caldi per le notti nel deserto: le temperature scendono drasticamente dopo il tramonto anche in primavera e in autunno.",
      "Portate una torcia e acqua supplementare per il trekking in cammello. Le dune possono disorientare al buio.",
      "La sabbia si infiltra ovunque. Usate una sacca impermeabile per l'attrezzatura fotografica e sigillate bene gli articoli da toeletta.",
      "Il sandboard è divertente ma fisicamente impegnativo: risalire dune di 150 m è estenuante.",
      "L'alba sull'Erg è spettacolare quanto il tramonto: impostate la sveglia e salite sulla cresta di duna più vicina prima che faccia luce.",
    ],
    faqs: [
      { q: "Quanto dista Merzouga da Marrakech?", a: "Merzouga si trova a circa 560 km da Marrakech, circa 9-10 ore in auto. La maggior parte dei tour nel deserto percorre un itinerario all'andata (di solito attraverso le gole del Dades e la Valle delle Mille Kasbah) e ritorna per una diversa rotta meridionale. È possibile anche un andata e ritorno notturno per i tour economici." },
      { q: "Un tour di 3 giorni nel Sahara è sufficiente?", a: "3 giorni offrono l'esperienza essenziale: attraversare l'Atlante e la regione delle kasbah, una notte completa nel campo del deserto e il viaggio di ritorno. Per un'esperienza più completa, 4-5 giorni permettono di esplorare la Valle delle Rose, le gole del Todra e diverse zone di dune." },
      { q: "Cosa è incluso in una notte di campo nel Sahara?", a: "Le notti di campo standard includono una tenda berbera tradizionale, la cena (tajine e couscous), musica dal vivo attorno al fuoco e la colazione prima del giro in cammello all'alba. I campi privati più lussuosi dispongono di veri letti e bagno privato." },
      { q: "Posso visitare il Sahara in modo indipendente?", a: "Sì, ma l'esperienza è notevolmente più ricca con una guida locale esperta. Orientarsi tra le dune non è banale, e le guide locali offrono contesto culturale, accesso linguistico alle famiglie berbere e una logistica che richiederebbe giorni da organizzare autonomamente." },
    ],
    relatedCategories: ["desert"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Tour nel deserto del Sahara da Marrakech — Guida a Erg Chebbi e Merzouga | Marrakech Eco Tours",
    seoDescription: "Scopri il deserto del Sahara con guide certificate: trekking in cammello, notti in campo berbero e alba sulle dune di 150 m dell'Erg Chebbi. Tour nel deserto di 2-4 giorni da Marrakech.",
  },
  {
    slug: "fes",
    name: "Fès el-Bali",
    subtitle: "La città medievale vivente",
    region: "Fès-Meknès",
    lat: 34.0545,
    lng: -4.9815,
    heroImage: "https://images.unsplash.com/photo-1582742850838-24590fb39fdc?w=1400&q=85",
    about:
      "Fès el-Bali è probabilmente la più straordinaria sopravvivenza urbana al mondo: una città medievale pienamente funzionante di 156.000 abitanti, che copre 256 ettari ed è abitata ininterrottamente dal 789 d.C. È la più grande area urbana priva di automobili al mondo. Ogni strada del suo labirinto di 9.400 vicoli vede il trasporto di merci a mano o a dorso di mulo. Gli stessi mestieri vengono praticati negli stessi laboratori da mille anni: concia del cuoio, smaltatura della ceramica, intarsio dell'ottone, zellige. La città fu fondata da Moulay Idriss I ed espansa sotto la dinastia merinide fino a diventare il grande centro del sapere islamico che rimane ancora oggi.",
    knownFor: [
      "La più grande zona urbana priva di automobili al mondo, con 9.400 vicoli",
      "La conceria Chouara, immutata dall'XI secolo",
      "L'Università di al-Qarawiyyin, fondata nell'859, la più antica al mondo",
      "La madrasa Bou Inania e la madrasa Attarine",
      "Il Mellah (quartiere ebraico) e le sue viste dai tetti",
      "Una tradizione artigianale viva: zellige, ricamo, rame, cuoio",
    ],
    highlights: [
      { title: "La conceria Chouara", desc: "Il luogo più fotografato del Marocco dopo il Sahara. Vasche di pietra piene di tinture (zafferano, papavero, henné, indaco) dove i conciatori lavorano immersi fino al ginocchio, trattando le pelli esattamente come 800 anni fa. Si ammira al meglio dalle terrazze dei negozi di pelletteria che si affacciano sulle vasche." },
      { title: "Moschea e Università di al-Qarawiyyin", desc: "Fondata nell'859 da una donna, Fatima al-Fihri, al-Qarawiyyin è riconosciuta dall'UNESCO come la più antica università al mondo in funzionamento ininterrotto. I non musulmani non possono entrare nella moschea, ma il cortile intravisto attraverso i portali scolpiti è uno dei grandi capolavori architettonici del Marocco." },
      { title: "Il labirinto della medina", desc: "A differenza della medina di Marrakech, quella di Fès è genuinamente labirintica: anche le guide esperte usano punti di riferimento anziché una mappa mentale. Perdersi leggermente è il modo migliore per scoprire la vera Fès: piccoli forni, tessitori di tappeti, moschee di quartiere e piccole piazze dove gli anziani giocano a carte." },
      { title: "Il Mellah", desc: "Il quartiere ebraico della vecchia Fès, un tempo casa di una delle comunità ebraiche più importanti del Nord Africa, custodisce una splendida architettura di metà Novecento, una sinagoga restaurata e le migliori viste della città dalle sue terrazze rialzate e dal cimitero." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da marzo a maggio: temperature piacevoli (18-26°C), serate lunghe, dintorni verdi." },
      { name: "Estate", emoji: "☀️", rating: 2, note: "Da giugno ad agosto: molto caldo (35-40°C). La medina diventa opprimente. Si consigliano visite solo al mattino." },
      { name: "Autunno", emoji: "🍂", rating: 5, note: "Da settembre a novembre: clima perfetto, stagione del raccolto, Festival di Fès delle Musiche Sacre del Mondo (novembre)." },
      { name: "Inverno", emoji: "❄️", rating: 3, note: "Da dicembre a febbraio: fresco e occasionalmente piovoso. Le concerie sono meno affollate e più accessibili." },
    ],
    travelTips: [
      "Fès dista 3-4 ore d'auto da Marrakech. La maggior parte dei tour delle città imperiali combina Fès, Meknès e Volubilis in 3 o più giorni.",
      "Una guida locale è preziosa nella medina: orientarsi da soli porta spesso a frustrazione. Anche i locali si perdono.",
      "Le concerie sono più colorate al mattino (la concia pomeridiana avviene più tardi nella giornata).",
      "Acquistate articoli in pelle direttamente nei negozi della conceria: la qualità è autentica e la provenienza tracciabile.",
      "Assaggiate i piatti tipici fassi: la pastilla (torta salata di piccione e mandorle), la zuppa harira e la bastilla au lait (dolce al latte).",
    ],
    faqs: [
      { q: "Quanti giorni servono a Fès?", a: "Due giorni interi sono il minimo per coprire i principali siti della medina, le concerie e la Ville Nouvelle. Tre giorni permettono di esplorare il Mellah, il quartiere andaluso, fare una gita alle rovine romane di Volubilis e visitare la medina con più calma." },
      { q: "Fès è sul percorso stradale da Marrakech a Fès?", a: "Sì: Marrakech-Fès è il classico itinerario terrestre del Marocco, che di solito richiede da 3 a 6 giorni passando per le gole del Dades, le gole del Todra, il Sahara di Merzouga e le foreste di cedri del Medio Atlante. È uno dei grandi road trip del Nord Africa." },
      { q: "Devo alloggiare nella medina o nella Ville Nouvelle?", a: "Alloggiate nella medina. L'esperienza del riad è centrale per comprendere Fès: varcare un muro esterno anonimo per scoprire un cortile interno decorato con fontana è uno dei momenti più suggestivi del Marocco. La Ville Nouvelle non ha carattere storico." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guida di viaggio a Fès el-Bali — Tour della medina, concerie e città imperiale | Marrakech Eco Tours",
    seoDescription: "Esplora Fès el-Bali, la città medievale più intatta al mondo. Tour guidati alla conceria Chouara, all'Università di al-Qarawiyyin e nella medina di 9.400 vicoli. Escursioni di un giorno e tour di più giorni da Marrakech.",
  },
  {
    slug: "chefchaouen",
    name: "Chefchaouen",
    subtitle: "La perla blu del Marocco",
    region: "Tanger-Tétouan-Al Hoceïma",
    lat: 35.1688,
    lng: -5.2689,
    heroImage: "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1400&q=85",
    about:
      "Chefchaouen sorge sui pendii delle montagne del Rif a 600 m sul livello del mare: una medina piccola e notevolmente ben conservata, i cui muri, scalinate e vasi di fiori sono uniformemente dipinti di blu e bianco. La tradizione della tinteggiatura blu, introdotta dai profughi ebrei in fuga dalla Reconquista spagnola negli anni '30, è diventata così centrale nell'identità della cittadina che i residenti ridipingono le proprie case ogni primavera. L'effetto è completamente diverso da qualsiasi altro luogo in Marocco: sereno, fotogenico e genuinamente rilassato.",
    knownFor: [
      "Una medina interamente dipinta di blu e bianco",
      "Un contesto montano nel Rif con viste spettacolari sulle gole",
      "Il fiume Ras el-Ma, la sua cascata e le pietre per il bucato",
      "Plaza Uta el-Hammam, la piazza principale circondata da caffè",
      "Tessitura artigianale della lana e artigianato tradizionale del Rif",
      "Porta d'accesso al Parco Nazionale di Talassemtane",
    ],
    highlights: [
      { title: "La medina blu", desc: "Ogni muro, gradino e stipite è dipinto in tonalità che vanno dall'azzurro pallido all'indaco profondo. La medina è abbastanza piccola da esplorare interamente in un giorno, ma abbastanza gratificante da meritare tre giorni di soggiorno. Ogni angolo è una fotografia." },
      { title: "Ras el-Ma", desc: "A pochi passi dalla medina, la sorgente di Ras el-Ma sgorga dalla montagna in un piccolo fiume dove gli abitanti lavano i panni secondo il metodo tradizionale. Una fuga tranquilla dalla piazza centrale, più affollata di turisti." },
      { title: "Parco Nazionale di Talassemtane", desc: "Il parco inizia ai margini della medina e offre escursioni di mezza giornata attraverso foreste di cedri e querce, passeggiate lungo le gole sopra il fiume Laou e viste sulla città dipinta di blu sottostante." },
      { title: "La Moschea Spagnola", desc: "Una salita di 20 minuti dalla medina (o raggiungibile tramite un sentiero roccioso) conduce a una moschea costruita dagli spagnoli, con vista panoramica sull'intera città blu e sulle valli del Rif circostanti, ideale al tramonto." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da aprile a giugno: temperature miti, colline verdi, fiori selvatici sui pendii del Rif. Alta stagione." },
      { name: "Estate", emoji: "☀️", rating: 4, note: "Da luglio ad agosto: caldo ma gestibile in quota. Le serate sono fresche. Molto affollata: prenotate in anticipo." },
      { name: "Autunno", emoji: "🍂", rating: 4, note: "Da settembre a novembre: temperature piacevoli, più tranquilla dell'estate." },
      { name: "Inverno", emoji: "❄️", rating: 2, note: "Da dicembre a marzo: può essere freddo e piovoso. Neve occasionale sulle creste del Rif. Molto tranquilla." },
    ],
    travelTips: [
      "Chefchaouen si visita al meglio con un pernottamento, non come gita giornaliera: la città è più magica al primo mattino, prima dell'arrivo dei bus turistici.",
      "Le strade blu sono più vivide con la luce del primo mattino (prima delle 9) e con l'oro del tardo pomeriggio.",
      "Ottima base per escursioni nelle montagne del Rif. Chiedete al vostro riad informazioni sulle guide locali per i sentieri.",
      "La medina è piccola: 'perdersi' intenzionalmente porta ai vicoli e alle botteghe artigiane più interessanti.",
      "Acquistate prodotti locali: le coperte di lana, le djellabe e gli articoli in pelle sono di tradizione rifena e di ottima qualità.",
    ],
    faqs: [
      { q: "Come si arriva a Chefchaouen da Marrakech?", a: "Non esiste un percorso diretto: Chefchaouen dista 530 km da Marrakech, circa 6-7 ore in auto o autobus. La maggior parte dei visitatori vi arriva passando per Fès o Tangeri. L'approccio più pratico è un tour di più giorni delle città imperiali che includa Fès, Chefchaouen, Meknès e il ritorno a Marrakech." },
      { q: "Perché Chefchaouen è dipinta di blu?", a: "La tradizione della tinteggiatura blu fu introdotta negli anni '30 dai profughi ebrei in fuga dalla Reconquista spagnola. Nella tradizione ebraica il blu simboleggia il cielo. Nel tempo l'intera medina ha adottato questa pratica come parte della propria identità, e gli abitanti ridipingono le case ogni primavera." },
      { q: "Vale la pena il viaggio a Chefchaouen da Marrakech?", a: "Sì, ma richiede almeno un pernottamento per apprezzarla appieno. Visitarla come gita giornaliera (possibile solo da Fès o Tangeri, a 1,5-2 ore) lascia troppo poco tempo. Un pernottamento permette di vivere la medina nel suo momento più tranquillo e bello." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guida di viaggio a Chefchaouen — La città blu del Marocco | Marrakech Eco Tours",
    seoDescription: "Scopri Chefchaouen, la famosa città blu del Marocco tra le montagne del Rif. Tour guidati, escursioni nel Parco Nazionale di Talassemtane e pernottamenti nella medina dipinta.",
  },
  {
    slug: "agadir",
    name: "Agadir",
    subtitle: "Costa atlantica e capitale del surf",
    region: "Souss-Massa",
    lat: 30.4278,
    lng: -9.5981,
    heroImage: "https://images.unsplash.com/photo-1562874732-260714dfe537?w=1400&q=85",
    about:
      "Agadir è la principale città balneare del Marocco: un moderno porto atlantico ricostruito interamente dopo un catastrofico terremoto nel 1960. Situata ai piedi delle montagne dell'Anti-Atlante, con una mezzaluna di spiaggia di sabbia bianca lunga nove chilometri, Agadir funge da porta d'accesso meridionale al Marocco sia per i turisti in pacchetto che per gli avventurieri. Trenta minuti a nord si trova Taghazout, un villaggio diventato una delle destinazioni surf più famose al mondo. La regione di Souss-Massa che circonda Agadir ospita parchi nazionali, foreste di argan, zone umide popolate da fenicotteri e comunità berbere che mantengono uno stile di vita secolare.",
    knownFor: [
      "9 km di spiaggia atlantica, la più lunga spiaggia urbana del Marocco",
      "Taghazout, surf di livello mondiale (Anchor Point, Hash Point, Killer Point)",
      "Il Parco Nazionale di Souss-Massa (fenicotteri, ibis eremita, gazzelle)",
      "Paradise Valley, oasi di palme, piscine turchesi e bagni naturali",
      "Cooperative di olio di argan: il Souss è l'unica foresta di argan al mondo",
      "Pesce fresco nel porto peschereccio attivo di Agadir",
    ],
    highlights: [
      { title: "Surf a Taghazout", desc: "Il villaggio di Taghazout (30 minuti a nord di Agadir) offre onde di reef di livello mondiale adatte a tutti i livelli. Anchor Point produce le onde più lunghe del Marocco. La stagione del surf dura tutto l'anno, con le mareggiate più grandi da ottobre a marzo." },
      { title: "Parco Nazionale di Souss-Massa", desc: "Una riserva di zone umide costiere a 45 minuti a sud di Agadir, che ospita una delle ultime colonie selvatiche di ibis eremita al mondo, grandi stormi di fenicotteri e la gazzella dorcas in pericolo. Un patrimonio naturale straordinario e spesso trascurato." },
      { title: "Paradise Valley", desc: "Un'oasi nascosta a 30 km nell'entroterra da Agadir: una stretta gola bordata di palme con una serie di pozze naturali turchesi per fare il bagno. Raggiungibile con una breve discesa dalla strada, è la fuga perfetta di mezza giornata lontano dalla spiaggia." },
      { title: "Il paese dell'argan", desc: "La piana del Souss, tra Agadir e Taroudant, è l'unico luogo al mondo dove l'argan cresce spontaneo. Cooperative femminili raccolgono e spremono l'olio a mano. Visitarne una è un'esperienza turistica autentica e significativa." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da marzo a maggio: caldo, soleggiato, ideale per spiaggia e surf. L'acqua atlantica è ancora fresca ma balneabile." },
      { name: "Estate", emoji: "☀️", rating: 4, note: "Da giugno ad agosto: caldo costante. I venti dominanti dall'Atlantico mantengono le temperature più basse rispetto all'entroterra marocchino." },
      { name: "Autunno", emoji: "🍂", rating: 5, note: "Da settembre a novembre: inizia la migliore stagione del surf. Mare caldo, mareggiate costanti." },
      { name: "Inverno", emoji: "❄️", rating: 4, note: "Da dicembre a febbraio: mite per gli standard marocchini (15-20°C). Le mareggiate più grandi dell'anno. Spiaggia meno affollata." },
    ],
    travelTips: [
      "Agadir dista 3 ore a sud di Marrakech via strada (256 km) o 40 minuti con un volo diretto.",
      "Il lungomare è ottimo per andare in bicicletta: diversi noleggi operano lungo la costa.",
      "Le lezioni di surf sono disponibili tutto l'anno a Taghazout per principianti. Prenotate direttamente presso il surf camp, non tramite i banchi turistici.",
      "I souk di Inezgane (10 km a sud di Agadir) sono un'alternativa più autentica e meno turistica al souk cittadino di Agadir.",
      "La collina della kasba restaurata di Agadir fu rasa al suolo dal terremoto del 1960: restano solo le mura, ma la vista sulla baia merita la salita.",
    ],
    faqs: [
      { q: "Agadir è una buona base per esplorare il sud del Marocco?", a: "Sì: Agadir è idealmente posizionata per gite di un giorno a Paradise Valley, Immouzer du Kandar, Taroudant (la 'piccola Marrakech'), il souk dell'argenteria di Tiznit e le montagne dell'Anti-Atlante. Sono possibili anche viaggi di più giorni verso il deserto del Sahara da Agadir (560 km fino a Merzouga)." },
      { q: "Qual è la stagione del surf a Taghazout?", a: "Taghazout offre onde surfabili tutto l'anno. Le mareggiate più grandi e potenti arrivano da ottobre a marzo. Da aprile a settembre sono più morbide e adatte a surfisti principianti-intermedi. La temperatura dell'acqua varia dai 16°C in inverno ai 22°C in estate." },
      { q: "Posso combinare Agadir e Marrakech in un unico viaggio?", a: "Assolutamente: è l'approccio standard per molti dei nostri tour. Atterrate a Marrakech, viaggiate verso Agadir via terra (attraversando i contrafforti dell'Atlante e il paese dell'argan) e tornate a Marrakech per il volo di ritorno. O viceversa. Il percorso del valico montano di Tizi n'Test è spettacolare." },
    ],
    relatedCategories: ["day-tours", "hiking"],
    relatedOrigins: ["agadir"],
    seoTitle: "Guida di viaggio ad Agadir — Spiaggia atlantica, surf ed escursioni | Marrakech Eco Tours",
    seoDescription: "Guida completa ad Agadir: surf a Taghazout, Parco Nazionale di Souss-Massa, Paradise Valley ed escursioni dalla costa atlantica del Marocco. Tour in piccoli gruppi con guide locali.",
  },
  {
    slug: "ouzoud",
    name: "Cascate di Ouzoud",
    subtitle: "La meraviglia naturale più spettacolare del Marocco",
    region: "Béni Mellal-Khénifra",
    lat: 32.0187,
    lng: -6.7188,
    heroImage: "https://images.unsplash.com/photo-1535027341838-aa4d6ab54a25?w=1400&q=85",
    about:
      "Le Cascades d'Ouzoud sono le più spettacolari del Nord Africa: una tripla cascata che precipita per 110 metri su scogliere rossastre fino a una piscina turchese alimentata dal fiume El-Abid. Il nome 'Ouzoud' significa 'macinare le olive' in tamazight (berbero), un riferimento ai tradizionali frantoi che operano qui da generazioni. Il sito si trova in una profonda gola circondata da uliveti e ficheti, ed è la casa di una colonia di magot selvatici di Barberia, gli unici primati selvatici d'Africa al di fuori dell'Africa subsahariana.",
    knownFor: [
      "Una tripla cascata di 110 m, la più spettacolare del Marocco",
      "Colonia di magot selvatici di Barberia (l'unico primate selvatico del Nord Africa)",
      "Piscina naturale turchese alla base per fare il bagno",
      "Arcobaleno visibile a mezzogiorno quando il sole è alto",
      "Tradizionali frantoi berberi nella gola",
      "Suggestiva escursione nella gola lungo il fiume El-Abid",
    ],
    highlights: [
      { title: "Le cascate", desc: "Tre corsi d'acqua paralleli convergono su una serie di cornici rocciose prima della caduta principale. Il volume è massimo dopo le piogge invernali (gennaio-marzo) ma le cascate scorrono tutto l'anno. A mezzogiorno, in primavera e in estate, si forma un arcobaleno permanente nella nebbia: uno dei fenomeni naturali più belli del Marocco." },
      { title: "Magot di Barberia", desc: "La colonia di magot selvatici di Barberia (Macaca sylvanus) a Ouzoud è una delle popolazioni di primati più accessibili al mondo. I magot sono abituati alla presenza umana ma restano selvatici: non nutriteli e tenete il cibo al sicuro. Sono protetti dalla legge marocchina." },
      { title: "L'escursione nella gola", desc: "Un sentiero scende dalla cima delle cascate lungo le cascate, attraversa il fiume nella piscina alla base e continua attraverso la gola. Il circuito completo (3-4 ore) passa per frantoi tradizionali, punti per il bagno e punti panoramici che riportano alla vista delle cascate dal basso." },
      { title: "I frantoi", desc: "Le famiglie berbere gestiscono presse per olive a ruota di pietra nella gola sotto le cascate da secoli. Nella stagione della raccolta delle olive (novembre-gennaio) si può osservare la spremitura a freddo tradizionale, eseguita esattamente come da generazioni." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "Da marzo a maggio: massima portata d'acqua, arcobaleno permanente, fiori selvatici. Il momento migliore per la visita." },
      { name: "Estate", emoji: "☀️", rating: 4, note: "Da giugno ad agosto: caldo (35°C e oltre) ma la piscina è rinfrescante. Molto affollata nei fine settimana." },
      { name: "Autunno", emoji: "🍂", rating: 4, note: "Da settembre a novembre: stagione della raccolta delle olive, buona portata d'acqua, temperature piacevoli." },
      { name: "Inverno", emoji: "❄️", rating: 3, note: "Da dicembre a febbraio: massima piovosità, cascate al massimo della loro potenza, ma fresco e occasionalmente fangoso." },
    ],
    travelTips: [
      "Ouzoud dista 3 ore da Marrakech (150 km). La maggior parte dei visitatori la combina con un'escursione di un giorno tornando la sera stessa.",
      "Arrivate presto (prima delle 9) per avere le cascate e la piscina alla base quasi tutte per voi.",
      "Il sentiero di discesa verso la base può essere scivoloso: indossate scarpe con buona presa, non sandali.",
      "Portate un cambio di vestiti: la nebbia e il bagno rendono inevitabile bagnarsi.",
      "Non nutrite i magot: disturba il loro comportamento naturale e li abitua al cibo umano.",
    ],
    faqs: [
      { q: "Quanto distano le cascate di Ouzoud da Marrakech?", a: "Ouzoud si trova a circa 150 km da Marrakech, circa 3 ore in auto. Il percorso attraversa Azilal e l'altopiano di Béni Mellal. Offriamo escursioni guidate di un'intera giornata da Marrakech che includono trasporto, guida ed escursione nella gola." },
      { q: "Posso fare il bagno alla base delle cascate?", a: "Sì: la piscina naturale alla base delle cascate è uno dei luoghi per nuotare più belli del Marocco. L'acqua è fredda (alimentata da sorgenti di montagna) ma rinfrescante, soprattutto in estate." },
      { q: "Ouzoud è una buona gita di un giorno da Marrakech?", a: "Sì: è l'escursione di un giorno più popolare da Marrakech. Una giornata intera (7-19) permette 4-5 ore alle cascate e nella gola. Un pernottamento nel villaggio consente una visita mattutina prima dell'arrivo delle folle giornaliere, il modo migliore per viverla." },
    ],
    relatedCategories: ["hiking", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Gita di un giorno alle cascate di Ouzoud da Marrakech — Guida e tour | Marrakech Eco Tours",
    seoDescription: "Visita le cascate di Ouzoud (110 m) da Marrakech: escursioni guidate nella gola, magot selvatici di Barberia, piscine per nuotare e arcobaleno naturale nella nebbia. Tour di un'intera giornata con guide locali.",
  },
  {
    slug: "essaouira",
    name: "Essaouira",
    subtitle: "La ventosa città fortificata dell'Atlantico",
    region: "Marrakech-Safi",
    lat: 31.5085,
    lng: -9.7595,
    heroImage: "https://images.unsplash.com/photo-1555686367-56d5186965d5?w=1400&q=85",
    about:
      "Essaouira è il grande contrappunto atlantico di Marrakech: imbiancata a calce dove Marrakech è rosso rosato, spazzata dal vento dove Marrakech è immobile, e profondamente rilassata dove Marrakech è elettrica. Le fortificazioni portoghesi della città, risalenti al XVIII secolo, si proiettano nella risacca atlantica, racchiudendo una medina Patrimonio dell'Umanità UNESCO con persiane blu ad arco, riparazioni di reti da pesca e musica gnawa che fluttua dalle porte dei caffè. Essaouira ha da sempre attirato artisti, musicisti e scrittori: Jimi Hendrix la visitò nel 1969, ispirando una generazione di viaggiatori a seguirne l'esempio.",
    knownFor: [
      "Medina patrimonio UNESCO con mura marittime portoghesi del XVIII secolo",
      "Kitesurf e windsurf di livello mondiale (venti atlantici costanti)",
      "Musica gnawa, il blues spirituale dell'eredità africana del Marocco",
      "Flotta peschereccia blu attiva e pesce fresco",
      "Intarsio in legno di thuya, l'artigianato caratteristico di Essaouira",
      "I bastioni della Skala, una passeggiata costeggiata da cannoni sopra l'Atlantico",
    ],
    highlights: [
      { title: "I bastioni", desc: "Le mura marittime di Essaouira furono costruite nel XVIII secolo da un architetto francese incaricato dal sultano alauita. La Skala de la Ville, un'ampia terrazza costeggiata da cannoni affacciata sull'Atlantico, è una delle passeggiate più suggestive del Marocco, specialmente al tramonto quando rientrano le barche da pesca." },
      { title: "Musica gnawa", desc: "Essaouira è la casa spirituale della musica gnawa, l'antica tradizione musicale di influenza africana del Marocco, radicata nella cultura delle comunità dell'Africa occidentale portate in Marocco come schiave. Il Festival Gnaoua e Musiche del Mondo (giugno) richiama musicisti da tutta l'Africa e non solo." },
      { title: "Paradiso del kitesurf", desc: "I costanti venti alisei che soffiano da nord-est durante i mesi estivi rendono Essaouira una delle grandi destinazioni mondiali del kitesurf. La spiaggia a sud della città è frequentata tutto l'anno da surfisti, kitesurfisti e windsurfisti." },
      { title: "La medina", desc: "A differenza del labirinto di Marrakech, quella di Essaouira è pianificata logicamente a griglia: più facile da percorrere, ma altrettanto suggestiva. La Porte de la Marine, i souk delle spezie e della gioielleria e l'asta del pesce al porto sono tra i suoi punti forti." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 4, note: "Da aprile a giugno: caldo, venti moderati, serate lunghe. Festival Gnaoua a giugno." },
      { name: "Estate", emoji: "☀️", rating: 5, note: "Da luglio ad agosto: alisei a piena forza, perfetti per il kitesurf. Fresco per gli standard marocchini (22-26°C)." },
      { name: "Autunno", emoji: "🍂", rating: 4, note: "Da settembre a novembre: temperature piacevoli, buon surf, meno turisti dell'estate." },
      { name: "Inverno", emoji: "❄️", rating: 3, note: "Da dicembre a marzo: la stagione più ventosa e fresca. La città è al suo momento più tranquillo e suggestivo." },
    ],
    travelTips: [
      "Essaouira dista 3 ore da Marrakech (170 km). Le gite di un giorno sono possibili, ma un pernottamento è decisamente preferibile.",
      "Portate uno strato antivento anche in estate: il costante vento alisio può rendere il lungomare pungente.",
      "Il pesce più fresco si trova ai banchi del porto (a est della porta principale): scegliete il vostro pesce e fatelo grigliare subito.",
      "L'intarsio in legno di thuya è la specialità artigianale locale: cercate pezzi autentici realizzati con la radica di thuya, non imitazioni tinte a pino.",
      "Camminate sui bastioni al tramonto per la luce migliore sull'Atlantico e sulla flotta peschereccia.",
    ],
    faqs: [
      { q: "Come si arriva da Marrakech a Essaouira?", a: "Gli autobus Supratours partono due volte al giorno da Marrakech (Bab Doukkala) e impiegano 2,5-3 ore. I taxi collettivi sono più veloci ma più affollati. Auto private e transfer turistici impiegano 2,5 ore sull'autostrada A7. Non esiste un collegamento ferroviario." },
      { q: "Essaouira è adatta a chi non fa surf?", a: "Assolutamente: Essaouira è una delle destinazioni più complete del Marocco per chi non pratica surf. La medina, i bastioni, la musica gnawa, il pesce fresco, le botteghe artigiane e le passeggiate in spiaggia offrono un itinerario completo senza alcuno sport acquatico." },
      { q: "Perché Jimi Hendrix visitò Essaouira?", a: "Hendrix visitò Essaouira nel 1969 durante il suo lungo soggiorno in Marocco, attratto dalla comunità artistica della città e dalle tradizioni musicali gnawa. Vi rimase per diversi giorni e da allora la visita è diventata parte celebrata della mitologia culturale della città. Una casa in cui presumibilmente soggiornò vicino alla medina è oggi un piccolo museo, sebbene la sua accuratezza storica sia contestata." },
    ],
    relatedCategories: ["day-tours", "cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guida di viaggio a Essaouira — Kitesurf, musica gnawa e medina | Marrakech Eco Tours",
    seoDescription: "Scopri Essaouira: medina atlantica patrimonio UNESCO, kitesurf di livello mondiale, musica gnawa e pesce fresco. Gite di un giorno e tour di più giorni da Marrakech con guide locali.",
  },
];

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}
