import type { Destination } from "./destinations";

export const DESTINATIONS: Destination[] = [
  {
    slug: "marrakech",
    name: "Marrakech",
    subtitle: "La Ville Rouge",
    region: "Marrakech-Safi",
    lat: 31.6295,
    lng: -7.9811,
    heroImage: "https://images.unsplash.com/photo-1708823081494-3e5bbd2ce931?w=1400&q=85",
    about:
      "Marrakech est la ville la plus vibrante du Maroc — un labyrinthe millénaire de souks, de palais et de théâtre de rue bâti dans une pierre couleur rose. La médina de Marrakech est classée au patrimoine mondial de l'UNESCO et compte parmi les zones urbaines les plus densément peuplées au monde, avec plus de 90 000 habitants sur un espace de moins de deux kilomètres carrés. En son cœur se trouve Jemaa el-Fna, la place publique la plus extraordinaire de la planète : marché aux épices et stands de jus de fruits le jour, carnaval de conteurs, d'acrobates et de musiciens gnaoua la nuit — un spectacle donné chaque soir depuis 900 ans.",
    knownFor: [
      "Jemaa el-Fna — le plus grand théâtre à ciel ouvert du monde",
      "14 souks de corporations artisanales au cœur de la médina ancienne",
      "La mosquée Koutoubia et les tombeaux saadiens",
      "Le Jardin Majorelle et le Musée des Arts Berbères",
      "Riads secrets et culture traditionnelle du hammam",
      "Porte d'entrée du Haut Atlas (à une heure de route)",
    ],
    highlights: [
      { title: "La Médina", desc: "Une cité fortifiée classée UNESCO comptant plus de 9 000 ruelles, chacune menant vers l'inattendu. Elle abrite les souks, tanneries et marchés d'épices les plus célèbres du Maroc." },
      { title: "Jemaa el-Fna", desc: "La grande place se métamorphose deux fois par jour. Les mêmes familles tiennent les mêmes échoppes depuis des générations — merguez grillées, soupe harira et jus d'orange fraîchement pressé." },
      { title: "Le Jardin Majorelle", desc: "Conçu par le peintre français Jacques Majorelle dans les années 1920 puis restauré par Yves Saint Laurent, ce jardin est une oasis de bleu cobalt, de bambouseraies et de cactus rares." },
      { title: "Point de départ des excursions", desc: "Marrakech est la base idéale pour explorer toute la région : le Haut Atlas et le sommet du Toubkal (1 heure), les cascades d'Ouzoud (3 heures), le Sahara (10 heures en voiture ou en excursion de nuit) et Essaouira sur la côte atlantique (3 heures)." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "De mars à mai, c'est la haute saison — chaleur douce, verdure et fleurs sauvages dans l'Atlas. Réservez tôt." },
      { name: "Été", emoji: "☀️", rating: 2, note: "De juin à août, les températures dépassent 40°C en ville. Peu adapté aux visites à pied." },
      { name: "Automne", emoji: "🍂", rating: 5, note: "De septembre à novembre, c'est excellent — chaleur agréable, saison des récoltes, moins de monde." },
      { name: "Hiver", emoji: "❄️", rating: 3, note: "De décembre à février, il fait doux et ensoleillé en ville. Les sentiers de l'Atlas peuvent être enneigés au-dessus de 2 000 m." },
    ],
    travelTips: [
      "La médina se découvre surtout à pied — faites appel à un guide local pour accéder aux quartiers situés au-delà des rues touristiques principales.",
      "Négociez les prix dans les souks — la première offre est rarement le prix réel.",
      "Portez des vêtements légers et respirants. Une tenue modeste (épaules et genoux couverts) est appréciée dans la médina et les mosquées.",
      "Gardez sur vous des pièces de monnaie en dirhams pour les stands de nourriture et les pourboires.",
      "Les plus beaux riads sont invisibles de l'extérieur — une simple porte dans un mur nu.",
    ],
    faqs: [
      { q: "Comment se rendre de l'aéroport de Marrakech à la médina ?", a: "Un taxi depuis l'aéroport de la Ménara jusqu'à la médina coûte environ 100 à 150 MAD (9 à 13 €) et prend 15 à 20 minutes. Convenez du prix avant de monter. Certains riads proposent un transfert depuis l'aéroport." },
      { q: "Marrakech est-elle sûre pour les voyageurs seuls ?", a: "Oui — Marrakech est globalement sûre et dispose d'une solide infrastructure touristique. Les principaux désagréments sont les rabatteurs insistants dans la médina et les scooters dans les ruelles étroites. Restez vigilant dans la foule et surveillez vos effets personnels." },
      { q: "Quel est le meilleur quartier où loger à Marrakech ?", a: "La médina (vieille ville) offre l'ambiance la plus authentique. Les quartiers de la Kasbah et de Mouassine proposent les riads les plus calmes, à proximité des sites principaux. Guéliz (la ville nouvelle) est plus occidentalisée, avec un stationnement plus facile." },
      { q: "Ai-je besoin d'un visa pour le Maroc ?", a: "Les citoyens de l'UE, du Royaume-Uni, des États-Unis, du Canada, de l'Australie et de la plupart des pays occidentaux n'ont pas besoin de visa pour un séjour de moins de 90 jours. Votre passeport doit rester valide au moins 6 mois après la date d'entrée." },
      { q: "Quelle est la monnaie utilisée et peut-on payer par carte ?", a: "Le Maroc utilise le dirham (MAD). Les cartes sont acceptées dans la plupart des hôtels et grands restaurants, mais les souks et petits commerçants n'acceptent que les espèces. Les distributeurs automatiques sont nombreux dans la médina et à Guéliz." },
    ],
    relatedCategories: ["cultural", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guide de voyage à Marrakech — Meilleures excursions et conseils | Marrakech Eco Tours",
    seoDescription: "Guide complet de Marrakech : balades dans la médina, souks, Jemaa el-Fna et excursions d'une journée vers l'Atlas et le Sahara. Réservez des circuits en petit groupe avec des guides berbères locaux.",
  },
  {
    slug: "high-atlas",
    name: "Haut Atlas",
    subtitle: "Le toit de l'Afrique du Nord",
    region: "Marrakech-Safi",
    lat: 31.0573,
    lng: -7.9149,
    heroImage: "https://images.unsplash.com/photo-1611859836043-a9177f500a27?w=1400&q=85",
    about:
      "Le Haut Atlas est l'une des grandes chaînes montagneuses d'Afrique — une épine dorsale de 2 400 km de sommets englacés, de villages berbères et d'antiques sentiers muletiers, s'étendant de l'Atlantique à la frontière algérienne. À son point culminant se dresse le Jbel Toubkal (4 167 m), le toit de l'Afrique du Nord et le sommet de 4 000 mètres le plus accessible du continent. Depuis des millénaires, les communautés berbères cultivent les vallées en terrasses et parcourent les hauts cols sur des itinéraires inchangés depuis les caravanes du Moyen Âge.",
    knownFor: [
      "Le Jbel Toubkal — plus haut sommet d'Afrique du Nord à 4 167 m",
      "Le village d'Imlil — point de départ traditionnel de l'ascension du Toubkal",
      "Des communautés berbères montagnardes fortes de siècles de tradition",
      "Lacs d'altitude, gorges et vallées glaciaires",
      "La traversée du massif du M'Goun — le trek le plus reculé du Maroc",
      "Des vues spectaculaires depuis les crêtes, du Maroc jusqu'à l'Espagne",
    ],
    highlights: [
      { title: "Le sommet du Toubkal", desc: "Le trek de 4 jours vers le Toubkal est le défi montagnard le plus emblématique du Maroc. Partant d'Imlil à 1 740 m, l'ascension traverse des villages berbères, des refuges de montagne et le col du Tizi n'Ouanoums avant l'ultime effort vers le sommet à 4 167 m." },
      { title: "La vallée d'Imlil", desc: "Le village porte d'entrée de toute randonnée dans le Haut Atlas. Entourée de noyeraies et de champs de blé en terrasses, Imlil abrite une communauté de guides de montagne dont les familles arpentent ces sentiers depuis des générations." },
      { title: "Les villages berbères", desc: "L'Atlas abrite des communautés amazighes (berbères) autochtones qui ont préservé leur langue, leur culture et leur architecture à travers des siècles d'histoire. Nombre de villages ne sont accessibles que par des sentiers muletiers, sans route." },
      { title: "Le massif du M'Goun", desc: "Pour les trekkeurs expérimentés en quête de solitude, la traversée du M'Goun (7 à 10 jours) longe certains des paysages de gorges et de crêtes les plus spectaculaires d'Afrique du Nord, avec quasiment aucune infrastructure touristique." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "D'avril à juin : fleurs sauvages, neige en recul sur les hauts cols, conditions de trek idéales." },
      { name: "Été", emoji: "☀️", rating: 4, note: "De juillet à août : sentiers du sommet dégagés, chaleur dans les vallées mais fraîcheur en altitude. Haute saison." },
      { name: "Automne", emoji: "🍂", rating: 5, note: "De septembre à octobre : sans doute les meilleures conditions — ciel stable, couleurs éclatantes, moins de trekkeurs." },
      { name: "Hiver", emoji: "❄️", rating: 3, note: "De novembre à mars : le sommet du Toubkal exige crampons et piolet. Magnifique mais exigeant." },
    ],
    travelTips: [
      "Acclimatez-vous à Marrakech (460 m) pendant au moins une journée avant de monter à Imlil (1 740 m).",
      "Le Toubkal exige une bonne condition physique mais aucune technique d'escalade en été. En hiver, c'est un véritable objectif alpin.",
      "Faites appel à un guide berbère local agréé — il connaît chaque pierre de la montagne et sa présence est obligatoire dans le Parc National du Toubkal.",
      "Les mules peuvent porter le matériel sur la plupart des itinéraires de l'Atlas — profitez-en pour voyager plus léger.",
      "Emportez des couches chaudes même en été : les températures au refuge du Toubkal peuvent descendre sous zéro la nuit.",
    ],
    faqs: [
      { q: "Le trek du Toubkal est-il difficile ?", a: "Le Toubkal est un objectif de randonnée exigeant (et non d'escalade technique) qui demande une bonne condition cardiovasculaire. Il faut être à l'aise pour marcher 6 à 8 heures par jour avec un sac à dos. En été, aucun équipement spécial n'est nécessaire. En hiver, crampons et piolet sont indispensables." },
      { q: "Combien de temps faut-il pour atteindre le sommet du Toubkal ?", a: "L'itinéraire classique depuis Imlil, aller-retour, prend 3 à 4 jours. Jour 1 : Imlil jusqu'au refuge (4 à 5 heures). Jour 2 : tentative de sommet depuis le refuge (3 à 4 heures de montée, 2h30 de descente). Jours 3-4 : descente et visites optionnelles de villages berbères." },
      { q: "Un guide est-il obligatoire pour le trek du Toubkal ?", a: "Un guide agréé n'est pas légalement obligatoire mais fortement recommandé, et exigé par la plupart des opérateurs responsables. Le terrain est exigeant, la météo change vite, et les guides locaux apportent sécurité, connaissance des itinéraires et un précieux contexte culturel." },
      { q: "Quelle est la meilleure base pour la randonnée dans le Haut Atlas ?", a: "Le village d'Imlil (1 740 m), à 62 km de Marrakech, est le point de départ classique pour le Toubkal. Azilal sert de base pour les treks du massif du M'Goun. Les deux nécessitent un guide et une préparation adéquate." },
    ],
    relatedCategories: ["trekking", "hiking"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guide de voyage du Haut Atlas — Trek du Toubkal et villages berbères | Marrakech Eco Tours",
    seoDescription: "Explorez le Haut Atlas avec des guides locaux certifiés : trek au sommet du Toubkal (4 167 m), balades dans les villages berbères et traversées de plusieurs jours dans l'Atlas. Petits groupes au départ de Marrakech.",
  },
  {
    slug: "sahara",
    name: "Désert du Sahara",
    subtitle: "Les dunes dorées de l'Erg Chebbi",
    region: "Drâa-Tafilalet",
    lat: 31.1513,
    lng: -3.9785,
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1400&q=85",
    about:
      "L'Erg Chebbi, près du village de Merzouga, est la portion la plus spectaculaire de mer de sable saharienne du Maroc — un champ de dunes étoilées de 50 km² culminant à 150 mètres au-dessus de la hamada plane (plaine caillouteuse). Les dunes sont entièrement composées d'un sable fin orangé-rouge, sculpté par les vents dominants du nord-ouest en classiques croissants de barkhanes. Au coucher et au lever du soleil, la lumière transforme l'Erg en un paysage d'or et de cuivre en fusion, unique au monde.",
    knownFor: [
      "Des dunes atteignant 150 m — parmi les plus hautes du Maroc",
      "Balade à dos de chameau au coucher du soleil, au cœur de l'Erg",
      "Nuits authentiques sous les étoiles dans un campement nomade berbère",
      "Observation de la Voie lactée, loin de toute pollution lumineuse",
      "Le village de Merzouga — porte d'entrée du désert",
      "Excursions en quad et en 4×4 dans le désert",
    ],
    highlights: [
      { title: "Les dunes de l'Erg Chebbi", desc: "Le champ de dunes est le plus saisissant à l'heure dorée — arrivez au coucher du soleil pour ce spectacle de lumière qui teinte le sable de toutes les nuances de cuivre, d'ambre et de rose. À l'aube, les couleurs s'inversent, les bleus frais cédant la place à l'or chaud tandis que le soleil grimpe sur la crête des dunes." },
      { title: "Balade à dos de chameau", desc: "La traversée traditionnelle de l'Erg se fait à dos de chameau — un voyage lent et méditatif au cœur du désert qui vous relie à des millénaires de routes caravanières. Nos guides berbères empruntent les mêmes chemins que leurs ancêtres." },
      { title: "Nuits en campement désertique", desc: "Dormir sous une tente berbère au cœur de l'Erg, loin de toute route ou habitation, est l'une des expériences les plus profondes qui soient. Le silence est absolu. La Voie lactée, dans un ciel épargné par toute pollution lumineuse, y est extraordinaire." },
      { title: "Activités dans le désert", desc: "Au-delà de la classique balade à dos de chameau, l'Erg et la hamada environnante offrent du surf sur les pentes des dunes, des excursions en quad sur les plaines caillouteuses et des sorties en 4×4 vers les oasis et sites de fossiles du désert." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "De mars à mai : températures idéales (20-28°C), parfois des fleurs sauvages dans la hamada après les pluies hivernales." },
      { name: "Été", emoji: "☀️", rating: 1, note: "De juin à août : chaleur extrême (40-48°C). Un voyage dans le désert est déconseillé en plein été." },
      { name: "Automne", emoji: "🍂", rating: 5, note: "De septembre à novembre : journées chaudes, nuits fraîches — des conditions parfaites pour le camping dans le désert." },
      { name: "Hiver", emoji: "❄️", rating: 4, note: "De décembre à février : nuits froides (proches de zéro en janvier) mais ciels d'une clarté saisissante. Prévoyez des vêtements chauds pour le campement." },
    ],
    travelTips: [
      "Emportez des vêtements chauds pour les nuits du désert — les températures chutent fortement après le coucher du soleil, même au printemps et en automne.",
      "Prévoyez une lampe torche et de l'eau supplémentaire pour les balades à dos de chameau. Les dunes peuvent désorienter dans le noir.",
      "Le sable s'infiltre partout. Utilisez un sac étanche pour le matériel photo et fermez bien vos affaires de toilette.",
      "Le surf sur dunes est amusant mais physiquement exigeant — remonter des dunes de 150 m est épuisant.",
      "Le lever du soleil sur l'Erg est aussi spectaculaire que le coucher — réglez votre réveil et grimpez sur la crête de dune la plus proche avant le jour." ,
    ],
    faqs: [
      { q: "À quelle distance se trouve Merzouga de Marrakech ?", a: "Merzouga se trouve à environ 560 km de Marrakech — soit 9 à 10 heures de route. La plupart des circuits désertiques empruntent un itinéraire à l'aller (généralement via les gorges du Dadès et la vallée des Mille Kasbahs) et un autre au retour, par une route méridionale différente. Un aller-retour de nuit est aussi possible pour les circuits économiques." },
      { q: "Un circuit de 3 jours au Sahara est-il suffisant ?", a: "3 jours permettent de vivre l'essentiel : traversée de l'Atlas et du pays des kasbahs, une nuit complète au campement désertique, et le trajet retour. Pour une expérience plus complète, 4 à 5 jours permettent d'explorer la vallée des Roses, les gorges du Todra et plusieurs zones de dunes." },
      { q: "Qu'est-ce qui est inclus dans une nuit de campement au Sahara ?", a: "Les nuits de campement classiques comprennent une tente berbère traditionnelle, un dîner (tajine et couscous), de la musique live autour du feu de camp, et un petit-déjeuner avant la balade à dos de chameau au lever du soleil. Les campements privés plus luxueux disposent de véritables lits et de salles de bain privatives." },
      { q: "Puis-je visiter le Sahara en toute autonomie ?", a: "Oui, mais l'expérience est nettement plus riche avec un guide local expérimenté. La navigation dans les dunes n'est pas simple, et les guides locaux apportent un contexte culturel, un accès linguistique aux familles berbères, et une logistique qui demanderait des jours à organiser seul." },
    ],
    relatedCategories: ["desert"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Circuit dans le désert du Sahara depuis Marrakech — Guide de l'Erg Chebbi et Merzouga | Marrakech Eco Tours",
    seoDescription: "Découvrez le désert du Sahara avec des guides certifiés : balades à dos de chameau, nuits en campement berbère et lever du soleil sur les dunes de 150 m de l'Erg Chebbi. Circuits désertiques de 2 à 4 jours au départ de Marrakech.",
  },
  {
    slug: "fes",
    name: "Fès el-Bali",
    subtitle: "La cité médiévale vivante",
    region: "Fès-Meknès",
    lat: 34.0545,
    lng: -4.9815,
    heroImage: "https://images.unsplash.com/photo-1582742850838-24590fb39fdc?w=1400&q=85",
    about:
      "Fès el-Bali est sans doute l'une des survivances urbaines les plus remarquables au monde — une cité médiévale pleinement fonctionnelle de 156 000 habitants, couvrant 256 hectares, habitée sans interruption depuis 789 après J.-C. C'est la plus grande zone urbaine sans voiture au monde. Chaque rue de son labyrinthe de 9 400 ruelles voit ses marchandises transportées à dos d'homme ou de mule. Les mêmes artisanats se perpétuent dans les mêmes ateliers depuis mille ans : tannage du cuir, émaillage des céramiques, incrustation du laiton, zellige. La ville fut fondée par Moulay Idriss Ier et s'étendit sous la dynastie mérinide pour devenir le grand foyer de savoir islamique qu'elle demeure aujourd'hui.",
    knownFor: [
      "La plus grande zone urbaine sans voiture au monde — 9 400 ruelles",
      "La tannerie Chouara — inchangée depuis le XIe siècle",
      "L'université Al Quaraouiyine, fondée en 859 — la plus ancienne au monde",
      "La médersa Bou Inania et la médersa Attarine",
      "Le Mellah (quartier juif) et ses vues depuis les toits",
      "Une tradition artisanale vivante : zellige, broderie, cuivre, cuir",
    ],
    highlights: [
      { title: "La tannerie Chouara", desc: "Le site le plus photographié du Maroc après le Sahara. Des cuves de pierre remplies de teintures (safran, coquelicot, henné, indigo) où les ouvriers, jambes nues jusqu'aux genoux, traitent les peaux exactement comme il y a 800 ans. À admirer depuis les terrasses des boutiques de cuir surplombant les bassins." },
      { title: "La mosquée et l'université Al Quaraouiyine", desc: "Fondée en 859 par une femme, Fatima al-Fihri, Al Quaraouiyine est reconnue par l'UNESCO comme la plus ancienne université encore en activité au monde. Les non-musulmans ne peuvent pas entrer dans la mosquée, mais la cour entrevue à travers les portails sculptés est l'un des grands sites architecturaux du Maroc." },
      { title: "Le labyrinthe de la médina", desc: "Contrairement à celle de Marrakech, la médina de Fès est véritablement labyrinthique — même les guides expérimentés se repèrent aux points de repère plutôt qu'à une carte mentale. Se perdre un peu est le meilleur moyen de découvrir le vrai Fès : petites boulangeries, tisserands de tapis, mosquées de quartier et petites places où les anciens jouent aux cartes." },
      { title: "Le Mellah", desc: "Le quartier juif du vieux Fès, jadis foyer de l'une des communautés juives les plus importantes d'Afrique du Nord, abrite une architecture magnifique du milieu du XXe siècle, une synagogue restaurée, et les meilleures vues de la ville depuis ses terrasses surélevées et son cimetière." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "De mars à mai : températures agréables (18-26°C), longues soirées, paysages verdoyants." },
      { name: "Été", emoji: "☀️", rating: 2, note: "De juin à août : très chaud (35-40°C). La médina devient étouffante. Visites en matinée uniquement recommandées." },
      { name: "Automne", emoji: "🍂", rating: 5, note: "De septembre à novembre : climat parfait, saison des récoltes, Festival de Fès des musiques sacrées du monde (novembre)." },
      { name: "Hiver", emoji: "❄️", rating: 3, note: "De décembre à février : frais et parfois pluvieux. Les tanneries sont moins actives et plus faciles d'accès." },
    ],
    travelTips: [
      "Fès se trouve à 3-4 heures de route de Marrakech. La plupart des circuits des villes impériales combinent Fès, Meknès et Volubilis sur 3 jours ou plus.",
      "Un guide local est précieux dans la médina — s'y orienter seul mène souvent à la frustration. Même les habitants s'y perdent.",
      "Les tanneries sont les plus colorées le matin (le tannage de l'après-midi a lieu plus tard dans la journée).",
      "Achetez vos articles en cuir directement dans les boutiques des tanneries — la qualité y est authentique et l'origine traçable.",
      "Goûtez les plats fassis emblématiques : la pastilla (tourte au pigeon et aux amandes), la soupe harira et la bastilla au lait.",
    ],
    faqs: [
      { q: "Combien de jours faut-il prévoir à Fès ?", a: "Deux journées complètes constituent le minimum pour couvrir les principaux sites de la médina, les tanneries et la Ville Nouvelle. Trois jours permettent d'explorer le Mellah, le quartier andalou, de faire une excursion aux ruines romaines de Volubilis, et de parcourir la médina à un rythme plus détendu." },
      { q: "Fès fait-elle partie de l'itinéraire routier Marrakech-Fès ?", a: "Oui — l'itinéraire Marrakech-Fès est le grand classique routier du Maroc, généralement parcouru en 3 à 6 jours via les gorges du Dadès, les gorges du Todra, le Sahara de Merzouga et les forêts de cèdres du Moyen Atlas. C'est l'un des plus beaux road trips d'Afrique du Nord." },
      { q: "Faut-il loger dans la médina ou dans la Ville Nouvelle ?", a: "Logez dans la médina. L'expérience du riad est essentielle pour comprendre Fès — franchir un mur extérieur tout simple pour découvrir une cour intérieure ornée avec fontaine est l'un des moments les plus envoûtants du Maroc. La Ville Nouvelle n'a aucun caractère historique." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guide de voyage à Fès el-Bali — Visites de la médina, tanneries et ville impériale | Marrakech Eco Tours",
    seoDescription: "Explorez Fès el-Bali, la cité médiévale la plus intacte au monde. Visites guidées de la tannerie Chouara, de l'université Al Quaraouiyine et de la médina aux 9 400 ruelles. Excursions d'une journée et circuits de plusieurs jours au départ de Marrakech.",
  },
  {
    slug: "chefchaouen",
    name: "Chefchaouen",
    subtitle: "La perle bleue du Maroc",
    region: "Tanger-Tétouan-Al Hoceïma",
    lat: 35.1688,
    lng: -5.2689,
    heroImage: "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1400&q=85",
    about:
      "Chefchaouen s'étend sur les flancs des montagnes du Rif, à 600 m d'altitude — une médina petite et remarquablement bien préservée, dont les murs, les escaliers et les pots de fleurs sont uniformément peints de bleu et de blanc. Cette tradition du bleu, introduite par des réfugiés juifs fuyant la Reconquista espagnole dans les années 1930, est devenue si centrale à l'identité de la ville que les habitants repeignent leur maison chaque printemps. Le résultat ne ressemble à rien d'autre au Maroc : serein, photogénique et véritablement paisible.",
    knownFor: [
      "Une médina entièrement peinte en bleu et blanc",
      "Un cadre dans les montagnes du Rif avec des vues spectaculaires sur les gorges",
      "La rivière Ras el-Ma, sa cascade et ses rochers à lessive",
      "La place Uta el-Hammam — la grande place bordée de cafés",
      "Le tissage artisanal de la laine et l'artisanat traditionnel du Rif",
      "Porte d'entrée du Parc National de Talassemtane",
    ],
    highlights: [
      { title: "La médina bleue", desc: "Chaque mur, chaque marche, chaque encadrement de porte est peint dans des nuances allant du bleu ciel pâle à l'indigo profond. La médina est assez petite pour être explorée en une journée, mais assez captivante pour y rester trois. Chaque recoin est une photographie." },
      { title: "Ras el-Ma", desc: "À quelques pas de la médina, la source de Ras el-Ma jaillit de la montagne pour former une petite rivière où les habitants lavent leur linge selon la méthode traditionnelle. Une échappée paisible loin de la place centrale, plus fréquentée par les touristes." },
      { title: "Le Parc National de Talassemtane", desc: "Le parc débute à la lisière de la médina et propose des randonnées d'une demi-journée à travers forêts de cèdres et de chênes, des marches en surplomb de la rivière Laou, et des vues plongeantes sur la ville bleue en contrebas." },
      { title: "La Mosquée espagnole", desc: "Une montée de 20 minutes depuis la médina (ou un sentier caillouteux) mène à une mosquée construite par les Espagnols, offrant une vue panoramique sur toute la ville bleue et les vallées du Rif environnantes — magnifique au coucher du soleil." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "D'avril à juin : températures douces, collines verdoyantes, fleurs sauvages sur les pentes du Rif. Haute saison." },
      { name: "Été", emoji: "☀️", rating: 4, note: "De juillet à août : chaud mais supportable en altitude. Les soirées sont fraîches. Très fréquenté — réservez à l'avance." },
      { name: "Automne", emoji: "🍂", rating: 4, note: "De septembre à novembre : températures agréables, plus calme que l'été." },
      { name: "Hiver", emoji: "❄️", rating: 2, note: "De décembre à mars : peut être froid et pluvieux. Neige occasionnelle sur les crêtes du Rif. Très calme." },
    ],
    travelTips: [
      "Chefchaouen se visite idéalement lors d'un séjour d'une nuit, pas en excursion d'une journée — la ville est la plus envoûtante tôt le matin, avant l'arrivée des cars de touristes.",
      "Les ruelles bleues sont les plus éclatantes tôt le matin (avant 9h) et en fin d'après-midi, sous la lumière dorée.",
      "Excellente base pour les randonnées dans le Rif. Renseignez-vous auprès de votre riad sur les guides de sentiers locaux.",
      "La médina est petite — s'y « perdre » volontairement mène vers les ruelles et ateliers d'artisans les plus intéressants.",
      "Achetez local : les couvertures en laine, les djellabas et les articles en cuir sont de tradition rifaine et d'excellente qualité.",
    ],
    faqs: [
      { q: "Comment se rendre à Chefchaouen depuis Marrakech ?", a: "Il n'existe pas d'itinéraire direct — Chefchaouen est à 530 km de Marrakech, soit environ 6 à 7 heures en voiture ou en bus. La plupart des visiteurs y accèdent via Fès ou Tanger. La formule la plus pratique reste un circuit de plusieurs jours dans les villes impériales, incluant Fès, Chefchaouen, Meknès et le retour vers Marrakech." },
      { q: "Pourquoi Chefchaouen est-elle peinte en bleu ?", a: "Cette tradition du bleu fut introduite dans les années 1930 par des réfugiés juifs fuyant la Reconquista espagnole. Dans la tradition juive, le bleu symbolise le ciel et les cieux. Avec le temps, toute la médina a adopté cette pratique comme élément de son identité, et les habitants repeignent leur maison chaque printemps." },
      { q: "Chefchaouen vaut-elle le déplacement depuis Marrakech ?", a: "Oui — mais il faut au moins une nuit sur place pour bien l'apprécier. Une excursion d'une journée (possible uniquement depuis Fès ou Tanger, à 1h30-2h de route) laisse trop peu de temps. Un séjour d'une nuit permet de découvrir la médina dans son calme et sa beauté les plus authentiques." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guide de voyage à Chefchaouen — La ville bleue du Maroc | Marrakech Eco Tours",
    seoDescription: "Découvrez Chefchaouen, la célèbre ville bleue du Maroc nichée dans les montagnes du Rif. Visites guidées, randonnées dans le Parc National de Talassemtane, et séjours dans la médina peinte.",
  },
  {
    slug: "agadir",
    name: "Agadir",
    subtitle: "Côte atlantique et capitale du surf",
    region: "Souss-Massa",
    lat: 30.4278,
    lng: -9.5981,
    heroImage: "https://images.unsplash.com/photo-1562874732-260714dfe537?w=1400&q=85",
    about:
      "Agadir est la principale ville balnéaire du Maroc — un port atlantique moderne entièrement reconstruit après un séisme catastrophique en 1960. Située au pied des montagnes de l'Anti-Atlas, avec un croissant de plage de sable blanc long de neuf kilomètres, Agadir sert de porte d'entrée méridionale du Maroc, aussi bien pour les voyageurs en séjour organisé que pour les aventuriers. Trente minutes plus au nord se trouve Taghazout, un village devenu l'une des destinations de surf les plus célèbres au monde. La région du Souss-Massa qui entoure Agadir abrite des parcs nationaux, des forêts d'arganiers, des zones humides peuplées de flamants roses, et des communautés berbères perpétuant un mode de vie séculaire.",
    knownFor: [
      "9 km de plage atlantique — la plus longue plage urbaine du Maroc",
      "Taghazout — surf de renommée mondiale (Anchor Point, Hash Point, Killer Point)",
      "Le Parc National de Souss-Massa (flamants roses, ibis chauves, gazelles)",
      "La Vallée du Paradis — oasis de palmiers, bassins turquoise et baignade naturelle",
      "Coopératives d'huile d'argan — le Souss est l'unique forêt d'arganiers au monde",
      "Fruits de mer frais au port de pêche actif d'Agadir",
    ],
    highlights: [
      { title: "Le surf à Taghazout", desc: "Le village de Taghazout (30 min au nord d'Agadir) offre des spots de surf de récif de renommée mondiale, adaptés à tous les niveaux. Anchor Point produit les plus longues vagues du Maroc. La saison de surf est ouverte toute l'année, avec les plus grosses houles d'octobre à mars." },
      { title: "Le Parc National de Souss-Massa", desc: "Une réserve côtière humide à 45 minutes au sud d'Agadir, abritant l'une des dernières colonies sauvages d'ibis chauve du monde, de grandes colonies de flamants roses, et la gazelle dorcas menacée. Un joyau naturel extraordinaire et souvent méconnu." },
      { title: "La Vallée du Paradis", desc: "Une oasis cachée à 30 km à l'intérieur des terres depuis Agadir — une gorge étroite bordée de palmiers avec une série de bassins naturels turquoise pour la baignade. Accessible après une courte marche depuis la route, c'est l'échappée idéale d'une demi-journée loin de la plage." },
      { title: "Le pays de l'argan", desc: "La plaine du Souss, entre Agadir et Taroudant, est le seul endroit au monde où l'arganier pousse à l'état sauvage. Des coopératives féminines récoltent et pressent l'huile à la main. Visiter l'une d'elles est une expérience touristique authentique et importante." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "De mars à mai : doux, ensoleillé, idéal pour la plage et le surf. L'eau atlantique reste fraîche mais baignable." },
      { name: "Été", emoji: "☀️", rating: 4, note: "De juin à août : chaleur fiable. Les vents dominants venus de l'Atlantique maintiennent des températures plus basses que dans l'intérieur du Maroc." },
      { name: "Automne", emoji: "🍂", rating: 5, note: "De septembre à novembre : début de la meilleure saison de surf. Mer chaude, houles régulières." },
      { name: "Hiver", emoji: "❄️", rating: 4, note: "De décembre à février : doux pour les standards marocains (15-20°C). Les plus grosses vagues de l'année. Plage moins fréquentée." },
    ],
    travelTips: [
      "Agadir se trouve à 3 heures de route au sud de Marrakech (256 km), ou à 40 minutes en vol direct.",
      "La promenade en front de mer est excellente pour le vélo — plusieurs loueurs opèrent le long du littoral.",
      "Des cours de surf pour débutants sont proposés toute l'année à Taghazout. Réservez directement auprès du camp de surf, pas via les comptoirs touristiques.",
      "Les souks d'Inezgane (10 km au sud d'Agadir) offrent une alternative plus authentique et moins touristique au souk de la ville d'Agadir.",
      "La colline de la kasbah restaurée d'Agadir fut rasée par le séisme de 1960 — seuls les murs subsistent, mais la vue sur la baie mérite la montée.",
    ],
    faqs: [
      { q: "Agadir est-elle une bonne base pour explorer le sud du Maroc ?", a: "Oui — Agadir est idéalement située pour des excursions d'une journée vers la Vallée du Paradis, Immouzer du Kandar, Taroudant (le « petit Marrakech »), le souk de bijoux en argent de Tiznit, et les montagnes de l'Anti-Atlas. Des circuits de plusieurs jours vers le désert du Sahara sont également possibles depuis Agadir (560 km jusqu'à Merzouga)." },
      { q: "Quelle est la saison de surf à Taghazout ?", a: "Taghazout offre des vagues surfables toute l'année. Les houles les plus grosses et les plus puissantes arrivent d'octobre à mars. D'avril à septembre, les conditions sont plus douces et adaptées aux surfeurs débutants et intermédiaires. La température de l'eau varie de 16°C en hiver à 22°C en été." },
      { q: "Puis-je combiner Agadir et Marrakech dans un même voyage ?", a: "Absolument — c'est la formule standard pour beaucoup de nos circuits. Atterrissez à Marrakech, rejoignez Agadir par la route (en traversant les contreforts de l'Atlas et le pays de l'argan), puis revenez à Marrakech pour votre vol retour. Ou l'inverse. La route du col de montagne du Tizi n'Test est spectaculaire." },
    ],
    relatedCategories: ["day-tours", "hiking"],
    relatedOrigins: ["agadir"],
    seoTitle: "Guide de voyage à Agadir — Plage atlantique, surf et excursions | Marrakech Eco Tours",
    seoDescription: "Guide complet d'Agadir : surf à Taghazout, Parc National de Souss-Massa, Vallée du Paradis et excursions depuis la côte atlantique du Maroc. Circuits en petit groupe avec des guides locaux.",
  },
  {
    slug: "ouzoud",
    name: "Cascades d'Ouzoud",
    subtitle: "La plus spectaculaire merveille naturelle du Maroc",
    region: "Béni Mellal-Khénifra",
    lat: 32.0187,
    lng: -6.7188,
    heroImage: "https://images.unsplash.com/photo-1535027341838-aa4d6ab54a25?w=1400&q=85",
    about:
      "Les cascades d'Ouzoud sont les plus spectaculaires d'Afrique du Nord — une triple chute d'eau dévalant 110 mètres le long de falaises rougeâtres jusqu'à un bassin turquoise alimenté par la rivière El-Abid. Le nom « Ouzoud » signifie « broyage des olives » en tamazight (berbère), en référence aux moulins à huile traditionnels qui fonctionnent ici depuis des générations. Le site se niche dans une gorge profonde entourée d'oliveraies et de figueraies, et abrite une colonie de magots de Barbarie sauvages — les seuls primates sauvages d'Afrique en dehors de l'Afrique subsaharienne.",
    knownFor: [
      "Une triple cascade de 110 m — la plus spectaculaire du Maroc",
      "Une colonie de magots de Barbarie sauvages (le seul primate sauvage d'Afrique du Nord)",
      "Un bassin naturel turquoise pour la baignade au pied des chutes",
      "Un arc-en-ciel visible en pleine journée quand le soleil est au zénith",
      "Des moulins à huile d'olive berbères traditionnels dans la gorge",
      "Une spectaculaire randonnée en gorge le long de la rivière El-Abid",
    ],
    highlights: [
      { title: "Les chutes", desc: "Trois cours d'eau parallèles convergent sur une série de corniches rocheuses avant la chute principale. Le débit est maximal après les pluies hivernales (janvier-mars), mais les chutes coulent toute l'année. En pleine journée, au printemps et en été, un arc-en-ciel permanent se forme dans les embruns — l'un des plus beaux phénomènes naturels du Maroc." },
      { title: "Les magots de Barbarie", desc: "La colonie de magots de Barbarie sauvages (Macaca sylvanus) d'Ouzoud est l'une des populations de primates les plus accessibles au monde. Les magots sont habitués à la présence humaine mais restent sauvages — ne les nourrissez pas et gardez votre nourriture bien fermée. Ils sont protégés par la loi marocaine." },
      { title: "La randonnée en gorge", desc: "Un sentier descend depuis le sommet des chutes le long des cascades, traverse la rivière au niveau du bassin de base, puis se poursuit à travers la gorge. Le circuit complet (3 à 4 heures) passe par des moulins à huile traditionnels, des lieux de baignade et des points de vue sur les chutes vues d'en bas." },
      { title: "Les moulins à huile", desc: "Des familles berbères exploitent des pressoirs à olives en pierre dans la gorge, en contrebas des chutes, depuis des siècles. Pendant la saison des récoltes (novembre-janvier), on peut y observer la pression à froid traditionnelle, réalisée exactement comme depuis des générations." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 5, note: "De mars à mai : débit d'eau maximal, arc-en-ciel permanent, fleurs sauvages. Le meilleur moment pour la visite." },
      { name: "Été", emoji: "☀️", rating: 4, note: "De juin à août : chaud (35°C et plus) mais le bassin de baignade est rafraîchissant. Très fréquenté le week-end." },
      { name: "Automne", emoji: "🍂", rating: 4, note: "De septembre à novembre : saison des récoltes d'olives, bon débit d'eau, températures agréables." },
      { name: "Hiver", emoji: "❄️", rating: 3, note: "De décembre à février : pluviométrie maximale, chutes à leur puissance maximale, mais frais et parfois boueux." },
    ],
    travelTips: [
      "Ouzoud se trouve à 3 heures de Marrakech (150 km). La plupart des visiteurs combinent une randonnée d'une journée et un retour le soir même.",
      "Arrivez tôt (avant 9h) pour avoir les chutes et le bassin de base pratiquement pour vous seul.",
      "Le sentier de descente vers la base peut être glissant — portez des chaussures avec une bonne adhérence, pas des sandales.",
      "Prévoyez un change de vêtements — les embruns et la baignade rendent le fait de se mouiller inévitable.",
      "Ne nourrissez pas les magots — cela perturbe leur comportement naturel et les habitue à la nourriture humaine.",
    ],
    faqs: [
      { q: "À quelle distance se trouvent les cascades d'Ouzoud depuis Marrakech ?", a: "Ouzoud se trouve à environ 150 km de Marrakech — soit environ 3 heures de route. Le trajet traverse Azilal et le plateau de Béni Mellal. Nous proposons des excursions guidées d'une journée complète depuis Marrakech, incluant le transport, le guide et la randonnée en gorge." },
      { q: "Peut-on se baigner au pied des cascades ?", a: "Oui — le bassin naturel au pied des chutes est l'un des plus beaux lieux de baignade du Maroc. L'eau est froide (alimentée par des sources de montagne) mais rafraîchissante, surtout en été." },
      { q: "Ouzoud est-elle une bonne excursion d'une journée depuis Marrakech ?", a: "Oui — c'est l'excursion d'une journée la plus populaire au départ de Marrakech. Une journée complète (7h-19h) permet de passer 4 à 5 heures aux chutes et dans la gorge. Un séjour d'une nuit dans le village permet une visite matinale avant l'arrivée des foules de la journée, ce qui reste la meilleure façon d'en profiter." },
    ],
    relatedCategories: ["hiking", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Excursion d'une journée aux cascades d'Ouzoud depuis Marrakech — Guide et circuits | Marrakech Eco Tours",
    seoDescription: "Visitez les cascades d'Ouzoud (110 m) depuis Marrakech : randonnées guidées en gorge, magots de Barbarie sauvages, bassins de baignade et arc-en-ciel naturel. Excursions d'une journée complète avec des guides locaux.",
  },
  {
    slug: "essaouira",
    name: "Essaouira",
    subtitle: "La cité fortifiée et venteuse de l'Atlantique",
    region: "Marrakech-Safi",
    lat: 31.5085,
    lng: -9.7595,
    heroImage: "https://images.unsplash.com/photo-1555686367-56d5186965d5?w=1400&q=85",
    about:
      "Essaouira est le grand pendant atlantique de Marrakech — blanchie à la chaux là où Marrakech est rouge rosé, balayée par les vents là où Marrakech est immobile, et profondément paisible là où Marrakech est électrique. Les fortifications portugaises du XVIIIe siècle de la ville s'avancent dans le ressac atlantique, enserrant une médina classée au patrimoine mondial de l'UNESCO, avec ses volets bleus en arceaux, ses réparations de filets de pêche et sa musique gnaoua flottant depuis les portes des cafés. Essaouira a longtemps attiré artistes, musiciens et écrivains — Jimi Hendrix y séjourna en 1969, inspirant toute une génération de voyageurs à lui emboîter le pas.",
    knownFor: [
      "Une médina classée UNESCO ceinte de remparts maritimes portugais du XVIIIe siècle",
      "Un kitesurf et un windsurf de renommée mondiale (vents atlantiques constants)",
      "La musique gnaoua — le blues spirituel de l'héritage africain du Maroc",
      "Une flotte de pêche bleue en activité et des fruits de mer frais",
      "La marqueterie en bois de thuya — l'artisanat emblématique d'Essaouira",
      "Les remparts de la Skala — une promenade bordée de canons au-dessus de l'Atlantique",
    ],
    highlights: [
      { title: "Les remparts", desc: "Les murailles maritimes d'Essaouira furent construites au XVIIIe siècle par un architecte français mandaté par le sultan alaouite. La Skala de la Ville, une large terrasse bordée de canons surplombant l'Atlantique, est l'une des promenades les plus spectaculaires du Maroc, surtout au coucher du soleil quand les bateaux de pêche rentrent au port." },
      { title: "La musique gnaoua", desc: "Essaouira est le foyer spirituel de la musique gnaoua — l'ancienne tradition musicale d'influence africaine du Maroc, enracinée dans la culture des communautés d'Afrique de l'Ouest amenées au Maroc comme esclaves. Le Festival Gnaoua et Musiques du Monde (juin) attire des musiciens de toute l'Afrique et au-delà." },
      { title: "Le paradis du kitesurf", desc: "Les vents alizés constants qui soufflent du nord-est durant tout l'été font d'Essaouira l'une des grandes destinations mondiales du kitesurf. La plage au sud de la ville est fréquentée toute l'année par surfeurs, kitesurfeurs et windsurfeurs." },
      { title: "La médina", desc: "Contrairement au labyrinthe de Marrakech, la médina d'Essaouira est organisée selon un plan en damier logique — plus facile à parcourir, mais tout aussi envoûtante. La Porte de la Marine, les souks d'épices et de bijoux, ainsi que la criée aux poissons du port comptent parmi ses temps forts." },
    ],
    seasons: [
      { name: "Printemps", emoji: "🌸", rating: 4, note: "D'avril à juin : chaud, vents modérés, longues soirées. Festival Gnaoua en juin." },
      { name: "Été", emoji: "☀️", rating: 5, note: "De juillet à août : alizés à pleine puissance — parfait pour le kitesurf. Frais pour les standards marocains (22-26°C)." },
      { name: "Automne", emoji: "🍂", rating: 4, note: "De septembre à novembre : températures agréables, bon surf, moins de touristes qu'en été." },
      { name: "Hiver", emoji: "❄️", rating: 3, note: "De décembre à mars : saison la plus venteuse et la plus fraîche. La ville est alors à son plus calme et à son plus authentique." },
    ],
    travelTips: [
      "Essaouira se trouve à 3 heures de Marrakech (170 km). Les excursions d'une journée sont possibles, mais une nuit sur place est bien préférable.",
      "Emportez une couche coupe-vent même en été — l'alizé constant peut rendre le front de mer frisquet.",
      "Les fruits de mer les plus frais se trouvent aux étals du port (à l'est de la porte principale) — choisissez votre poisson et faites-le griller sur place.",
      "La marqueterie en bois de thuya est la spécialité artisanale locale — recherchez les pièces authentiques faites à partir de la loupe de racine de thuya, et non des imitations teintées en pin.",
      "Marchez sur les remparts au coucher du soleil pour profiter de la meilleure lumière sur l'Atlantique et la flotte de pêche.",
    ],
    faqs: [
      { q: "Comment se rendre de Marrakech à Essaouira ?", a: "Les bus Supratours partent deux fois par jour de Marrakech (Bab Doukkala) et mettent 2h30 à 3 heures. Les taxis collectifs sont plus rapides mais plus bondés. Les voitures privées et transferts touristiques mettent 2h30 sur l'autoroute A7. Il n'existe pas de liaison ferroviaire." },
      { q: "Essaouira convient-elle aux non-surfeurs ?", a: "Absolument — Essaouira est l'une des destinations les plus complètes du Maroc pour les non-surfeurs. La médina, les remparts, la musique gnaoua, les fruits de mer, les ateliers d'artisans et les balades sur la plage offrent un programme complet sans aucun sport nautique." },
      { q: "Pourquoi Jimi Hendrix a-t-il visité Essaouira ?", a: "Hendrix visita Essaouira en 1969 lors de son long séjour au Maroc, attiré par la communauté artistique de la ville et les traditions musicales gnaoua. Il y resta plusieurs jours, et cette visite est depuis devenue un élément célèbre de la mythologie culturelle de la ville. Une maison où il aurait séjourné, près de la médina, est aujourd'hui un petit musée, bien que son exactitude historique soit contestée." },
    ],
    relatedCategories: ["day-tours", "cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guide de voyage à Essaouira — Kitesurf, musique gnaoua et médina | Marrakech Eco Tours",
    seoDescription: "Découvrez Essaouira : sa médina atlantique classée UNESCO, son kitesurf de renommée mondiale, sa musique gnaoua et ses fruits de mer. Excursions d'une journée et circuits de plusieurs jours au départ de Marrakech avec des guides locaux.",
  },
];

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}
