import type { Destination } from "./destinations";

export const DESTINATIONS: Destination[] = [
  {
    slug: "marrakech",
    name: "Marrakesch",
    subtitle: "Die Rote Stadt",
    region: "Marrakech-Safi",
    lat: 31.6295,
    lng: -7.9811,
    heroImage: "https://images.unsplash.com/photo-1708823081494-3e5bbd2ce931?w=1400&q=85",
    about:
      "Marrakesch ist die lebendigste Stadt Marokkos – ein tausend Jahre altes Labyrinth aus Souks, Palästen und Straßentheater, erbaut aus rosafarbenem Stein. Die Medina von Marrakesch ist UNESCO-Weltkulturerbe und eines der am dichtesten besiedelten Stadtgebiete der Welt, Heimat von über 90.000 Menschen auf einer Fläche von weniger als zwei Quadratkilometern. In ihrem Herzen liegt der Djemaa el-Fna, der außergewöhnlichste öffentliche Platz der Erde: tagsüber Gewürzmarkt und Saftstand, nachts ein Karneval aus Geschichtenerzählern, Akrobaten und Gnaoua-Musikern, der seit 900 Jahren jeden einzelnen Abend stattfindet.",
    knownFor: [
      "Djemaa el-Fna – das großartigste Freilufttheater der Welt",
      "14 spezialisierte Zunft-Souks in der historischen Medina",
      "Koutoubia-Moschee und die Saadier-Gräber",
      "Majorelle-Garten und das Museum für Berberkunst",
      "Versteckte Riads und traditionelle Hamam-Kultur",
      "Tor zum Hohen Atlas (eine Stunde entfernt)",
    ],
    highlights: [
      { title: "Die Medina", desc: "Eine UNESCO-gelistete ummauerte Stadt mit über 9.000 Gassen, von denen jede zu etwas Unerwartetem führt. Heimat der berühmtesten Souks, Gerbereien und Gewürzmärkte Marokkos." },
      { title: "Djemaa el-Fna", desc: "Der große Platz verwandelt sich zweimal täglich vollständig. Dieselben Familien betreiben seit Generationen dieselben Essensstände – gegrillte Merguez, Harira-Suppe und frisch gepresster Orangensaft." },
      { title: "Der Majorelle-Garten", desc: "In den 1920er Jahren vom französischen Maler Jacques Majorelle angelegt und später von Yves Saint Laurent restauriert, ist der Garten eine Oase aus Kobaltblau, Bambushainen und seltenen Kakteen." },
      { title: "Ausgangspunkt für Tagesausflüge", desc: "Marrakesch ist die ideale Basis für die gesamte Region: der Hohe Atlas und der Toubkal-Gipfel (1 Stunde), die Ouzoud-Wasserfälle (3 Stunden), die Sahara (10 Stunden mit dem Auto oder als Übernachtungstour) und Essaouira an der Atlantikküste (3 Stunden)." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "März bis Mai ist Hochsaison – warm, grün, Wildblumen im Atlas. Früh buchen." },
      { name: "Sommer", emoji: "☀️", rating: 2, note: "Juni bis August erreichen die Temperaturen in der Stadt über 40 °C. Für Stadtrundgänge nicht ideal." },
      { name: "Herbst", emoji: "🍂", rating: 5, note: "September bis November ist ausgezeichnet – angenehme Wärme, Erntezeit, weniger Andrang." },
      { name: "Winter", emoji: "❄️", rating: 3, note: "Dezember bis Februar ist mild und sonnig in der Stadt. Oberhalb von 2.000 m kann auf den Atlas-Pfaden Schnee liegen." },
    ],
    travelTips: [
      "Die Medina erkundet man am besten zu Fuß – engagieren Sie einen lokalen Guide, um die Viertel hinter den touristischen Hauptstraßen zu entdecken.",
      "Handeln Sie die Preise in den Souks aus – das erste Angebot ist selten der tatsächliche Preis.",
      "Tragen Sie leichte, atmungsaktive Kleidung. Zurückhaltende Kleidung (bedeckte Schultern und Knie) wird in der Medina und in Moscheen geschätzt.",
      "Führen Sie kleine Dirham-Münzen für Essensstände und Trinkgelder mit sich.",
      "Viele der schönsten Riads sind von außen unsichtbar – eine schlichte Tür in einer kahlen Wand.",
    ],
    faqs: [
      { q: "Wie komme ich vom Flughafen Marrakesch zur Medina?", a: "Ein Taxi vom Flughafen Menara zur Medina kostet etwa 100–150 MAD (9–13 €) und dauert 15–20 Minuten. Vereinbaren Sie den Preis vor dem Einsteigen. Manche Riads bieten einen Flughafentransfer an." },
      { q: "Ist Marrakesch sicher für Alleinreisende?", a: "Ja – Marrakesch ist grundsätzlich sicher und verfügt über eine gut ausgebaute touristische Infrastruktur. Häufige Probleme sind aufdringliche Anbieter in der Medina und Motorroller in den engen Gassen. Bleiben Sie in Menschenmengen aufmerksam und sichern Sie Ihre Wertsachen." },
      { q: "Welches ist die beste Gegend zum Übernachten in Marrakesch?", a: "Die Medina (Altstadt) hat die authentischste Atmosphäre. Die Viertel Kasbah und Mouassine bieten die ruhigsten Riads mit dem kürzesten Weg zu den wichtigsten Sehenswürdigkeiten. Gueliz (die Neustadt) ist westlicher geprägt und bietet einfacheres Parken." },
      { q: "Benötige ich ein Visum für Marokko?", a: "Bürger der EU, Großbritanniens, der USA, Kanadas, Australiens und der meisten westlichen Länder benötigen für Aufenthalte unter 90 Tagen kein Visum. Ihr Reisepass muss ab dem Einreisedatum noch mindestens 6 Monate gültig sein." },
      { q: "Welche Währung wird verwendet und kann ich mit Karte zahlen?", a: "Marokko verwendet den Dirham (MAD). Karten werden in den meisten Hotels und größeren Restaurants akzeptiert, aber Souks und kleinere Händler nehmen nur Bargeld. Geldautomaten sind in der Medina und in Gueliz weit verbreitet." },
    ],
    relatedCategories: ["cultural", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Marrakesch Reiseführer — Beste Touren, Tipps und Abenteuer | Marrakech Eco Tours",
    seoDescription: "Der komplette Marrakesch-Reiseführer: Medina-Spaziergänge, Souks, Djemaa el-Fna und Tagesausflüge in den Atlas und die Sahara. Buchen Sie Kleingruppentouren mit lokalen Berber-Guides.",
  },
  {
    slug: "high-atlas",
    name: "Hoher Atlas",
    subtitle: "Das Dach Nordafrikas",
    region: "Marrakech-Safi",
    lat: 31.0573,
    lng: -7.9149,
    heroImage: "https://images.unsplash.com/photo-1611859836043-a9177f500a27?w=1400&q=85",
    about:
      "Der Hohe Atlas ist eines der großen Gebirgsmassive Afrikas – ein 2.400 km langes Rückgrat aus vergletscherten Gipfeln, Berberdörfern und uralten Maultierpfaden, das sich vom Atlantik bis zur algerischen Grenze erstreckt. An seinem höchsten Punkt erhebt sich der Jbel Toubkal (4.167 m), das Dach Nordafrikas und der am leichtesten erreichbare 4.000er-Gipfel des Kontinents. Seit Jahrtausenden bewirtschaften Berbergemeinschaften die terrassierten Täler und durchqueren die hohen Pässe auf Routen, die sich seit den mittelalterlichen Karawanenzügen kaum verändert haben.",
    knownFor: [
      "Jbel Toubkal – mit 4.167 m der höchste Gipfel Nordafrikas",
      "Das Dorf Imlil – traditioneller Ausgangspunkt für den Toubkal-Aufstieg",
      "Berberische Bergdörfer mit jahrhundertealter Hochgebirgstradition",
      "Bergseen, Schluchten und Gletschertäler",
      "Die Überquerung des M'Goun-Massivs – die abgelegenste Trekkingroute Marokkos",
      "Spektakuläre Ausblicke von den Graten – bis nach Spanien" ,
    ],
    highlights: [
      { title: "Toubkal-Gipfel", desc: "Der viertägige Toubkal-Trek ist Marokkos ikonischste Bergherausforderung. Von Imlil auf 1.740 m führt der Aufstieg durch Berberdörfer, Berghütten und den Pass Tizi n'Ouanoums, bevor der letzte Anstieg zum Gipfel auf 4.167 m folgt." },
      { title: "Das Imlil-Tal", desc: "Das Ausgangsdorf für alle Trekkingtouren im Hohen Atlas. Umgeben von Walnusshainen und terrassierten Weizenfeldern, beherbergt Imlil eine Gemeinschaft von Bergführern, deren Familien seit Generationen auf diesen Pfaden arbeiten." },
      { title: "Berberdörfer", desc: "Der Atlas ist Heimat indigener Amazigh-Gemeinschaften (Berber), die ihre Sprache, Kultur und Architektur über Jahrhunderte hinweg bewahrt haben. Viele Dörfer haben keinen Straßenanschluss – nur Maultierpfade." },
      { title: "Das M'Goun-Massiv", desc: "Für erfahrene Trekker auf der Suche nach Einsamkeit führt die M'Goun-Überquerung (7–10 Tage) durch einige der spektakulärsten Schluchten- und Gratlandschaften Nordafrikas – nahezu ohne touristische Infrastruktur." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "April bis Juni: Wildblumen, zurückweichender Schnee auf den hohen Pässen, ideales Trekkingwetter." },
      { name: "Sommer", emoji: "☀️", rating: 4, note: "Juli bis August: Gipfelpfade schneefrei, heiß in den Tälern, aber kühl in der Höhe. Hochsaison." },
      { name: "Herbst", emoji: "🍂", rating: 5, note: "September bis Oktober: wohl die besten Bedingungen – stabiler Himmel, kräftige Farben, weniger Trekker." },
      { name: "Winter", emoji: "❄️", rating: 3, note: "November bis März: Der Toubkal-Gipfel erfordert Steigeisen und Eispickel. Wunderschön, aber anspruchsvoll." },
    ],
    travelTips: [
      "Akklimatisieren Sie sich mindestens einen Tag in Marrakesch (460 m), bevor Sie nach Imlil (1.740 m) hinaufsteigen.",
      "Der Toubkal erfordert gute Kondition, aber im Sommer keine technischen Klettertechniken. Im Winter ist er ein ernsthaftes alpinistisches Unterfangen.",
      "Engagieren Sie einen lizenzierten lokalen Berber-Guide – er kennt jeden Stein des Berges, und seine Begleitung ist im Toubkal-Nationalpark vorgeschrieben.",
      "Auf den meisten Atlas-Routen können Maultiere die Ausrüstung tragen – nutzen Sie das, um mit leichterem Gepäck zu reisen.",
      "Packen Sie auch im Sommer warme Schichten ein: Die Temperaturen an der Toubkal-Hütte können nachts unter null Grad fallen.",
    ],
    faqs: [
      { q: "Wie schwierig ist der Toubkal-Trek?", a: "Der Toubkal ist ein anspruchsvolles Trekkingziel (kein technisches Klettern), das eine gute Grundkondition erfordert. Sie sollten in der Lage sein, 6–8 Stunden täglich mit Tagesrucksack zu wandern. Im Sommer wird keine Spezialausrüstung benötigt. Im Winter sind Steigeisen und Eispickel unverzichtbar." },
      { q: "Wie lange dauert es, den Toubkal-Gipfel zu erreichen?", a: "Die Standardroute von Imlil zum Gipfel und zurück dauert 3–4 Tage. Tag 1: Imlil zur Hütte (4–5 Stunden). Tag 2: Gipfelversuch von der Hütte aus (3–4 Stunden Aufstieg, 2,5 Stunden Abstieg). Tag 3–4: Abstieg und optionale Besuche in Berberdörfern." },
      { q: "Ist ein Guide für den Toubkal-Trek vorgeschrieben?", a: "Ein lizenzierter Guide ist rechtlich nicht zwingend erforderlich, wird jedoch dringend empfohlen und von den meisten verantwortungsbewussten Anbietern verlangt. Das Gelände ist anspruchsvoll, das Wetter ändert sich schnell, und lokale Guides bieten Sicherheit, Routenkenntnis und wertvollen kulturellen Kontext." },
      { q: "Was ist die beste Basis für Trekkingtouren im Hohen Atlas?", a: "Das Dorf Imlil (1.740 m), 62 km von Marrakesch entfernt, ist der klassische Ausgangspunkt für den Toubkal. Azilal dient als Basis für Treks im M'Goun-Massiv. Beide erfordern einen Guide und angemessene Vorbereitung." },
    ],
    relatedCategories: ["trekking", "hiking"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Hoher Atlas Reiseführer — Toubkal-Trek und Berberdörfer | Marrakech Eco Tours",
    seoDescription: "Erkunden Sie den Hohen Atlas mit zertifizierten lokalen Guides: Toubkal-Gipfeltrek (4.167 m), Wanderungen zu Berberdörfern und mehrtägige Atlas-Überquerungen. Kleingruppen ab Marrakesch.",
  },
  {
    slug: "sahara",
    name: "Sahara-Wüste",
    subtitle: "Die goldenen Dünen von Erg Chebbi",
    region: "Drâa-Tafilalet",
    lat: 31.1513,
    lng: -3.9785,
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1400&q=85",
    about:
      "Erg Chebbi, nahe dem Dorf Merzouga, ist der spektakulärste Abschnitt saharischen Sandmeers in Marokko – ein 50 km² großes Feld aus Sterndünen, das sich bis zu 150 Meter über die flache Hamada (Kieswüste) erhebt. Die Dünen bestehen vollständig aus feinem, orangerotem Sand, den die vorherrschenden Nordwestwinde zu klassischen sichelförmigen Barchandünen geformt haben. Bei Sonnenuntergang und Sonnenaufgang verwandelt das Licht den Erg in eine Landschaft aus geschmolzenem Gold und Kupfer, die es so nirgendwo sonst auf der Erde gibt.",
    knownFor: [
      "Dünen von bis zu 150 m Höhe – zu den höchsten Marokkos zählend",
      "Kamelritte bei Sonnenuntergang ins Herz des Erg",
      "Authentische Nächte im berberischen Nomadencamp unter den Sternen",
      "Sternenbeobachtung der Milchstraße fernab jeglicher Lichtverschmutzung",
      "Das Dorf Merzouga – Tor zur Wüste",
      "Quad-Touren und 4×4-Wüstenausflüge",
    ],
    highlights: [
      { title: "Die Dünen des Erg Chebbi", desc: "Das Dünenfeld ist zur goldenen Stunde am eindrucksvollsten – kommen Sie zum Sonnenuntergang für das Lichtspiel, das den Sand in jede Nuance von Kupfer, Bernstein und Rosa taucht. Bei Sonnenaufgang kehren sich die Farben um: kühles Blau weicht warmem Gold, während die Sonne über den Dünenkamm steigt." },
      { title: "Kamelritte", desc: "Die traditionelle Durchquerung des Erg erfolgt auf dem Kamel – eine langsame, meditative Reise ins Herz der Wüste, die Sie mit Jahrtausenden alter Karawanenhandelsrouten verbindet. Unsere Berber-Guides führen dieselben Pfade wie ihre Vorfahren." },
      { title: "Nächte im Wüstencamp", desc: "In einem Berberzelt mitten im Erg zu übernachten, fernab jeder Straße oder Siedlung, ist eines der eindrucksvollsten Erlebnisse überhaupt. Die Stille ist absolut. Die Milchstraße an einem von Lichtverschmutzung unberührten Himmel ist außergewöhnlich." },
      { title: "Wüstenaktivitäten", desc: "Über den klassischen Kamelritt hinaus bieten der Erg und die umliegende Hamada Sandboarding an den Dünenhängen, Quad-Touren über die Kieswüste und 4×4-Ausflüge zu Wüstenoasen und Fossilienfundstellen." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "März bis Mai: ideale Temperaturen (20–28 °C), nach den Winterregen gelegentlich Wildblumen in der Hamada." },
      { name: "Sommer", emoji: "☀️", rating: 1, note: "Juni bis August: extreme Hitze (40–48 °C). Wüstenreisen im Hochsommer werden nicht empfohlen." },
      { name: "Herbst", emoji: "🍂", rating: 5, note: "September bis November: warme Tage, kühle Nächte – perfekte Bedingungen fürs Wüstencamping." },
      { name: "Winter", emoji: "❄️", rating: 4, note: "Dezember bis Februar: kalte Nächte (im Januar nahe dem Gefrierpunkt), aber atemberaubend klarer Himmel. Warme Kleidung fürs Camp mitbringen." },
    ],
    travelTips: [
      "Packen Sie warme Kleidung für Wüstennächte ein – die Temperaturen fallen nach Sonnenuntergang selbst im Frühling und Herbst drastisch.",
      "Bringen Sie eine Taschenlampe und zusätzliches Wasser für Kamelritte mit. Die Dünen können im Dunkeln desorientierend wirken.",
      "Sand gelangt überallhin. Verwenden Sie einen wasserdichten Beutel für die Kameraausrüstung und verschließen Sie Toilettenartikel gut.",
      "Sandboarding macht Spaß, ist aber körperlich anstrengend – der Aufstieg über 150 m hohe Dünen ist ermüdend.",
      "Der Sonnenaufgang über dem Erg ist ebenso spektakulär wie der Sonnenuntergang – stellen Sie den Wecker und besteigen Sie vor dem Morgengrauen den nächstgelegenen Dünenkamm.",
    ],
    faqs: [
      { q: "Wie weit ist Merzouga von Marrakesch entfernt?", a: "Merzouga liegt etwa 560 km von Marrakesch entfernt – rund 9–10 Autostunden. Die meisten Wüstentouren fahren auf dem Hinweg meist über die Dadès-Schlucht und das Tal der Tausend Kasbahs und kehren auf einer anderen südlichen Route zurück. Eine Hin- und Rückfahrt über Nacht ist bei preisgünstigen Touren ebenfalls möglich." },
      { q: "Reicht eine 3-tägige Sahara-Tour aus?", a: "3 Tage bieten das wesentliche Erlebnis: Fahrt durch den Atlas und das Kasbah-Land, eine volle Nacht im Wüstencamp und die Rückreise. Für ein umfassenderes Erlebnis ermöglichen 4–5 Tage die Erkundung des Rosental, der Todra-Schlucht und mehrerer Dünengebiete." },
      { q: "Was ist in einer Sahara-Camp-Nacht enthalten?", a: "Standard-Camp-Nächte umfassen ein traditionelles Berberzelt, Abendessen (Tajine und Couscous), Live-Musik am Lagerfeuer und Frühstück vor dem Kamelritt zum Sonnenaufgang. Luxuriösere Privatcamps verfügen über richtige Betten und eigenes Bad." },
      { q: "Kann ich die Sahara auf eigene Faust besuchen?", a: "Ja, aber das Erlebnis ist mit einem sachkundigen lokalen Guide deutlich reicher. Die Navigation in den Dünen ist nicht trivial, und lokale Guides bieten kulturellen Kontext, sprachlichen Zugang zu Berberfamilien und Logistik, deren eigenständige Organisation Tage in Anspruch nehmen würde." },
    ],
    relatedCategories: ["desert"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Sahara-Wüstentour ab Marrakesch — Erg Chebbi & Merzouga Reiseführer | Marrakech Eco Tours",
    seoDescription: "Entdecken Sie die Sahara mit zertifizierten Guides: Kamelritte, Nächte im Berbercamp und Sonnenaufgang über den 150 m hohen Dünen von Erg Chebbi. 2- bis 4-tägige Wüstentouren ab Marrakesch.",
  },
  {
    slug: "fes",
    name: "Fès el-Bali",
    subtitle: "Die lebendige mittelalterliche Stadt",
    region: "Fès-Meknès",
    lat: 34.0545,
    lng: -4.9815,
    heroImage: "https://images.unsplash.com/photo-1582742850838-24590fb39fdc?w=1400&q=85",
    about:
      "Fès el-Bali ist wohl das bemerkenswerteste urbane Überbleibsel der Erde – eine voll funktionsfähige mittelalterliche Stadt mit 156.000 Einwohnern auf 256 Hektar, die seit dem Jahr 789 n. Chr. ununterbrochen bewohnt ist. Sie ist das größte autofreie Stadtgebiet der Welt. Jede Straße ihres Labyrinths aus 9.400 Gassen transportiert Waren per Hand oder Maultier. Dieselben Handwerke werden seit tausend Jahren in denselben Werkstätten ausgeübt: Ledergerbung, Keramikglasur, Messingeinlegearbeiten, Zellij-Mosaike. Die Stadt wurde von Moulay Idriss I. gegründet und expandierte unter der Marinidendynastie zu jenem großen Sitz islamischer Gelehrsamkeit, der sie bis heute geblieben ist.",
    knownFor: [
      "Die größte autofreie Stadtzone der Welt – 9.400 Gassen",
      "Die Chouara-Gerberei – unverändert seit dem 11. Jahrhundert",
      "Die 859 gegründete Universität al-Qarawiyyin – die älteste der Welt",
      "Die Bou-Inania-Medresse und die Attarine-Medresse",
      "Das Mellah (jüdisches Viertel) und seine Dachterrassenblicke",
      "Lebendige Handwerkstradition: Zellij, Stickerei, Kupfer, Leder",
    ],
    highlights: [
      { title: "Die Chouara-Gerberei", desc: "Die meistfotografierte Sehenswürdigkeit Marokkos nach der Sahara. Steinkufen voller Farbstoffe (Safran, Mohn, Henna, Indigo), in denen Lederarbeiter kniehoch stehend Häute genau so verarbeiten wie vor 800 Jahren. Am besten von den Terrassen der Lederläden über den Gruben aus zu betrachten." },
      { title: "Moschee und Universität al-Qarawiyyin", desc: "859 von einer Frau, Fatima al-Fihri, gegründet, ist al-Qarawiyyin von der UNESCO als die weltweit älteste, ununterbrochen betriebene Universität anerkannt. Nichtmuslime dürfen die Moschee nicht betreten, doch der durch die geschnitzten Türportale sichtbare Innenhof zählt zu Marokkos großen architektonischen Sehenswürdigkeiten." },
      { title: "Das Medina-Labyrinth", desc: "Anders als die Medina von Marrakesch ist Fès wirklich labyrinthisch – selbst erfahrene Guides orientieren sich an Landmarken statt an einer gedanklichen Karte. Sich leicht zu verirren ist der beste Weg, das wahre Fès zu entdecken: winzige Bäckereien, Teppichweber, Nachbarschaftsmoscheen und kleine Plätze, auf denen alte Männer Karten spielen." },
      { title: "Das Mellah", desc: "Das jüdische Viertel des alten Fès, einst Heimat einer der bedeutendsten jüdischen Gemeinden Nordafrikas, birgt großartige Architektur der Mitte des 20. Jahrhunderts, eine restaurierte Synagoge und von seinen erhöhten Terrassen und dem Friedhof aus die besten Ausblicke der Stadt." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "März bis Mai: angenehme Temperaturen (18–26 °C), lange Abende, grüne Umgebung." },
      { name: "Sommer", emoji: "☀️", rating: 2, note: "Juni bis August: sehr heiß (35–40 °C). Die Medina wird drückend. Nur Vormittagsbesuche empfohlen." },
      { name: "Herbst", emoji: "🍂", rating: 5, note: "September bis November: perfektes Klima, Erntezeit, Festival der Heiligen Musik von Fès (November)." },
      { name: "Winter", emoji: "❄️", rating: 3, note: "Dezember bis Februar: kühl und gelegentlich regnerisch. Die Gerbereien sind weniger geschäftig und leichter zugänglich." },
    ],
    travelTips: [
      "Fès liegt 3–4 Autostunden von Marrakesch entfernt. Die meisten Touren zu den Kaiserstädten kombinieren Fès, Meknès und Volubilis über 3 oder mehr Tage.",
      "Ein lokaler Guide ist in der Medina unverzichtbar – Selbstnavigation führt zu Frustration. Sogar Einheimische verirren sich.",
      "Die Gerbereien sind morgens am farbenprächtigsten (das nachmittägliche Gerben findet später am Tag statt).",
      "Kaufen Sie Lederwaren direkt in den Gerbereiläden – die Qualität ist echt und die Herkunft nachvollziehbar.",
      "Probieren Sie die typischen Fassi-Gerichte: Pastilla (Taubenpastete mit Mandeln), Harira-Suppe und Bastilla au lait (Milchgebäck).",
    ],
    faqs: [
      { q: "Wie viele Tage brauche ich für Fès?", a: "Zwei volle Tage sind das Minimum, um die wichtigsten Sehenswürdigkeiten der Medina, die Gerbereien und die Ville Nouvelle abzudecken. Drei Tage erlauben die Erkundung des Mellah, des andalusischen Viertels, einen Tagesausflug zu den römischen Ruinen von Volubilis und ein entspanntes Erkunden der Medina." },
      { q: "Liegt Fès auf der Roadtrip-Route von Marrakesch nach Fès?", a: "Ja – Marrakesch nach Fès ist Marokkos klassische Überlandroute, die meist 3–6 Tage über die Dadès-Schlucht, die Todra-Schlucht, die Merzouga-Sahara und die Zedernwälder des Mittleren Atlas führt. Dies ist einer der großen Roadtrips Nordafrikas." },
      { q: "Sollte ich in der Medina oder in der Ville Nouvelle übernachten?", a: "Übernachten Sie in der Medina. Das Riad-Erlebnis ist zentral für das Verständnis von Fès – durch eine schlichte Außenmauer zu treten und einen verzierten Innenhof mit Brunnen zu entdecken, ist einer der stimmungsvollsten Momente Marokkos. Die Ville Nouvelle hat keinen historischen Charakter." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Fès el-Bali Reiseführer — Medina-Touren, Gerbereien und Kaiserstadt | Marrakech Eco Tours",
    seoDescription: "Erkunden Sie Fès el-Bali, die am besten erhaltene mittelalterliche Stadt der Welt. Geführte Touren zur Chouara-Gerberei, zur Universität al-Qarawiyyin und durch die Medina mit 9.400 Gassen. Tagesausflüge und mehrtägige Touren ab Marrakesch.",
  },
  {
    slug: "chefchaouen",
    name: "Chefchaouen",
    subtitle: "Die Blaue Perle Marokkos",
    region: "Tanger-Tétouan-Al Hoceïma",
    lat: 35.1688,
    lng: -5.2689,
    heroImage: "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1400&q=85",
    about:
      "Chefchaouen liegt auf 600 m Höhe an den Hängen des Rif-Gebirges – eine kleine, bemerkenswert gut erhaltene Medina, deren Mauern, Treppen und Blumentöpfe durchgehend in Blau und Weiß getüncht sind. Die Tradition des Blaufärbens, eingeführt von jüdischen Flüchtlingen der spanischen Reconquista in den 1930er Jahren, ist so zentral für die Identität der Stadt geworden, dass die Bewohner ihre Häuser jeden Frühling neu streichen. Der Effekt ist völlig anders als alles andere in Marokko: heiter, fotogen und wirklich entschleunigt.",
    knownFor: [
      "Eine vollständig in Blau und Weiß getünchte Medina",
      "Lage im Rif-Gebirge mit dramatischen Schluchtblicken",
      "Der Fluss Ras el-Ma, sein Wasserfall und die Waschsteine",
      "Die Plaza Uta el-Hammam – der von Cafés gesäumte Hauptplatz",
      "Handwerkliche Wollweberei und traditionelles Rif-Handwerk",
      "Tor zum Talassemtane-Nationalpark",
    ],
    highlights: [
      { title: "Die blaue Medina", desc: "Jede Wand, jede Stufe, jeder Türrahmen ist in Farbtönen von zartem Himmelblau bis tiefem Indigo gestrichen. Die Medina ist klein genug, um sie an einem Tag vollständig zu erkunden, aber lohnend genug, um drei Tage zu bleiben. Jede Ecke ist ein Fotomotiv." },
      { title: "Ras el-Ma", desc: "Ein kurzer Spaziergang von der Medina entfernt entspringt die Quelle Ras el-Ma dem Berg und speist einen kleinen Fluss, in dem Einheimische auf traditionelle Weise Wäsche waschen. Eine friedliche Auszeit vom touristischeren zentralen Platz." },
      { title: "Talassemtane-Nationalpark", desc: "Der Park beginnt am Rand der Medina und bietet halbtägige Wanderungen durch Zedern- und Eichenwälder, Schluchtenwanderungen über dem Fluss Laou sowie Ausblicke zurück auf die blau getünchte Stadt darunter." },
      { title: "Die Spanische Moschee", desc: "Ein 20-minütiger Aufstieg von der Medina (oder über einen felsigen Pfad erreichbar) führt zu einer von den Spaniern erbauten Moschee mit Panoramablick über die gesamte blaue Stadt und die umliegenden Rif-Täler – am schönsten bei Sonnenuntergang." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "April bis Juni: milde Temperaturen, grüne Hügel, Wildblumen an den Rif-Hängen. Hochsaison." },
      { name: "Sommer", emoji: "☀️", rating: 4, note: "Juli bis August: warm, aber auf dieser Höhe erträglich. Die Abende sind kühl. Sehr geschäftig – im Voraus buchen." },
      { name: "Herbst", emoji: "🍂", rating: 4, note: "September bis November: angenehme Temperaturen, ruhiger als der Sommer." },
      { name: "Winter", emoji: "❄️", rating: 2, note: "Dezember bis März: kann kalt und regnerisch sein. Gelegentlich Schnee auf den Rif-Graten. Sehr ruhig." },
    ],
    travelTips: [
      "Chefchaouen eignet sich am besten für eine Übernachtung, nicht für einen Tagesausflug – die Stadt ist am magischsten früh morgens, bevor die Reisebusse eintreffen.",
      "Die blauen Gassen wirken am eindrucksvollsten im frühen Morgenlicht (vor 9 Uhr) und im goldenen Licht des späten Nachmittags.",
      "Ausgezeichnete Basis für Wanderungen im Rif-Gebirge. Fragen Sie in Ihrem Riad nach lokalen Wanderführern.",
      "Die Medina ist klein – sich absichtlich 'zu verirren' führt zu den interessantesten Gassen und Handwerkswerkstätten.",
      "Kaufen Sie lokal ein: Wolldecken, Djellabas und Lederwaren sind Rif-Tradition und von ausgezeichneter Qualität.",
    ],
    faqs: [
      { q: "Wie komme ich von Marrakesch nach Chefchaouen?", a: "Es gibt keine direkte Route – Chefchaouen liegt 530 km von Marrakesch entfernt, etwa 6–7 Autostunden oder mit dem Bus. Die meisten Besucher reisen über Fès oder Tanger. Am praktischsten ist eine mehrtägige Kaiserstädte-Tour, die Fès, Chefchaouen, Meknès und die Rückkehr nach Marrakesch einschließt." },
      { q: "Warum ist Chefchaouen blau gestrichen?", a: "Die Tradition des Blaufärbens wurde in den 1930er Jahren von jüdischen Flüchtlingen eingeführt, die vor der spanischen Reconquista flohen. Blau symbolisiert in der jüdischen Tradition den Himmel. Mit der Zeit übernahm die gesamte Medina diese Praxis als Teil ihrer Identität, und Einheimische streichen ihre Häuser jeden Frühling neu." },
      { q: "Lohnt sich der Ausflug nach Chefchaouen von Marrakesch aus?", a: "Ja – aber es erfordert mindestens eine Übernachtung, um sie richtig zu würdigen. Ein Tagesausflug (nur von Fès oder Tanger aus möglich, 1,5–2 Stunden entfernt) lässt zu wenig Zeit. Eine Übernachtung ermöglicht es, die Medina in ihrer ruhigsten und schönsten Form zu erleben." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Chefchaouen Reiseführer — Die Blaue Stadt Marokkos | Marrakech Eco Tours",
    seoDescription: "Entdecken Sie Chefchaouen, Marokkos berühmte blaue Stadt im Rif-Gebirge. Geführte Touren, Wanderungen im Talassemtane-Nationalpark und Übernachtungen in der bemalten Medina.",
  },
  {
    slug: "agadir",
    name: "Agadir",
    subtitle: "Atlantikküste und Surf-Hauptstadt",
    region: "Souss-Massa",
    lat: 30.4278,
    lng: -9.5981,
    heroImage: "https://images.unsplash.com/photo-1562874732-260714dfe537?w=1400&q=85",
    about:
      "Agadir ist Marokkos wichtigste Badestadt – ein moderner Atlantikhafen, der nach einem verheerenden Erdbeben im Jahr 1960 vollständig wiederaufgebaut wurde. Am Fuß des Anti-Atlas-Gebirges gelegen, mit einem neun Kilometer langen, geschwungenen Weißsandstrand, dient Agadir sowohl Pauschaltouristen als auch Abenteurern als südliches Tor zu Marokko. Dreißig Minuten nördlich liegt Taghazout, ein Dorf, das sich zu einem der berühmtesten Surfziele der Welt entwickelt hat. Die Region Souss-Massa rund um Agadir beherbergt Nationalparks, Arganölwälder, von Flamingos bevölkerte Feuchtgebiete und Berbergemeinschaften, die eine jahrhundertealte Lebensweise bewahren.",
    knownFor: [
      "9 km Atlantikstrand – Marokkos längster Stadtstrand",
      "Taghazout – Weltklasse-Surfen (Anchor Point, Hash Point, Killer Point)",
      "Der Nationalpark Souss-Massa (Flamingos, Waldrapp, Gazellen)",
      "Paradise Valley – Palmenoase, türkisfarbene Becken und Naturschwimmen",
      "Arganöl-Kooperativen – der Souss ist der weltweit einzige Arganwald",
      "Frische Meeresfrüchte im aktiven Fischereihafen von Agadir",
    ],
    highlights: [
      { title: "Surfen in Taghazout", desc: "Das Dorf Taghazout (30 Minuten nördlich von Agadir) bietet Riffbrandungen von Weltklasse für alle Erfahrungsstufen. Anchor Point erzeugt Marokkos längste Wellenritte. Die Surfsaison läuft das ganze Jahr über, mit der größten Dünung von Oktober bis März." },
      { title: "Nationalpark Souss-Massa", desc: "Ein 45 Minuten südlich von Agadir gelegenes Küstenfeuchtgebiet, Heimat einer der letzten wilden Kolonien des Waldrapps weltweit, großer Flamingoschwärme und der bedrohten Dorkasgazelle. Ein außergewöhnliches und oft übersehenes Naturjuwel." },
      { title: "Paradise Valley", desc: "Eine versteckte Oase 30 km landeinwärts von Agadir – eine schmale, palmengesäumte Schlucht mit einer Reihe natürlicher türkisfarbener Badebecken. Nach einem kurzen Abstieg von der Straße erreichbar, ist es der perfekte Halbtagesausflug abseits des Strandes." },
      { title: "Arganland", desc: "Die Souss-Ebene zwischen Agadir und Taroudant ist der einzige Ort der Welt, an dem Arganbäume wild wachsen. Frauenkooperativen ernten und pressen das Öl von Hand. Der Besuch einer solchen Kooperative ist ein authentisches und bedeutsames touristisches Erlebnis." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "März bis Mai: warm, sonnig, ideal für Strand und Surfen. Das Atlantikwasser ist noch frisch, aber gut zum Schwimmen." },
      { name: "Sommer", emoji: "☀️", rating: 4, note: "Juni bis August: verlässlich warm. Die Passatwinde vom Atlantik halten die Temperaturen niedriger als im marokkanischen Landesinneren." },
      { name: "Herbst", emoji: "🍂", rating: 5, note: "September bis November: Beginn der besten Surfsaison. Warmes Meer, gleichmäßige Dünung." },
      { name: "Winter", emoji: "❄️", rating: 4, note: "Dezember bis Februar: nach marokkanischen Maßstäben mild (15–20 °C). Die größte Dünung des Jahres. Weniger überlaufener Strand." },
    ],
    travelTips: [
      "Agadir liegt auf dem Landweg 3 Stunden südlich von Marrakesch (256 km) oder 40 Flugminuten mit einem Direktflug entfernt.",
      "Die Strandpromenade eignet sich hervorragend zum Radfahren – mehrere Verleihe sind entlang der Uferstraße zu finden.",
      "Surfkurse für Anfänger werden in Taghazout ganzjährig angeboten. Buchen Sie direkt über das Surfcamp, nicht über Touristenschalter.",
      "Die Souks von Inezgane (10 km südlich von Agadir) sind eine authentischere und weniger touristische Alternative zum Stadtsouk von Agadir.",
      "Der wiederhergestellte Kasbah-Hügel von Agadir wurde beim Erdbeben von 1960 vollständig zerstört – nur die Mauern sind erhalten, doch der Blick über die Bucht lohnt den Aufstieg.",
    ],
    faqs: [
      { q: "Ist Agadir eine gute Basis zur Erkundung Südmarokkos?", a: "Ja – Agadir liegt ideal für Tagesausflüge zum Paradise Valley, nach Immouzer du Kandar, Taroudant (das 'kleine Marrakesch'), zum Silberschmucksouk von Tiznit und in die Anti-Atlas-Berge. Auch mehrtägige Ausflüge in die Sahara sind von Agadir aus möglich (560 km bis Merzouga)." },
      { q: "Wie ist die Surfsaison in Taghazout?", a: "Taghazout bietet das ganze Jahr über surfbare Wellen. Die größte und kraftvollste Dünung kommt von Oktober bis März. April bis September ist sanfter und eher für Anfänger und fortgeschrittene Anfänger geeignet. Die Wassertemperatur reicht von 16 °C im Winter bis 22 °C im Sommer." },
      { q: "Kann ich Agadir und Marrakesch in einer Reise verbinden?", a: "Auf jeden Fall – das ist der Standardansatz vieler unserer Touren. Fliegen Sie nach Marrakesch, reisen Sie auf dem Landweg nach Agadir (vorbei an den Atlas-Ausläufern und dem Arganland) und kehren Sie für Ihren Rückflug nach Marrakesch zurück. Oder umgekehrt. Die Route über den Gebirgspass Tizi n'Test ist spektakulär." },
    ],
    relatedCategories: ["day-tours", "hiking"],
    relatedOrigins: ["agadir"],
    seoTitle: "Agadir Reiseführer — Atlantikstrand, Surfen und Tagesausflüge | Marrakech Eco Tours",
    seoDescription: "Der komplette Agadir-Reiseführer: Surfen in Taghazout, Nationalpark Souss-Massa, Paradise Valley und Tagesausflüge von Marokkos Atlantikküste. Kleingruppentouren mit lokalen Guides.",
  },
  {
    slug: "ouzoud",
    name: "Ouzoud-Wasserfälle",
    subtitle: "Marokkos spektakulärstes Naturwunder",
    region: "Béni Mellal-Khénifra",
    lat: 32.0187,
    lng: -6.7188,
    heroImage: "https://images.unsplash.com/photo-1535027341838-aa4d6ab54a25?w=1400&q=85",
    about:
      "Die Cascades d'Ouzoud sind der spektakulärste Wasserfall Nordafrikas – eine dreifache Kaskade, die 110 Meter über rötliche Klippen in ein türkisfarbenes Becken stürzt, gespeist vom Fluss El-Abid. Der Name 'Ouzoud' bedeutet auf Tamazight (Berberisch) 'Olivenmahlen' – ein Verweis auf die traditionellen Olivenmühlen, die hier seit Generationen in Betrieb sind. Der Ort liegt in einer tiefen Schlucht, umgeben von Oliven- und Feigenhainen, und ist Heimat einer Kolonie wilder Berberaffen – die einzigen wilden Primaten Afrikas außerhalb Subsahara-Afrikas.",
    knownFor: [
      "110 m hoher dreifacher Wasserfall – der spektakulärste Marokkos",
      "Kolonie wilder Berberaffen (Nordafrikas einziger wilder Primat)",
      "Türkisfarbenes natürliches Schwimmbecken am Fuß der Fälle",
      "Regenbogennebel, mittags bei hochstehender Sonne sichtbar",
      "Traditionelle berberische Olivenölmühlen in der Schlucht",
      "Dramatische Schluchtenwanderung entlang des Flusses El-Abid",
    ],
    highlights: [
      { title: "Die Fälle", desc: "Drei parallele Wasserläufe treffen an einer Reihe felsiger Simse zusammen, bevor der Hauptfall folgt. Das Wasservolumen ist nach den Winterregen (Januar–März) am höchsten, doch die Fälle fließen das ganze Jahr über. Mittags im Frühling und Sommer bildet sich im Nebel ein dauerhafter Regenbogen – eines der schönsten Naturphänomene Marokkos." },
      { title: "Berberaffen", desc: "Die Kolonie wilder Berberaffen (Macaca sylvanus) bei Ouzoud gehört zu den am leichtesten zugänglichen Primatenpopulationen der Welt. Die Affen sind an menschliche Präsenz gewöhnt, bleiben aber wild – füttern Sie sie nicht und sichern Sie Ihr Essen. Sie stehen unter marokkanischem Gesetzesschutz." },
      { title: "Die Schluchtenwanderung", desc: "Ein Pfad führt vom oberen Ende der Fälle entlang der Kaskaden hinunter, überquert den Fluss am Basisbecken und führt weiter durch die Schlucht. Die vollständige Runde (3–4 Stunden) führt an traditionellen Olivenmühlen, Badestellen und Aussichtspunkten mit Blick zurück auf die Fälle von unten vorbei." },
      { title: "Olivenmühlen", desc: "Berberfamilien betreiben seit Jahrhunderten Steinmühlen-Olivenpressen in der Schlucht unterhalb der Fälle. In der Olivenerntesaison (November–Januar) können Sie beobachten, wie traditionelles Kaltpressen genau so durchgeführt wird wie seit Generationen." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 5, note: "März bis Mai: höchster Wasserfluss, dauerhafter Regenbogen, Wildblumen. Die beste Reisezeit." },
      { name: "Sommer", emoji: "☀️", rating: 4, note: "Juni bis August: heiß (35 °C+), aber das Schwimmbecken erfrischt. An Wochenenden sehr belebt." },
      { name: "Herbst", emoji: "🍂", rating: 4, note: "September bis November: Olivenerntesaison, guter Wasserfluss, angenehme Temperaturen." },
      { name: "Winter", emoji: "❄️", rating: 3, note: "Dezember bis Februar: höchste Niederschlagsmenge, Fälle mit maximaler Kraft, aber kühl und gelegentlich schlammig." },
    ],
    travelTips: [
      "Ouzoud liegt 3 Stunden von Marrakesch entfernt (150 km). Die meisten Besucher verbinden dies mit einer Tageswanderung und kehren am selben Abend zurück.",
      "Kommen Sie früh an (vor 9 Uhr), um die Fälle und das Basisbecken weitgehend für sich zu haben.",
      "Der Abstiegspfad zur Basis kann rutschig sein – tragen Sie griffiges Schuhwerk, keine Sandalen.",
      "Bringen Sie Wechselkleidung mit – Nebel und Baden machen Nasswerden unvermeidlich.",
      "Füttern Sie die Affen nicht – das stört ihr natürliches Verhalten und gewöhnt sie an menschliche Nahrung.",
    ],
    faqs: [
      { q: "Wie weit sind die Ouzoud-Wasserfälle von Marrakesch entfernt?", a: "Ouzoud liegt etwa 150 km von Marrakesch entfernt – rund 3 Autostunden. Die Fahrt führt durch Azilal und das Béni-Mellal-Plateau. Wir bieten geführte Tagesausflüge ab Marrakesch inklusive Transport, Guide und Schluchtenwanderung an." },
      { q: "Kann ich am Fuß der Wasserfälle schwimmen?", a: "Ja – das natürliche Becken am Fuß der Fälle ist einer der schönsten Badeorte Marokkos. Das Wasser ist kalt (aus Bergquellen gespeist), aber erfrischend, besonders im Sommer." },
      { q: "Ist Ouzoud ein guter Tagesausflug von Marrakesch aus?", a: "Ja – es ist der beliebteste Tagesausflug ab Marrakesch. Ein voller Tag (7–19 Uhr) erlaubt 4–5 Stunden an den Fällen und in der Schlucht. Eine Übernachtung im Dorf ermöglicht einen morgendlichen Besuch, bevor die Tagesausflügler eintreffen – die beste Art, den Ort zu erleben." },
    ],
    relatedCategories: ["hiking", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Tagesausflug zu den Ouzoud-Wasserfällen ab Marrakesch — Reiseführer & Touren | Marrakech Eco Tours",
    seoDescription: "Besuchen Sie die Ouzoud-Wasserfälle (110 m) ab Marrakesch: geführte Schluchtenwanderungen, wilde Berberaffen, Schwimmbecken und natürlicher Regenbogennebel. Ganztagestouren mit lokalen Guides.",
  },
  {
    slug: "essaouira",
    name: "Essaouira",
    subtitle: "Die windige, ummauerte Atlantikstadt",
    region: "Marrakech-Safi",
    lat: 31.5085,
    lng: -9.7595,
    heroImage: "https://images.unsplash.com/photo-1555686367-56d5186965d5?w=1400&q=85",
    about:
      "Essaouira ist der große atlantische Gegenpol zu Marrakesch – weiß getüncht, wo Marrakesch rosarot ist, windumtost, wo Marrakesch still ist, und tiefenentspannt, wo Marrakesch elektrisierend ist. Die im 18. Jahrhundert von den Portugiesen errichteten Befestigungsanlagen der Stadt ragen in die Atlantikbrandung hinein und umschließen eine UNESCO-Welterbe-Medina mit blauen Bogenläden, Fischernetzreparaturen und Gnaoua-Musik, die aus Caféeingängen weht. Essaouira zog seit jeher Künstler, Musiker und Schriftsteller an – Jimi Hendrix besuchte die Stadt 1969 und inspirierte damit eine ganze Reisendengeneration, es ihm gleichzutun.",
    knownFor: [
      "UNESCO-gelistete Medina mit portugiesischen Seemauern aus dem 18. Jahrhundert",
      "Weltklasse-Kitesurfen und Windsurfen (beständige Atlantikwinde)",
      "Gnaoua-Musik – der spirituelle Blues von Marokkos afrikanischem Erbe",
      "Aktive blaue Fischereiflotte und frische Meeresfrüchte",
      "Thuya-Holz-Intarsienkunst – Essaouiras charakteristisches Kunsthandwerk",
      "Die Festungsmauern der Skala – ein kanonengesäumter Spaziergang über dem Atlantik",
    ],
    highlights: [
      { title: "Die Festungsmauern", desc: "Essaouiras Seemauern wurden im 18. Jahrhundert von einem französischen Architekten im Auftrag des alawitischen Sultans erbaut. Die Skala de la Ville, eine breite, kanonengesäumte Terrasse mit Blick auf den Atlantik, ist einer der eindrucksvollsten Spaziergänge Marokkos, besonders bei Sonnenuntergang, wenn die Fischerboote einlaufen." },
      { title: "Gnaoua-Musik", desc: "Essaouira ist die spirituelle Heimat der Gnaoua – Marokkos uralter, afrikanisch geprägter Musiktradition, verwurzelt in der Kultur westafrikanischer Gemeinschaften, die als Versklavte nach Marokko gebracht wurden. Das Gnaoua World Music Festival (Juni) zieht Musiker aus ganz Afrika und darüber hinaus an." },
      { title: "Kitesurf-Paradies", desc: "Die beständigen Alizé-Passatwinde, die während der Sommermonate aus Nordosten wehen, machen Essaouira zu einem der weltweit großartigsten Kitesurf-Ziele. Der Strand südlich der Stadt wird ganzjährig von Surfern, Kitern und Windsurfern genutzt." },
      { title: "Die Medina", desc: "Anders als das labyrinthische Marrakesch ist Essaouiras Medina logisch als Raster angelegt – leichter zu navigieren, aber ebenso stimmungsvoll. Die Porte de la Marine, die Gewürz- und Schmucksouks sowie die Fischauktion im Hafen zählen zu ihren Höhepunkten." },
    ],
    seasons: [
      { name: "Frühling", emoji: "🌸", rating: 4, note: "April bis Juni: warm, mäßige Winde, lange Abende. Gnaoua-Festival im Juni." },
      { name: "Sommer", emoji: "☀️", rating: 5, note: "Juli bis August: Passatwinde in voller Stärke – perfekt zum Kitesurfen. Nach marokkanischen Maßstäben kühl (22–26 °C)." },
      { name: "Herbst", emoji: "🍂", rating: 4, note: "September bis November: angenehme Temperaturen, guter Wellengang, weniger Touristen als im Sommer." },
      { name: "Winter", emoji: "❄️", rating: 3, note: "Dezember bis März: windigste und kühlste Saison. Die Stadt ist dann am ruhigsten und stimmungsvollsten." },
    ],
    travelTips: [
      "Essaouira liegt 3 Stunden von Marrakesch entfernt (170 km). Tagesausflüge sind möglich, aber eine Übernachtung ist deutlich lohnender.",
      "Packen Sie auch im Sommer eine winddichte Schicht ein – der konstante Alizé-Wind kann die Strandpromenade frisch werden lassen.",
      "Die frischesten Meeresfrüchte gibt es an den Fischständen des Hafens (östlich des Haupttors) – wählen Sie Ihren Fisch und lassen Sie ihn sofort grillen.",
      "Thuya-Holz-Intarsienkunst ist die lokale Handwerksspezialität – achten Sie auf echte Stücke aus der Wurzelmaserung des Lebensbaums, nicht auf kiefernholzgebeizte Imitate.",
      "Spazieren Sie bei Sonnenuntergang über die Festungsmauern für das schönste Licht über dem Atlantik und der Fischereiflotte.",
    ],
    faqs: [
      { q: "Wie komme ich von Marrakesch nach Essaouira?", a: "Supratours-Busse fahren zweimal täglich ab Marrakesch (Bab Doukkala) und benötigen 2,5–3 Stunden. Sammeltaxis sind schneller, aber voller. Privatwagen und Tourtransfers benötigen 2,5 Stunden auf der Autobahn A7. Es gibt keine Zugverbindung." },
      { q: "Ist Essaouira auch für Nicht-Surfer geeignet?", a: "Auf jeden Fall – Essaouira ist eines der abwechslungsreichsten Reiseziele Marokkos für Nicht-Surfer. Die Medina, die Festungsmauern, Gnaoua-Musik, Meeresfrüchte, Kunsthandwerksstätten und Strandspaziergänge bieten ein vollständiges Programm ganz ohne Wassersport." },
      { q: "Warum besuchte Jimi Hendrix Essaouira?", a: "Hendrix besuchte Essaouira 1969 während seines längeren Aufenthalts in Marokko, angezogen von der Künstlergemeinschaft der Stadt und den Gnaoua-Musiktraditionen. Er blieb mehrere Tage, und der Besuch ist seither zu einem gefeierten Teil der kulturellen Mythologie der Stadt geworden. Ein Haus, in dem er angeblich in der Nähe der Medina wohnte, ist heute ein kleines Museum, wenngleich dessen historische Genauigkeit umstritten ist." },
    ],
    relatedCategories: ["day-tours", "cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Essaouira Reiseführer — Kitesurfen, Gnaoua-Musik und Medina | Marrakech Eco Tours",
    seoDescription: "Entdecken Sie Essaouira: UNESCO-gelistete Atlantik-Medina, Weltklasse-Kitesurfen, Gnaoua-Musik und Meeresfrüchte. Tagesausflüge und Übernachtungstouren ab Marrakesch mit lokalen Guides.",
  },
];

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}
