import type { Destination } from "./destinations";

export const DESTINATIONS: Destination[] = [
  {
    slug: "marrakech",
    name: "Marrakech",
    subtitle: "La Ciudad Roja",
    region: "Marrakech-Safi",
    lat: 31.6295,
    lng: -7.9811,
    heroImage: "https://images.unsplash.com/photo-1708823081494-3e5bbd2ce931?w=1400&q=85",
    about:
      "Marrakech es la ciudad más vibrante de Marruecos: un laberinto milenario de zocos, palacios y teatro callejero construido en piedra de color rosado. La medina de Marrakech es Patrimonio de la Humanidad por la UNESCO y una de las zonas urbanas más densamente pobladas del mundo, con más de 90.000 habitantes en un espacio de menos de dos kilómetros cuadrados. En su corazón se encuentra la plaza Jemaa el-Fna, la plaza pública más extraordinaria del planeta: de día, mercado de especias y puestos de zumos; de noche, un carnaval de cuentacuentos, acróbatas y músicos gnawa que lleva funcionando cada noche desde hace 900 años.",
    knownFor: [
      "Jemaa el-Fna, el mayor teatro al aire libre del mundo",
      "14 zocos gremiales de artesanos dentro de la medina antigua",
      "La mezquita Koutoubia y las Tumbas Saadíes",
      "El Jardín Majorelle y el Museo de Artes Bereberes",
      "Riads escondidos y la tradición del hammam",
      "Puerta de entrada a las Montañas del Atlas (a una hora de distancia)",
    ],
    highlights: [
      { title: "La Medina", desc: "Una ciudad amurallada declarada Patrimonio de la Humanidad con más de 9.000 callejones, cada uno conduciendo a algo inesperado. Alberga los zocos, curtidurías y mercados de especias más famosos de Marruecos." },
      { title: "Jemaa el-Fna", desc: "La gran plaza se transforma por completo dos veces al día. Las mismas familias llevan generaciones regentando los mismos puestos de comida: merguez a la parrilla, sopa harira y zumo de naranja recién exprimido." },
      { title: "El Jardín Majorelle", desc: "Diseñado por el pintor francés Jacques Majorelle en los años 20 y restaurado más tarde por Yves Saint Laurent, el jardín es un oasis de azul cobalto, bosquecillos de bambú y cactus poco comunes." },
      { title: "Centro de excursiones", desc: "Marrakech es la base ideal para explorar toda la región: el Alto Atlas y la cima del Toubkal (1 hora), las cascadas de Ouzoud (3 horas), el Sáhara (10 horas en coche o en excursión nocturna) y Essaouira, en la costa atlántica (3 horas)." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De marzo a mayo es temporada alta: cálido, verde, con flores silvestres en el Atlas. Reserva con antelación." },
      { name: "Verano", emoji: "☀️", rating: 2, note: "De junio a agosto las temperaturas superan los 40 °C en la ciudad. No es ideal para recorridos a pie." },
      { name: "Otoño", emoji: "🍂", rating: 5, note: "De septiembre a noviembre es excelente: calor agradable, temporada de cosecha, menos aglomeraciones." },
      { name: "Invierno", emoji: "❄️", rating: 3, note: "De diciembre a febrero hace suave y soleado en la ciudad. Los senderos del Atlas pueden tener nieve por encima de los 2.000 m." },
    ],
    travelTips: [
      "La medina se recorre mejor a pie: contrata a un guía local para descubrir los barrios más allá de las calles turísticas principales.",
      "Negocia los precios en los zocos: la primera oferta rara vez es el precio real.",
      "Usa ropa ligera y transpirable. Un vestuario recatado (hombros y rodillas cubiertos) se aprecia en la medina y las mezquitas.",
      "Lleva monedas de dirham de baja denominación para los puestos de comida y las propinas.",
      "Muchos de los mejores riads son invisibles desde fuera: una puerta sencilla en un muro liso.",
    ],
    faqs: [
      { q: "¿Cómo llego del aeropuerto de Marrakech a la medina?", a: "Un taxi desde el aeropuerto de la Menara hasta la medina cuesta entre 100 y 150 MAD (9-13 €) y tarda entre 15 y 20 minutos. Acuerda el precio antes de subir. Algunos riads ofrecen recogida en el aeropuerto." },
      { q: "¿Es Marrakech segura para viajar en solitario?", a: "Sí. Marrakech es, por lo general, segura y cuenta con una sólida infraestructura turística. Los problemas más comunes son vendedores insistentes en la medina y motocicletas en las calles estrechas. Mantente atento entre la multitud y guarda bien tus objetos de valor." },
      { q: "¿Cuál es la mejor zona para alojarse en Marrakech?", a: "La medina (casco antiguo) es la más pintoresca. Los barrios de la Kasbah y Mouassine ofrecen los riads más tranquilos, con los trayectos más cortos hasta los principales lugares de interés. Gueliz (la ciudad nueva) es más occidentalizada y facilita el aparcamiento." },
      { q: "¿Necesito visado para Marruecos?", a: "Los ciudadanos de la UE, Reino Unido, EE. UU., Canadá, Australia y la mayoría de países occidentales no necesitan visado para estancias inferiores a 90 días. Tu pasaporte debe tener una validez mínima de 6 meses desde la fecha de entrada." },
      { q: "¿Qué moneda se utiliza y puedo pagar con tarjeta?", a: "Marruecos utiliza el dirham (MAD). Las tarjetas se aceptan en la mayoría de hoteles y restaurantes grandes, pero los zocos y comerciantes pequeños solo aceptan efectivo. Hay cajeros automáticos ampliamente disponibles en la medina y en Gueliz." },
    ],
    relatedCategories: ["cultural", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guía de viaje a Marrakech — Mejores tours, consejos y aventuras | Marrakech Eco Tours",
    seoDescription: "Guía completa de Marrakech: paseos por la medina, zocos, Jemaa el-Fna y excursiones de un día a las Montañas del Atlas y el Sáhara. Reserva tours en grupos reducidos con guías bereberes locales.",
  },
  {
    slug: "high-atlas",
    name: "Montañas del Alto Atlas",
    subtitle: "El techo del norte de África",
    region: "Marrakech-Safi",
    lat: 31.0573,
    lng: -7.9149,
    heroImage: "https://images.unsplash.com/photo-1611859836043-a9177f500a27?w=1400&q=85",
    about:
      "El Alto Atlas es una de las grandes cordilleras de África: una columna vertebral de 2.400 km de picos glaciares, aldeas bereberes y antiguas rutas de mulas que se extiende desde el Atlántico hasta la frontera argelina. En su punto más alto se alza el Jbel Toubkal (4.167 m), el techo del norte de África y la cima de 4.000 metros más accesible del continente. Durante milenios, las comunidades bereberes han cultivado los valles en terrazas y recorrido los altos puertos por rutas invariables desde las caravanas medievales.",
    knownFor: [
      "El Jbel Toubkal, el pico más alto del norte de África con 4.167 m",
      "El pueblo de Imlil, punto de partida tradicional para la ascensión al Toubkal",
      "Comunidades bereberes de montaña con siglos de tradición",
      "Lagos alpinos, gargantas y valles glaciares",
      "La travesía del macizo del M'Goun, la ruta de trekking más remota de Marruecos",
      "Vistas espectaculares desde las crestas, que abarcan desde Marruecos hasta España",
    ],
    highlights: [
      { title: "Cima del Toubkal", desc: "El trekking de 4 días al Toubkal es el reto de montaña más emblemático de Marruecos. Partiendo de Imlil a 1.740 m, la ascensión atraviesa aldeas bereberes, refugios de montaña y el puerto de Tizi n'Ouanoums antes del último tramo hacia la cima, a 4.167 m." },
      { title: "El valle de Imlil", desc: "El pueblo puerta de entrada para todo el trekking del Alto Atlas. Rodeado de nogales y campos de trigo en terrazas, Imlil alberga a una comunidad de guías de montaña cuyas familias llevan generaciones trabajando estos senderos." },
      { title: "Aldeas bereberes", desc: "El Atlas es hogar de comunidades indígenas amazigh (bereberes) que han preservado su idioma, cultura y arquitectura a lo largo de siglos de historia. Muchas aldeas carecen de acceso por carretera, solo cuentan con senderos de mulas." },
      { title: "Macizo del M'Goun", desc: "Para trekkers experimentados que buscan soledad, la travesía del M'Goun (7 a 10 días) recorre algunos de los terrenos de gargantas y crestas más espectaculares del norte de África, con apenas infraestructura turística." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De abril a junio: flores silvestres, nieve en retirada de los altos puertos, condiciones ideales para el trekking." },
      { name: "Verano", emoji: "☀️", rating: 4, note: "De julio a agosto: senderos de cumbre despejados, calor en los valles pero fresco en altitud. Temporada alta." },
      { name: "Otoño", emoji: "🍂", rating: 5, note: "De septiembre a octubre: posiblemente las mejores condiciones, cielos estables, colores intensos, menos trekkers." },
      { name: "Invierno", emoji: "❄️", rating: 3, note: "De noviembre a marzo: la cima del Toubkal requiere crampones y piolet. Precioso pero exigente." },
    ],
    travelTips: [
      "Aclimátate en Marrakech (a 460 m) durante al menos un día antes de subir a Imlil (1.740 m).",
      "El Toubkal exige buena forma física, pero ninguna técnica de escalada en verano. En invierno es un auténtico objetivo de montañismo.",
      "Contrata a un guía bereber local con licencia: conoce cada piedra de la montaña y su presencia es obligatoria en el Parque Nacional del Toubkal.",
      "Las mulas pueden llevar el equipaje en la mayoría de rutas del Atlas; aprovéchalo para viajar más ligero.",
      "Lleva capas de abrigo incluso en verano: las temperaturas en el refugio del Toubkal pueden bajar de cero por la noche.",
    ],
    faqs: [
      { q: "¿Qué dificultad tiene el trekking al Toubkal?", a: "El Toubkal es un objetivo de trekking exigente (no de escalada técnica) que requiere buena forma cardiovascular. Deberías sentirte cómodo caminando de 6 a 8 horas al día con una mochila. En verano no se necesita equipo especial. En invierno son imprescindibles los crampones y el piolet." },
      { q: "¿Cuánto se tarda en llegar a la cima del Toubkal?", a: "La ruta estándar desde Imlil, ida y vuelta, dura de 3 a 4 días. Día 1: Imlil hasta el refugio (4-5 horas). Día 2: intento de cima desde el refugio (3-4 horas de subida, 2,5 horas de bajada). Días 3-4: descenso y visitas opcionales a aldeas bereberes." },
      { q: "¿Es obligatorio un guía para el trekking al Toubkal?", a: "Un guía con licencia no es legalmente obligatorio, pero se recomienda encarecidamente y lo exigen la mayoría de operadores responsables. El terreno es exigente, el clima cambia rápido, y los guías locales aportan seguridad, conocimiento de la ruta y un valioso contexto cultural." },
      { q: "¿Cuál es la mejor base para el trekking en el Alto Atlas?", a: "El pueblo de Imlil (1.740 m), a 62 km de Marrakech, es el punto de partida clásico para el Toubkal. Azilal es la base para los treks del macizo del M'Goun. Ambos requieren guía y una preparación adecuada." },
    ],
    relatedCategories: ["trekking", "hiking"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guía de viaje al Alto Atlas — Trekking al Toubkal y aldeas bereberes | Marrakech Eco Tours",
    seoDescription: "Explora las Montañas del Alto Atlas con guías locales certificados: trekking a la cima del Toubkal (4.167 m), paseos por aldeas bereberes y travesías de varios días por el Atlas. Grupos reducidos desde Marrakech.",
  },
  {
    slug: "sahara",
    name: "Desierto del Sáhara",
    subtitle: "Las dunas doradas de Erg Chebbi",
    region: "Drâa-Tafilalet",
    lat: 31.1513,
    lng: -3.9785,
    heroImage: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1400&q=85",
    about:
      "Erg Chebbi, cerca del pueblo de Merzouga, es la sección más espectacular del mar de arena sahariano de Marruecos: un campo de dunas estrelladas de 50 km² que se eleva hasta 150 metros sobre la hamada llana (llanura de grava). Las dunas están compuestas enteramente de fina arena rojiza-anaranjada, esculpida por los vientos dominantes del noroeste en clásicas formas de barjanes en forma de media luna. Al atardecer y al amanecer, la luz transforma el Erg en un paisaje de oro y cobre fundidos que no existe en ningún otro lugar del mundo.",
    knownFor: [
      "Dunas de hasta 150 m, entre las más altas de Marruecos",
      "Paseo en camello al atardecer hacia el corazón del Erg",
      "Auténticas noches en campamentos nómadas bereberes bajo las estrellas",
      "Observación de la Vía Láctea, lejos de cualquier contaminación lumínica",
      "El pueblo de Merzouga, puerta de entrada al desierto",
      "Rutas en quad y excursiones en 4x4 por el desierto",
    ],
    highlights: [
      { title: "Las dunas de Erg Chebbi", desc: "El campo de dunas es más espectacular a la hora dorada; llega al atardecer para ver el espectáculo de luz que tiñe la arena de todos los tonos de cobre, ámbar y rosa. Al amanecer, los colores se invierten: los azules fríos dan paso al oro cálido mientras el sol asciende por la cresta de las dunas." },
      { title: "Paseo en camello", desc: "La travesía tradicional del Erg se hace en camello: un viaje lento y meditativo hacia el desierto que te conecta con milenios de rutas de caravanas comerciales. Nuestros guías bereberes siguen los mismos caminos que recorrieron sus antepasados." },
      { title: "Noches en el campamento del desierto", desc: "Dormir en una jaima bereber dentro del Erg, lejos de cualquier carretera o asentamiento, es una de las experiencias más profundas que ofrece el viajar. El silencio es absoluto. La Vía Láctea, en un cielo libre de contaminación lumínica, resulta extraordinaria." },
      { title: "Actividades en el desierto", desc: "Más allá del clásico paseo en camello, el Erg y la hamada circundante ofrecen sandboard en las laderas de las dunas, rutas en quad por las llanuras de grava y excursiones en 4x4 a oasis y yacimientos de fósiles del desierto." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De marzo a mayo: temperaturas ideales (20-28 °C), con flores silvestres ocasionales en la hamada tras las lluvias invernales." },
      { name: "Verano", emoji: "☀️", rating: 1, note: "De junio a agosto: calor extremo (40-48 °C). No se recomienda viajar al desierto en pleno verano." },
      { name: "Otoño", emoji: "🍂", rating: 5, note: "De septiembre a noviembre: días cálidos, noches frescas, condiciones perfectas para acampar en el desierto." },
      { name: "Invierno", emoji: "❄️", rating: 4, note: "De diciembre a febrero: noches frías (cercanas a cero en enero) pero cielos despejados e impresionantes. Lleva ropa de abrigo para el campamento." },
    ],
    travelTips: [
      "Lleva ropa de abrigo para las noches del desierto: las temperaturas caen drásticamente tras la puesta de sol incluso en primavera y otoño.",
      "Lleva una linterna y agua adicional en los paseos en camello. Las dunas pueden resultar desorientadoras de noche.",
      "La arena se cuela por todas partes. Usa una bolsa estanca para el equipo fotográfico y sella bien los artículos de aseo.",
      "El sandboard es divertido pero físicamente exigente: subir de nuevo dunas de 150 m resulta agotador.",
      "El amanecer sobre el Erg es tan espectacular como el atardecer: pon el despertador y sube a la cresta de duna más cercana antes de que amanezca.",
    ],
    faqs: [
      { q: "¿A qué distancia está Merzouga de Marrakech?", a: "Merzouga se encuentra aproximadamente a 560 km de Marrakech, unas 9-10 horas en coche. La mayoría de los tours al desierto conducen por un camino de ida (habitualmente por la garganta del Dades y el Valle de las Mil Kasbahs) y regresan por una ruta meridional distinta. También es posible un trayecto de ida y vuelta en una noche para tours económicos." },
      { q: "¿Es suficiente un tour de 3 días al Sáhara?", a: "3 días ofrecen la experiencia esencial: cruzar el Atlas y la región de las kasbahs, una noche completa en el campamento del desierto y el viaje de regreso. Para una experiencia más completa, 4-5 días permiten explorar el Valle de las Rosas, la garganta de Todra y varias zonas de dunas." },
      { q: "¿Qué incluye una noche de campamento en el Sáhara?", a: "Las noches de campamento estándar incluyen una jaima bereber tradicional, cena (tajín y cuscús), música en directo alrededor de la fogata y desayuno antes del paseo en camello al amanecer. Los campamentos privados más lujosos cuentan con camas de verdad y baño propio." },
      { q: "¿Puedo visitar el Sáhara de forma independiente?", a: "Sí, pero la experiencia es notablemente más rica con un guía local experto. Orientarse en las dunas no es sencillo, y los guías locales aportan contexto cultural, acceso lingüístico con familias bereberes, y una logística que llevaría días organizar de forma independiente." },
    ],
    relatedCategories: ["desert"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Tour por el desierto del Sáhara desde Marrakech — Guía de Erg Chebbi y Merzouga | Marrakech Eco Tours",
    seoDescription: "Descubre el desierto del Sáhara con guías certificados: paseos en camello, noches en campamentos bereberes y amanecer sobre las dunas de 150 m de Erg Chebbi. Tours de 2-4 días por el desierto desde Marrakech.",
  },
  {
    slug: "fes",
    name: "Fez el-Bali",
    subtitle: "La ciudad medieval viva",
    region: "Fès-Meknès",
    lat: 34.0545,
    lng: -4.9815,
    heroImage: "https://images.unsplash.com/photo-1582742850838-24590fb39fdc?w=1400&q=85",
    about:
      "Fez el-Bali es posiblemente la superviviente urbana más extraordinaria del planeta: una ciudad medieval plenamente funcional de 156.000 habitantes, que cubre 256 hectáreas y ha estado habitada de forma continua desde el año 789 d. C. Es la mayor zona urbana sin coches del mundo. Cada calle de su laberinto de 9.400 callejones transporta mercancías a mano o en mula. Los mismos oficios se han producido en los mismos talleres durante mil años: curtido de cuero, esmaltado de cerámica, incrustación de latón, mosaicos zellige. La ciudad fue fundada por Muley Idris I y se expandió bajo la dinastía merínida hasta convertirse en el gran centro de saber islámico que sigue siendo hoy.",
    knownFor: [
      "La mayor zona urbana sin coches del mundo, con 9.400 callejones",
      "La curtiduría Chouara, inalterada desde el siglo XI",
      "La Universidad de al-Qarawiyyin, fundada en el año 859, la más antigua del mundo",
      "La madrasa Bou Inania y la madrasa Attarine",
      "El Mellah (barrio judío) y sus vistas desde las azoteas",
      "Una tradición artesanal viva: zellige, bordado, cobre, cuero",
    ],
    highlights: [
      { title: "La curtiduría Chouara", desc: "El lugar más fotografiado de Marruecos después del Sáhara. Cubas de piedra llenas de tinte (azafrán, amapola, henna, índigo) donde los curtidores trabajan con las piernas sumergidas hasta la rodilla, procesando las pieles exactamente igual que hace 800 años. Se contempla mejor desde las terrazas de las tiendas de cuero que dan a los pozos." },
      { title: "Mezquita y Universidad de al-Qarawiyyin", desc: "Fundada en el año 859 por una mujer, Fátima al-Fihri, al-Qarawiyyin está reconocida por la UNESCO como la universidad en funcionamiento continuo más antigua del mundo. Los no musulmanes no pueden entrar en la mezquita, pero el patio que se vislumbra a través de las puertas talladas es una de las grandes joyas arquitectónicas de Marruecos." },
      { title: "El laberinto de la medina", desc: "A diferencia de la medina de Marrakech, la de Fez es verdaderamente laberíntica; incluso los guías con experiencia se orientan por puntos de referencia en lugar de un mapa mental. Perderse un poco es la mejor manera de encontrar el auténtico Fez: pequeñas panaderías, tejedores de alfombras, mezquitas de barrio y pequeñas plazas donde los ancianos juegan a las cartas." },
      { title: "El Mellah", desc: "El barrio judío del Fez antiguo, antaño hogar de una de las comunidades judías más importantes del norte de África, alberga una arquitectura magnífica de mediados del siglo XX, una sinagoga restaurada y las mejores vistas de la ciudad desde sus terrazas elevadas y su cementerio." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De marzo a mayo: temperaturas agradables (18-26 °C), tardes largas, entornos verdes." },
      { name: "Verano", emoji: "☀️", rating: 2, note: "De junio a agosto: muy caluroso (35-40 °C). La medina se vuelve agobiante. Se recomiendan visitas solo por la mañana." },
      { name: "Otoño", emoji: "🍂", rating: 5, note: "De septiembre a noviembre: clima perfecto, temporada de cosecha, Festival de Fez de Música Sagrada del Mundo (noviembre)." },
      { name: "Invierno", emoji: "❄️", rating: 3, note: "De diciembre a febrero: fresco y ocasionalmente lluvioso. Las curtidurías están menos concurridas y son más accesibles." },
    ],
    travelTips: [
      "Fez está a 3-4 horas en coche de Marrakech. La mayoría de tours a las ciudades imperiales combinan Fez, Mequinez y Volubilis en 3 días o más.",
      "Un guía local es indispensable en la medina: orientarse por cuenta propia lleva a la frustración. Incluso los locales se pierden.",
      "Las curtidurías son más coloridas por la mañana (el curtido vespertino ocurre más tarde en el día).",
      "Compra artículos de cuero en las tiendas de la curtiduría: la calidad es auténtica y el origen es rastreable.",
      "Prueba los platos fasíes más emblemáticos: la pastela (pastel de pichón y almendras), la sopa harira y la bastela au lait (pastel de leche).",
    ],
    faqs: [
      { q: "¿Cuántos días necesito en Fez?", a: "Dos días completos son el mínimo para cubrir los principales lugares de interés de la medina, las curtidurías y la Ville Nouvelle. Tres días permiten explorar el Mellah, el barrio andalusí, hacer una excursión a las ruinas romanas de Volubilis y recorrer la medina con calma." },
      { q: "¿Está Fez en la ruta de carretera de Marrakech a Fez?", a: "Sí. Marrakech a Fez es la ruta terrestre clásica de Marruecos, que suele tomar de 3 a 6 días pasando por la garganta del Dades, la garganta de Todra, el Sáhara de Merzouga y los bosques de cedros del Atlas Medio. Es uno de los grandes road trips del norte de África." },
      { q: "¿Debo alojarme dentro de la medina o en la Ville Nouvelle?", a: "Aloja en la medina. La experiencia del riad es fundamental para entender Fez: cruzar un muro exterior sencillo para descubrir un patio interior ornamentado con fuente es uno de los momentos más evocadores de Marruecos. La Ville Nouvelle no tiene carácter histórico." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guía de viaje a Fez el-Bali — Tours por la medina, curtidurías y ciudad imperial | Marrakech Eco Tours",
    seoDescription: "Explora Fez el-Bali, la ciudad medieval más intacta del mundo. Tours guiados por la curtiduría Chouara, la Universidad de al-Qarawiyyin y la medina de 9.400 callejones. Excursiones de un día y tours de varios días desde Marrakech.",
  },
  {
    slug: "chefchaouen",
    name: "Chefchaouen",
    subtitle: "La perla azul de Marruecos",
    region: "Tanger-Tétouan-Al Hoceïma",
    lat: 35.1688,
    lng: -5.2689,
    heroImage: "https://images.unsplash.com/photo-1569383746724-6f1b882b8f46?w=1400&q=85",
    about:
      "Chefchaouen se asienta en las laderas de las montañas del Rif, a 600 m sobre el nivel del mar: una medina pequeña y notablemente bien conservada cuyos muros, escaleras y macetas están pintados uniformemente de azul y blanco. La tradición de pintar de azul, introducida por refugiados judíos que huían de la Reconquista española en la década de 1930, se ha vuelto tan central en la identidad del pueblo que sus residentes repintan sus propias casas cada primavera. El efecto no se parece a nada más en Marruecos: sereno, fotogénico y genuinamente tranquilo.",
    knownFor: [
      "Una medina pintada por completo de azul y blanco",
      "Un entorno en las montañas del Rif con vistas espectaculares a las gargantas",
      "El río Ras el-Ma, su cascada y sus piedras de lavado",
      "La plaza Uta el-Hammam, la plaza principal rodeada de cafés",
      "Tejido artesanal de lana y artesanía tradicional del Rif",
      "Puerta de entrada al Parque Nacional de Talassemtane",
    ],
    highlights: [
      { title: "La medina azul", desc: "Cada muro, escalón y marco de puerta está pintado en tonos que van del azul cielo pálido al índigo profundo. La medina es lo bastante pequeña como para explorarla en un día, pero lo bastante gratificante como para quedarse tres. Cada rincón es una fotografía." },
      { title: "Ras el-Ma", desc: "A un corto paseo de la medina, el manantial de Ras el-Ma brota de la montaña hacia un pequeño río donde los lugareños lavan la ropa a la manera tradicional. Un escape apacible lejos de la plaza central, más concurrida por turistas." },
      { title: "Parque Nacional de Talassemtane", desc: "El parque comienza en el límite de la medina y ofrece caminatas de medio día por bosques de cedros y robles, paseos por gargantas sobre el río Laou y vistas hacia la ciudad azul que queda abajo." },
      { title: "La Mezquita Española", desc: "Una caminata cuesta arriba de 20 minutos desde la medina (o accesible por un sendero rocoso) conduce a una mezquita construida por los españoles, con vistas panorámicas sobre toda la ciudad azul y los valles del Rif circundantes; mejor al atardecer." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De abril a junio: temperaturas suaves, colinas verdes, flores silvestres en las laderas del Rif. Temporada alta." },
      { name: "Verano", emoji: "☀️", rating: 4, note: "De julio a agosto: cálido pero llevadero en altitud. Las noches son frescas. Muy concurrido: reserva con antelación." },
      { name: "Otoño", emoji: "🍂", rating: 4, note: "De septiembre a noviembre: temperaturas agradables, más tranquilo que el verano." },
      { name: "Invierno", emoji: "❄️", rating: 2, note: "De diciembre a marzo: puede ser frío y lluvioso. Nieve ocasional en las crestas del Rif. Muy tranquilo." },
    ],
    travelTips: [
      "Chefchaouen se disfruta mejor con una pernoctación, no como excursión de un día: la ciudad es más mágica a primera hora de la mañana, antes de que lleguen los autobuses turísticos.",
      "Las calles azules son más vívidas con la luz de primera hora (antes de las 9:00) y con el dorado de última hora de la tarde.",
      "Excelente base para caminatas por las montañas del Rif. Pregunta en tu riad por guías de senderos locales.",
      "La medina es pequeña: 'perderse' intencionadamente conduce a los callejones y talleres de artesanos más interesantes.",
      "Compra productos locales: las mantas de lana, las chilabas y los artículos de cuero son de tradición rifeña y de excelente calidad.",
    ],
    faqs: [
      { q: "¿Cómo llego a Chefchaouen desde Marrakech?", a: "No hay ruta directa: Chefchaouen está a 530 km de Marrakech, aproximadamente 6-7 horas en coche o autobús. La mayoría de visitantes llegan vía Fez o Tánger. El enfoque más práctico es un tour de varios días por las ciudades imperiales que incluya Fez, Chefchaouen, Mequinez y el regreso a Marrakech." },
      { q: "¿Por qué está Chefchaouen pintada de azul?", a: "La tradición de pintar de azul se introdujo en la década de 1930 por refugiados judíos que huían de la Reconquista española. En la tradición judía, el azul simboliza el cielo. Con el tiempo, toda la medina adoptó esta práctica como parte de su identidad, y los lugareños repintan sus casas cada primavera." },
      { q: "¿Merece la pena el viaje a Chefchaouen desde Marrakech?", a: "Sí, pero requiere al menos una pernoctación para apreciarla correctamente. Visitarla como excursión de un día (solo posible desde Fez o Tánger, a 1,5-2 horas) deja muy poco tiempo. Una pernoctación permite experimentar la medina en su momento más tranquilo y hermoso." },
    ],
    relatedCategories: ["cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guía de viaje a Chefchaouen — La ciudad azul de Marruecos | Marrakech Eco Tours",
    seoDescription: "Descubre Chefchaouen, la famosa ciudad azul de Marruecos en las montañas del Rif. Tours guiados, senderismo en el Parque Nacional de Talassemtane y pernoctaciones en la medina pintada.",
  },
  {
    slug: "agadir",
    name: "Agadir",
    subtitle: "Costa atlántica y capital del surf",
    region: "Souss-Massa",
    lat: 30.4278,
    lng: -9.5981,
    heroImage: "https://images.unsplash.com/photo-1562874732-260714dfe537?w=1400&q=85",
    about:
      "Agadir es la principal ciudad de playa de Marruecos: un puerto atlántico moderno reconstruido por completo tras un terremoto catastrófico en 1960. Situada al pie de las montañas del Antiatlas, con una media luna de playa de arena blanca de nueve kilómetros, Agadir sirve de puerta de entrada meridional a Marruecos tanto para turistas de paquete como para aventureros. Treinta minutos al norte se encuentra Taghazout, un pueblo que se ha convertido en uno de los destinos de surf más famosos del mundo. La región de Souss-Massa que rodea Agadir alberga parques nacionales, bosques de argán, humedales llenos de flamencos y comunidades bereberes que mantienen un modo de vida centenario.",
    knownFor: [
      "9 km de playa atlántica, la playa urbana más larga de Marruecos",
      "Taghazout, surf de categoría mundial (Anchor Point, Hash Point, Killer Point)",
      "Parque Nacional de Souss-Massa (flamencos, ibis eremita, gacelas)",
      "El Valle del Paraíso, oasis de palmeras, piscinas turquesa y baño natural",
      "Cooperativas de aceite de argán: el Souss es el único bosque de argán del mundo",
      "Marisco fresco en el puerto pesquero activo de Agadir",
    ],
    highlights: [
      { title: "Surf en Taghazout", desc: "El pueblo de Taghazout (30 min al norte de Agadir) tiene rompientes de arrecife de categoría mundial, adecuados para todos los niveles. Anchor Point produce las olas más largas de Marruecos. La temporada de surf dura todo el año, con los oleajes más grandes de octubre a marzo." },
      { title: "Parque Nacional de Souss-Massa", desc: "Una reserva de humedales costeros a 45 minutos al sur de Agadir, hogar de una de las últimas colonias silvestres de ibis eremita del mundo, grandes bandadas de flamencos y la amenazada gacela dorcas. Un patrimonio natural extraordinario y a menudo pasado por alto." },
      { title: "Valle del Paraíso", desc: "Un oasis escondido a 30 km tierra adentro desde Agadir: una estrecha garganta bordeada de palmeras con una serie de pozas naturales turquesa para bañarse. Se llega tras un breve descenso desde la carretera; es la escapada perfecta de medio día lejos de la playa." },
      { title: "El país del argán", desc: "La llanura del Souss, entre Agadir y Taroudant, es el único lugar del mundo donde el argán crece de forma silvestre. Cooperativas de mujeres cosechan y prensan el aceite a mano. Visitar una de ellas es una experiencia turística auténtica e importante." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De marzo a mayo: cálido, soleado, ideal para playa y surf. El agua atlántica sigue fresca pero apta para el baño." },
      { name: "Verano", emoji: "☀️", rating: 4, note: "De junio a agosto: calor fiable. Los vientos alisios del Atlántico mantienen las temperaturas más bajas que en el interior de Marruecos." },
      { name: "Otoño", emoji: "🍂", rating: 5, note: "De septiembre a noviembre: comienza la mejor temporada de surf. Mar cálido, oleajes constantes." },
      { name: "Invierno", emoji: "❄️", rating: 4, note: "De diciembre a febrero: suave para los estándares marroquíes (15-20 °C). El mayor oleaje del año. Playa menos concurrida." },
    ],
    travelTips: [
      "Agadir está a 3 horas al sur de Marrakech por carretera (256 km) o a 40 minutos en vuelo directo.",
      "El paseo marítimo es excelente para ir en bicicleta; varias tiendas de alquiler operan a lo largo de la costa.",
      "Las clases de surf están disponibles todo el año en Taghazout para principiantes. Reserva directamente a través del campamento de surf, no en mostradores turísticos.",
      "Los zocos de Inezgane (10 km al sur de Agadir) son una alternativa más auténtica y menos orientada al turismo que el zoco de la ciudad de Agadir.",
      "La colina de la kasba restaurada de Agadir quedó arrasada en el terremoto de 1960; solo quedan los muros, pero la vista sobre la bahía merece la subida.",
    ],
    faqs: [
      { q: "¿Es Agadir una buena base para explorar el sur de Marruecos?", a: "Sí. Agadir está idealmente ubicada para excursiones de un día al Valle del Paraíso, Immouzer du Kandar, Taroudant (el 'pequeño Marrakech'), el zoco de plata de Tiznit y las montañas del Antiatlas. También son posibles viajes de varios días al desierto del Sáhara desde Agadir (560 km hasta Merzouga)." },
      { q: "¿Cuál es la temporada de surf en Taghazout?", a: "Taghazout produce olas surfeables todo el año. Los oleajes más grandes y potentes llegan de octubre a marzo. De abril a septiembre son más suaves y adecuados para surfistas principiantes-intermedios. La temperatura del agua varía entre 16 °C en invierno y 22 °C en verano." },
      { q: "¿Puedo combinar Agadir y Marrakech en un mismo viaje?", a: "Por supuesto; este es el enfoque estándar de muchos de nuestros tours. Vuela a Marrakech, viaja a Agadir por carretera (atravesando las estribaciones del Atlas y el país del argán) y regresa a Marrakech para tu vuelo de vuelta. O viceversa. La ruta del puerto de montaña de Tizi n'Test es espectacular." },
    ],
    relatedCategories: ["day-tours", "hiking"],
    relatedOrigins: ["agadir"],
    seoTitle: "Guía de viaje a Agadir — Playa atlántica, surf y excursiones | Marrakech Eco Tours",
    seoDescription: "Guía completa de Agadir: surf en Taghazout, Parque Nacional de Souss-Massa, Valle del Paraíso y excursiones desde la costa atlántica de Marruecos. Tours en grupos reducidos con guías locales.",
  },
  {
    slug: "ouzoud",
    name: "Cascadas de Ouzoud",
    subtitle: "La maravilla natural más espectacular de Marruecos",
    region: "Béni Mellal-Khénifra",
    lat: 32.0187,
    lng: -6.7188,
    heroImage: "https://images.unsplash.com/photo-1535027341838-aa4d6ab54a25?w=1400&q=85",
    about:
      "Las cascadas de Ouzoud son las más espectaculares del norte de África: una triple caída de agua de 110 metros sobre acantilados rojizos hasta una poza turquesa alimentada por el río El-Abid. El nombre 'Ouzoud' significa 'moler aceitunas' en tamazight (bereber), en referencia a los molinos de aceite tradicionales que llevan generaciones funcionando aquí. El lugar se encuentra en una garganta profunda rodeada de olivares e higuerales, y alberga una colonia de macacos de Berbería salvajes, los únicos primates salvajes de África fuera del África subsahariana.",
    knownFor: [
      "Una triple cascada de 110 m, la más espectacular de Marruecos",
      "Colonia de macacos de Berbería salvajes (el único primate salvaje del norte de África)",
      "Poza natural turquesa para bañarse en la base",
      "Arcoíris visible al mediodía cuando el sol está alto",
      "Molinos tradicionales de aceite de oliva bereberes en la garganta",
      "Dramática caminata por la garganta a lo largo del río El-Abid",
    ],
    highlights: [
      { title: "Las cascadas", desc: "Tres corrientes paralelas convergen en una serie de repisas rocosas antes de la caída principal. El caudal es mayor tras las lluvias invernales (enero-marzo), pero las cascadas fluyen todo el año. Al mediodía en primavera y verano se forma un arcoíris permanente en la neblina, uno de los fenómenos naturales más hermosos de Marruecos." },
      { title: "Macacos de Berbería", desc: "La colonia de macacos de Berbería salvajes (Macaca sylvanus) en Ouzoud es una de las poblaciones de primates más accesibles del mundo. Los macacos están habituados a la presencia humana pero siguen siendo salvajes: no los alimentes y mantén tu comida asegurada. Están protegidos por la ley marroquí." },
      { title: "La caminata por la garganta", desc: "Un sendero desciende desde lo alto de las cascadas junto a las caídas, cruza el río en la poza de la base y continúa por la garganta. El recorrido completo (3-4 horas) pasa por molinos de aceite tradicionales, zonas de baño y miradores de vuelta hacia las cascadas desde abajo." },
      { title: "Molinos de aceite", desc: "Familias bereberes han operado prensas de oliva de rueda de piedra en la garganta bajo las cascadas durante siglos. En la temporada de la cosecha de aceitunas (noviembre-enero) puedes observar el prensado en frío tradicional, hecho exactamente igual que durante generaciones." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 5, note: "De marzo a mayo: máximo caudal de agua, arcoíris permanente, flores silvestres. El mejor momento para visitar." },
      { name: "Verano", emoji: "☀️", rating: 4, note: "De junio a agosto: caluroso (35 °C o más) pero la poza es refrescante. Muy concurrido los fines de semana." },
      { name: "Otoño", emoji: "🍂", rating: 4, note: "De septiembre a noviembre: temporada de cosecha de aceitunas, buen caudal de agua, temperaturas agradables." },
      { name: "Invierno", emoji: "❄️", rating: 3, note: "De diciembre a febrero: máxima pluviosidad, cascadas en su máxima potencia, pero frío y ocasionalmente embarrado." },
    ],
    travelTips: [
      "Ouzoud está a 3 horas de Marrakech (150 km). La mayoría de visitantes combinan una caminata de un día y regresan la misma tarde.",
      "Llega temprano (antes de las 9:00) para tener las cascadas y la poza base prácticamente solo para ti.",
      "El sendero de descenso hacia la base puede resbalar: usa calzado con buen agarre, no sandalias.",
      "Lleva ropa de recambio: la neblina y el baño hacen que mojarse sea inevitable.",
      "No alimentes a los macacos: perturba su comportamiento natural y los habitúa a la comida humana.",
    ],
    faqs: [
      { q: "¿A qué distancia están las cascadas de Ouzoud de Marrakech?", a: "Ouzoud está aproximadamente a 150 km de Marrakech, unas 3 horas en coche. El trayecto pasa por Azilal y la meseta de Beni Mellal. Ofrecemos excursiones guiadas de día completo desde Marrakech que incluyen transporte, guía y caminata por la garganta." },
      { q: "¿Puedo bañarme en la base de las cascadas?", a: "Sí, la poza natural en la base de las cascadas es uno de los lugares para nadar más bonitos de Marruecos. El agua está fría (alimentada por manantiales de montaña) pero es refrescante, sobre todo en verano." },
      { q: "¿Es Ouzoud una buena excursión de un día desde Marrakech?", a: "Sí, es la excursión de un día más popular desde Marrakech. Un día completo (7:00-19:00) permite 4-5 horas en las cascadas y la garganta. Una pernoctación en el pueblo permite una visita matinal antes de que lleguen las multitudes del día, lo cual es la mejor manera de vivirla." },
    ],
    relatedCategories: ["hiking", "day-tours"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Excursión de un día a las cascadas de Ouzoud desde Marrakech — Guía y tours | Marrakech Eco Tours",
    seoDescription: "Visita las cascadas de Ouzoud (110 m) desde Marrakech: caminatas guiadas por la garganta, macacos de Berbería salvajes, pozas para nadar y arcoíris natural. Tours de día completo con guías locales.",
  },
  {
    slug: "essaouira",
    name: "Essaouira",
    subtitle: "La ventosa ciudad amurallada del Atlántico",
    region: "Marrakech-Safi",
    lat: 31.5085,
    lng: -9.7595,
    heroImage: "https://images.unsplash.com/photo-1555686367-56d5186965d5?w=1400&q=85",
    about:
      "Essaouira es el gran contrapunto atlántico de Marrakech: encalada donde Marrakech es rojo rosado, azotada por el viento donde Marrakech está en calma, y profundamente relajada donde Marrakech es eléctrica. Las fortificaciones portuguesas del siglo XVIII de la ciudad se adentran en el oleaje atlántico, encerrando una medina Patrimonio de la Humanidad por la UNESCO de contraventanas azules en arco, reparaciones de redes de pesca y música gnawa que flota desde las puertas de los cafés. Essaouira ha atraído durante mucho tiempo a artistas, músicos y escritores; Jimi Hendrix la visitó en 1969 e inspiró a toda una generación de viajeros a seguir sus pasos.",
    knownFor: [
      "Medina declarada Patrimonio de la Humanidad con murallas marítimas portuguesas del siglo XVIII",
      "Kitesurf y windsurf de categoría mundial (vientos atlánticos constantes)",
      "Música gnawa: el blues espiritual de la herencia africana de Marruecos",
      "Flota de pesca azul en activo y marisco fresco",
      "Marquetería en madera de thuya, la artesanía característica de Essaouira",
      "Las murallas de la Skala, un paseo bordeado de cañones sobre el Atlántico",
    ],
    highlights: [
      { title: "Las murallas", desc: "Las murallas marítimas de Essaouira fueron construidas en el siglo XVIII por un arquitecto francés encargado por el sultán alauí. La Skala de la Ville, una amplia terraza bordeada de cañones que mira al Atlántico, es uno de los paseos más impresionantes de Marruecos, especialmente al atardecer cuando regresan los barcos de pesca." },
      { title: "Música gnawa", desc: "Essaouira es el hogar espiritual del gnawa, la antigua tradición musical de influencia africana de Marruecos, enraizada en la cultura de las comunidades de África Occidental traídas a Marruecos como esclavos. El Festival Gnaoua y Músicas del Mundo (junio) atrae a músicos de toda África y más allá." },
      { title: "Paraíso del kitesurf", desc: "Los vientos alisios constantes que soplan del noreste durante los meses de verano hacen de Essaouira uno de los grandes destinos mundiales del kitesurf. La playa al sur de la ciudad es utilizada todo el año por surfistas, kitesurfistas y windsurfistas." },
      { title: "La medina", desc: "A diferencia del laberinto de Marrakech, la medina de Essaouira está planificada lógicamente en cuadrícula: más fácil de recorrer, pero igualmente evocadora. La Puerta de la Marina, los zocos de especias y joyería, y la subasta de pescado en el puerto se cuentan entre sus destacados." },
    ],
    seasons: [
      { name: "Primavera", emoji: "🌸", rating: 4, note: "De abril a junio: cálido, vientos moderados, tardes largas. Festival Gnaoua en junio." },
      { name: "Verano", emoji: "☀️", rating: 5, note: "De julio a agosto: alisios a plena fuerza, perfecto para el kitesurf. Fresco para los estándares marroquíes (22-26 °C)." },
      { name: "Otoño", emoji: "🍂", rating: 4, note: "De septiembre a noviembre: temperaturas agradables, buen surf, menos turistas que en verano." },
      { name: "Invierno", emoji: "❄️", rating: 3, note: "De diciembre a marzo: temporada más ventosa y fresca. La ciudad está entonces en su momento más tranquilo y evocador." },
    ],
    travelTips: [
      "Essaouira está a 3 horas de Marrakech (170 km). Las excursiones de un día son posibles, pero una pernoctación es mucho mejor.",
      "Lleva una capa cortavientos incluso en verano: el viento alisio constante puede hacer que el paseo marítimo resulte frío.",
      "El marisco más fresco está en los puestos de pescado del puerto (al este de la puerta principal): elige tu pescado y hazlo asar al momento.",
      "La marquetería en madera de thuya es la especialidad artesanal local: busca piezas auténticas hechas del nudo de raíz de thuya, no imitaciones teñidas de pino.",
      "Camina por las murallas al atardecer para disfrutar de la mejor luz sobre el Atlántico y la flota pesquera.",
    ],
    faqs: [
      { q: "¿Cómo llego de Marrakech a Essaouira?", a: "Los autobuses Supratours salen dos veces al día desde Marrakech (Bab Doukkala) y tardan entre 2,5 y 3 horas. Los taxis compartidos son más rápidos pero más apretados. Los coches privados y traslados turísticos tardan 2,5 horas por la autopista A7. No hay conexión de tren." },
      { q: "¿Es Essaouira buena para quienes no practican surf?", a: "Sin duda; Essaouira es uno de los destinos más completos de Marruecos para quienes no hacen surf. La medina, las murallas, la música gnawa, el marisco, los talleres de artesanos y los paseos por la playa ofrecen un itinerario completo sin ningún deporte acuático." },
      { q: "¿Por qué visitó Jimi Hendrix Essaouira?", a: "Hendrix visitó Essaouira en 1969 durante su larga estancia en Marruecos, atraído por la comunidad artística de la ciudad y las tradiciones musicales gnawa. Se quedó varios días y la visita se ha convertido desde entonces en una celebrada parte de la mitología cultural de la ciudad. Una casa en la que supuestamente se alojó cerca de la medina es hoy un pequeño museo, aunque su exactitud histórica es objeto de debate." },
    ],
    relatedCategories: ["day-tours", "cultural"],
    relatedOrigins: ["marrakech"],
    seoTitle: "Guía de viaje a Essaouira — Kitesurf, música gnawa y medina | Marrakech Eco Tours",
    seoDescription: "Descubre Essaouira: medina atlántica declarada Patrimonio de la Humanidad, kitesurf de categoría mundial, música gnawa y marisco. Excursiones de un día y tours de varios días desde Marrakech con guías locales.",
  },
];

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.slug === slug);
}
