/**
 * Marrakech Eco Tours — post-tour quality form.
 * Generated for 48 tours. Internal quality tracking; nothing is published.
 *
 * WHY THE CLIENT NEVER SCROLLS 48 TOURS
 * -------------------------------------
 * Two paths, both built by this script:
 *
 *  1. THE LINK YOU SEND. makeLinks() prints one link per tour with the tour
 *     already filled in. The client lands straight on the questions. This is
 *     the path you will use every time.
 *
 *  2. THE PICKER, for when someone opens the bare form. Google Forms cannot
 *     filter a list live — every question is fixed when the form is built —
 *     but an answer CAN jump to a different page. So the narrowing is real,
 *     built out of pages:
 *
 *         kind of trip?  ->  how long?  ->  a list of 1-7 tours
 *
 *     27 leaf pages, most holding three tours or fewer. Three taps, no
 *     scrolling.
 *
 * SETUP
 *   1. script.google.com -> New project
 *   2. Paste this whole file, replacing the default myFunction
 *   3. Run -> createForm    (approve the permission prompt once)
 *   4. Run -> makeLinks     then View -> Executions/Logs to copy the links
 *
 * Re-running createForm builds a BRAND NEW form and leaves the old one
 * untouched. If you have hand-edited questions in the Forms UI, re-running
 * will not carry those edits across.
 *
 * Verified against the Apps Script Forms reference (Sept 2026): prefilling is
 * FormResponse.toPrefilledUrl(), branching is Choice navigation, and choice
 * navigation overrules a page's own setGoToPage.
 */

/** Generated by scripts/build-feedback-form.mjs. Do not hand-edit. */
var TOURS = [
  { slug: "zagora-2day-marrakech", title: "Marrakech to Zagora — 2-Day Desert Tour", cat: "desert", origin: "marrakech", days: 2, type: "private" },
  { slug: "merzouga-stargazing-desert-tour", title: "Merzouga Stargazing from Marrakech — 2-Day Dark Sky Desert Tour", cat: "desert", origin: "marrakech", days: 2, type: "private" },
  { slug: "shared-zagora-2day-marrakech", title: "Zagora Desert from Marrakech — 2-Day Shared Tour", cat: "desert", origin: "marrakech", days: 2, type: "shared" },
  { slug: "erg-chegaga-3day-marrakech", title: "Erg Chegaga from Marrakech — 3-Day Remote Desert Expedition", cat: "desert", origin: "marrakech", days: 3, type: "private" },
  { slug: "sahara-3day-marrakech", title: "Marrakech to Merzouga — 3-Day Desert Tour", cat: "desert", origin: "marrakech", days: 3, type: "private" },
  { slug: "shared-merzouga-3day-marrakech", title: "Merzouga Desert from Marrakech — 3-Day Shared Tour", cat: "desert", origin: "marrakech", days: 3, type: "shared" },
  { slug: "family-desert-4day-marrakech", title: "Family Desert Adventure — 4-Day Marrakech to Sahara", cat: "desert", origin: "marrakech", days: 4, type: "private" },
  { slug: "desert-4day-marrakech", title: "Marrakech Desert Grand Tour — 4 Days", cat: "desert", origin: "marrakech", days: 4, type: "private" },
  { slug: "chegaga-camel-trek-8day", title: "Draa Valley to M'hamid — 8-Day Chegaga Camel Trek", cat: "desert", origin: "marrakech", days: 8, type: "private" },
  { slug: "azzaden-valley-2day-trek", title: "Azzaden Valley from Marrakech — 2-Day Atlas Mountains Trek", cat: "trekking", origin: "marrakech", days: 2, type: "private" },
  { slug: "toubkal-summit-2day-marrakech", title: "Mount Toubkal Express — 2-Day Summit from Marrakech", cat: "trekking", origin: "marrakech", days: 2, type: "private" },
  { slug: "atlas-mountains-3day-trek", title: "High Atlas Villages from Marrakech — 3-Day Trek", cat: "trekking", origin: "marrakech", days: 3, type: "private" },
  { slug: "toubkal-three-peaks-4000m-3day", title: "Toubkal Three 4,000 m Peaks from Marrakech — 3-Day Challenge", cat: "trekking", origin: "marrakech", days: 3, type: "private" },
  { slug: "toubkal-aguelzim-pass-3day", title: "Toubkal via Aguelzim Pass from Marrakech — 3-Day Trek", cat: "trekking", origin: "marrakech", days: 3, type: "private" },
  { slug: "toubkal-summit-trek-4day", title: "4-Day Toubkal Summit Trek from Marrakech", cat: "trekking", origin: "marrakech", days: 4, type: "private" },
  { slug: "family-atlas-4day-trek", title: "Family High Atlas from Marrakech — 4-Day Gentle Trek", cat: "trekking", origin: "marrakech", days: 4, type: "private" },
  { slug: "toubkal-summit-sahara-5day", title: "Toubkal & Sahara from Marrakech — 5-Day Mountain-to-Desert Tour", cat: "trekking", origin: "marrakech", days: 5, type: "private" },
  { slug: "toubkal-circuit-ifni-lake-6day", title: "Toubkal Circuit & Ifni Lake from Marrakech — 6-Day Trek", cat: "trekking", origin: "marrakech", days: 6, type: "private" },
  { slug: "mgoun-massif-trek", title: "Marrakech to Mgoun Massif — 7-Day Traverse", cat: "trekking", origin: "marrakech", days: 7, type: "private" },
  { slug: "morocco-highlights-toubkal-sahara-8day", title: "8-Day Morocco Highlights: Toubkal Summit and Sahara Desert", cat: "trekking", origin: "marrakech", days: 8, type: "shared" },
  { slug: "high-atlas-grand-traverse-15day", title: "High Atlas Grand Traverse — 15-Day M'Goun to Toubkal Trek from Marrakech", cat: "trekking", origin: "marrakech", days: 15, type: "private" },
  { slug: "marrakech-medina-cultural-tour", title: "Marrakech Medina — Cultural Tour", cat: "cultural", origin: "marrakech", days: 1, type: "private" },
  { slug: "marrakech-to-fes-3day", title: "Marrakech to Fes — 3-Day Imperial Cities Tour", cat: "cultural", origin: "marrakech", days: 3, type: "private" },
  { slug: "marrakech-to-chefchaouen-4day", title: "Marrakech to Chefchaouen — 4-Day Blue City Tour", cat: "cultural", origin: "marrakech", days: 4, type: "private" },
  { slug: "marrakech-imperial-cities-5day", title: "Marrakech — All 4 Imperial Cities — 5-Day Grand Tour", cat: "cultural", origin: "marrakech", days: 5, type: "private" },
  { slug: "shared-agafay-dinner-camel-ride", title: "Agafay Desert — Dinner, Camel Ride & Fire Show", cat: "day-tours", origin: "marrakech", days: 1, type: "shared" },
  { slug: "shared-essaouira-day-trip", title: "Essaouira — Shared Day Trip from Marrakech", cat: "day-tours", origin: "marrakech", days: 1, type: "shared" },
  { slug: "marrakech-food-market-tour", title: "Marrakech Food & Market Tour — Half-Day Culinary Walk", cat: "day-tours", origin: "marrakech", days: 1, type: "private" },
  { slug: "agafay-desert-sunset", title: "Marrakech to Agafay Desert — Sunset & Dinner", cat: "day-tours", origin: "marrakech", days: 1, type: "private" },
  { slug: "ourika-valley-day-hike", title: "Marrakech to Ourika Valley — Day Hike", cat: "day-tours", origin: "marrakech", days: 1, type: "private" },
  { slug: "ouzoud-waterfalls-day-trip", title: "Marrakech to Ouzoud Waterfalls — Day Trip", cat: "day-tours", origin: "marrakech", days: 1, type: "private" },
  { slug: "shared-ouzoud-waterfalls-day-trip", title: "Ouzoud Waterfalls — Shared Day Trip from Marrakech", cat: "day-tours", origin: "marrakech", days: 1, type: "shared" },
  { slug: "sahara-2day-agadir", title: "Agadir to the Sahara — 2-Day Desert Tour", cat: "desert", origin: "agadir", days: 2, type: "private" },
  { slug: "zagora-2day-agadir", title: "Agadir to Zagora — 2-Day Desert Tour", cat: "desert", origin: "agadir", days: 2, type: "private" },
  { slug: "erg-chegaga-3day-agadir", title: "Agadir to Erg Chegaga — 3-Day Remote Desert Tour", cat: "desert", origin: "agadir", days: 3, type: "private" },
  { slug: "merzouga-3day-agadir", title: "Agadir to Merzouga — 3-Day Sahara Desert Tour", cat: "desert", origin: "agadir", days: 3, type: "private" },
  { slug: "desert-4day-agadir", title: "Agadir Desert Grand Tour — 4 Days", cat: "desert", origin: "agadir", days: 4, type: "private" },
  { slug: "anti-atlas-trekking-agadir", title: "Agadir to Anti-Atlas Mountains — 3-Day Trek", cat: "trekking", origin: "agadir", days: 3, type: "private" },
  { slug: "souss-valley-cultural-tour", title: "Agadir to Souss Valley — Argan & Berber Culture Tour", cat: "cultural", origin: "agadir", days: 1, type: "private" },
  { slug: "taroudant-day-trip-agadir", title: "Agadir to Taroudant — Day Trip", cat: "cultural", origin: "agadir", days: 1, type: "private" },
  { slug: "agadir-to-fes-4day", title: "Agadir to Fes — 4-Day Imperial Cities Tour", cat: "cultural", origin: "agadir", days: 4, type: "private" },
  { slug: "agadir-to-chefchaouen-5day", title: "Agadir to Chefchaouen — 5-Day Blue City Tour", cat: "cultural", origin: "agadir", days: 5, type: "private" },
  { slug: "agadir-imperial-cities-6day", title: "Agadir — All 4 Imperial Cities — 6-Day Grand Tour", cat: "cultural", origin: "agadir", days: 6, type: "private" },
  { slug: "agadir-surf-lesson", title: "Agadir Beach Surf Lesson", cat: "day-tours", origin: "agadir", days: 1, type: "private" },
  { slug: "agadir-to-essaouira-day-trip", title: "Agadir to Essaouira — Day Trip", cat: "day-tours", origin: "agadir", days: 1, type: "private" },
  { slug: "paradise-valley-agadir", title: "Agadir to Paradise Valley & Immouzer Waterfalls", cat: "day-tours", origin: "agadir", days: 1, type: "private" },
  { slug: "sous-massa-national-park", title: "Agadir to Souss-Massa National Park — Wildlife Tour", cat: "day-tours", origin: "agadir", days: 1, type: "private" },
  { slug: "casablanca-fes-sahara-marrakech-5day", title: "Casablanca to Marrakech — 5-Day Imperial Cities & Sahara", cat: "cultural", origin: "casablanca", days: 5, type: "private" },
];

var FORM_TITLE = 'How was your trip? — Marrakech Eco Tours';

/** Site locales, so a response can be read in the language it was written. */
var LANGUAGES = ['English', 'Français', 'Español', 'Deutsch', 'Italiano', 'العربية'];

var CATEGORY_LABELS = {
  desert:      'Desert tour — Merzouga, Zagora, Chegaga or Agafay',
  trekking:    'Trekking or mountains — Toubkal, Atlas, M\u2019Goun',
  cultural:    'Cultural or imperial cities — Fes, Chefchaouen, Meknes',
  'day-tours': 'A single day trip'
};

var ORIGIN_LABELS = {
  marrakech:  'Marrakech',
  agadir:     'Agadir',
  casablanca: 'Casablanca'
};

/**
 * Which suppliers a tour actually uses.
 *
 * A required GridItem forces an answer in EVERY row, so a day-trip client
 * would be made to rate "the desert camp" — an answer at random, which
 * quietly poisons every average you later compute. The Apps Script reference
 * confirms grids have no per-row validation, so these are separate optional
 * scale questions instead, each with its own "not part of my tour" escape.
 */
function suppliersFor(cat) {
  var s = ['guide'];
  if (cat === 'trekking') {
    s.push('muleteer');
  } else {
    s.push('driver', 'vehicle');
  }
  if (cat === 'desert') s.push('camp', 'camels');
  return s;
}

var SUPPLIER_LABELS = {
  guide:    'Your guide',
  driver:   'Your driver',
  vehicle:  'The vehicle — comfort and cleanliness',
  muleteer: 'The mule handler and trek crew',
  camp:     'The desert camp — tents, bathrooms, comfort',
  camels:   'The camel ride',
  food:     'The food',
  hotel:    'Hotels and guesthouses along the way'
};

/** Stable question order. Food and hotels apply to anything overnight. */
var ALL_SUPPLIERS = ['guide', 'driver', 'vehicle', 'muleteer', 'camp', 'camels', 'food', 'hotel'];

/** Group the catalogue the way the branching lands: category, days, city. */
function buildBuckets() {
  var map = {}, keys = [];
  for (var i = 0; i < TOURS.length; i++) {
    var t = TOURS[i];
    var key = t.cat + '||' + t.days + '||' + t.origin;
    if (!map[key]) { map[key] = { cat: t.cat, days: t.days, origin: t.origin, tours: [] }; keys.push(key); }
    map[key].tours.push(t);
  }
  return { map: map, keys: keys };
}

function daysLabel(n) {
  return n === 1 ? 'One day' : (n + ' days');
}

/* ================================================================== *
 *  createForm — run this once.
 * ================================================================== */
function createForm() {
  var form = FormApp.create(FORM_TITLE);
  form.setDescription(
      'Thank you for travelling with us. These answers go only to our office — ' +
      'they are not published anywhere. Two minutes, and they tell us which of ' +
      'our guides, drivers and camps are doing their job well.')
    .setProgressBar(true)
    .setCollectEmail(false)
    .setAllowResponseEdits(true)
    .setConfirmationMessage(
      'Thank you — this genuinely helps. If something went wrong and you would ' +
      'like us to reply, email contact@marrakechecotours.com and mention your tour.');

  /* ---- 1. The hidden identity fields -----------------------------
   * These carry what YOUR link already knows. They sit first so the
   * prefilled values land before anything else, and their titles say
   * "leave blank" so a client on the bare form skips them.
   * The slug is the machine key: titles get edited, slugs do not. */
  var slugItem = form.addTextItem()
    .setTitle('Booking reference')
    .setHelpText('Filled in automatically from your link — please leave this as it is.');

  var langItem = form.addMultipleChoiceItem()
    .setTitle('Which language would you like to answer in?')
    .setHelpText('Answer in whichever language you prefer — we read all of them.')
    .setChoiceValues(LANGUAGES);

  /* ---- 2. The picker ---------------------------------------------
   * Built ONLY for someone who opened the bare form. Anyone arriving
   * on a prefilled link has already answered this above and can pick
   * whatever is quickest — the slug field is what we actually read. */
  var pickerIntro = form.addSectionHeaderItem()
    .setTitle('Which trip did you take?')
    .setHelpText('Three quick taps and we will find it — you should not have to hunt through a long list.');

  var catItem = form.addMultipleChoiceItem().setTitle('What kind of trip was it?').setRequired(true);

  var b = buildBuckets();
  var pages = {};   // bucket key -> PageBreakItem
  var dayPages = {}; // category -> PageBreakItem holding its day question
  var dayItems = {}; // category -> the day MultipleChoiceItem

  // A page per category, holding "how many days".
  var cats = [];
  for (var i = 0; i < TOURS.length; i++) if (cats.indexOf(TOURS[i].cat) < 0) cats.push(TOURS[i].cat);

  for (var c = 0; c < cats.length; c++) {
    var cat = cats[c];
    dayPages[cat] = form.addPageBreakItem().setTitle(CATEGORY_LABELS[cat] || cat);
    dayItems[cat] = form.addMultipleChoiceItem().setTitle('How long was it?').setRequired(true);
  }

  // A leaf page per bucket, holding just that bucket's tours.
  for (var k = 0; k < b.keys.length; k++) {
    var key = b.keys[k], bk = b.map[key];
    var titleBits = [CATEGORY_LABELS[bk.cat] || bk.cat, daysLabel(bk.days), 'from ' + (ORIGIN_LABELS[bk.origin] || bk.origin)];
    var page = form.addPageBreakItem().setTitle(titleBits.join(' — '));
    var list = form.addMultipleChoiceItem()
      .setTitle('Which one was it?')
      .setRequired(true);
    var names = [];
    for (var t = 0; t < bk.tours.length; t++) names.push(bk.tours[t].title);
    names.push('None of these / not sure');
    list.setChoiceValues(names);
    pages[key] = page;
  }

  /* ---- 3. The ratings ---------------------------------------------
   * Must be built AFTER every leaf page: the reference is explicit that
   * "page navigation has no effect on the last page of a form", so the
   * leaves need somewhere to route forward TO. */
  var ratingsPage = form.addPageBreakItem()
    .setTitle('How did it go?')
    .setHelpText('Skip anything that was not part of your trip.');

  form.addScaleItem()
    .setTitle('Overall, how was the trip?')
    .setBounds(1, 5)
    .setLabels('Poor', 'Excellent')
    .setRequired(true);

  // One optional scale per supplier, plus an explicit escape hatch. A grid
  // would be tidier on screen but forces an answer in every row.
  for (var s = 0; s < ALL_SUPPLIERS.length; s++) {
    var sup = ALL_SUPPLIERS[s];
    form.addScaleItem()
      .setTitle(SUPPLIER_LABELS[sup])
      .setHelpText('Leave blank if this was not part of your tour.')
      .setBounds(1, 5)
      .setLabels('Poor', 'Excellent')
      .setRequired(false);
  }

  form.addParagraphTextItem()
    .setTitle('Was anything wrong, uncomfortable or not as described?')
    .setHelpText('This is the answer we act on. Be blunt — it goes to the office, not online.')
    .setRequired(false);

  form.addParagraphTextItem()
    .setTitle('What was the best part?')
    .setRequired(false);

  form.addMultipleChoiceItem()
    .setTitle('Did the trip match what we described when you booked?')
    .setChoiceValues([
      'Yes, it matched',
      'Mostly, with small differences',
      'No — something significant was different'
    ])
    .setRequired(true);

  form.addTextItem()
    .setTitle('Roughly when did you travel?')
    .setHelpText('Month and year is enough — it helps us tie feedback to a season.')
    .setRequired(false);

  form.addTextItem()
    .setTitle('Your name (optional)')
    .setHelpText('Only so we can look up your booking if you have raised something.')
    .setRequired(false);

  /* ---- 4. Wire the navigation -------------------------------------
   * Choice navigation overrules a page's own setGoToPage, so each leaf
   * page gets a default forward jump to the ratings, and the upstream
   * choices override where needed. */
  var catChoices = [];
  for (var c2 = 0; c2 < cats.length; c2++) {
    catChoices.push(catItem.createChoice(CATEGORY_LABELS[cats[c2]] || cats[c2], dayPages[cats[c2]]));
  }
  catItem.setChoices(catChoices);

  // Within a category, "how long" routes to the right leaf. Where a length
  // exists in more than one city, ask the city as part of the same choice
  // rather than adding another page — fewer taps, same precision.
  for (var c3 = 0; c3 < cats.length; c3++) {
    var cat3 = cats[c3];
    var seen = {}, order = [];
    for (var kk = 0; kk < b.keys.length; kk++) {
      var bk3 = b.map[b.keys[kk]];
      if (bk3.cat !== cat3) continue;
      if (!seen[bk3.days]) { seen[bk3.days] = []; order.push(bk3.days); }
      seen[bk3.days].push(b.keys[kk]);
    }
    order.sort(function (x, y) { return x - y; });

    var dayChoices = [];
    for (var o = 0; o < order.length; o++) {
      var d = order[o], keysForDay = seen[d];
      if (keysForDay.length === 1) {
        dayChoices.push(dayItems[cat3].createChoice(daysLabel(d), pages[keysForDay[0]]));
      } else {
        // Same length, several cities — fold the city into the label.
        for (var q = 0; q < keysForDay.length; q++) {
          var bk4 = b.map[keysForDay[q]];
          dayChoices.push(dayItems[cat3].createChoice(
            daysLabel(d) + ', from ' + (ORIGIN_LABELS[bk4.origin] || bk4.origin),
            pages[keysForDay[q]]));
        }
      }
    }
    dayItems[cat3].setChoices(dayChoices);
    dayPages[cat3].setGoToPage(ratingsPage);
  }

  for (var k2 = 0; k2 < b.keys.length; k2++) {
    pages[b.keys[k2]].setGoToPage(ratingsPage);
  }

  /* ---- 5. Responses land in a sheet ------------------------------- */
  var ss = SpreadsheetApp.create('Tour feedback — responses');
  form.setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId());

  var props = PropertiesService.getScriptProperties();
  props.setProperty('FORM_ID', form.getId());
  props.setProperty('SLUG_ITEM_ID', String(slugItem.getId()));
  props.setProperty('LANG_ITEM_ID', String(langItem.getId()));

  Logger.log('FORM BUILT');
  Logger.log('Edit it here:      %s', form.getEditUrl());
  Logger.log('Send this link:    %s', form.getPublishedUrl());
  Logger.log('Responses sheet:   %s', ss.getUrl());
  Logger.log('Leaf pages: %s   Tours: %s', b.keys.length, TOURS.length);
  Logger.log('Now run makeLinks() to get one prefilled link per tour.');
  return form.getId();
}

/* ================================================================== *
 *  makeLinks — one prefilled link per tour. Run after createForm.
 *
 *  Writes them to a sheet as well as the log, because 48 links in a log
 *  window is not something you can copy from on a phone.
 * ================================================================== */
function makeLinks() {
  var props = PropertiesService.getScriptProperties();
  var formId = props.getProperty('FORM_ID');
  if (!formId) throw new Error('No form yet — run createForm() first.');

  var form = FormApp.openById(formId);
  var slugItem = form.getItemById(Number(props.getProperty('SLUG_ITEM_ID'))).asTextItem();

  var ss = SpreadsheetApp.create('Tour feedback — links to send');
  var sheet = ss.getActiveSheet();
  sheet.appendRow(['Tour', 'City', 'Type', 'Link to send the client']);
  sheet.getRange(1, 1, 1, 4).setFontWeight('bold');
  sheet.setFrozenRows(1);

  var rows = [];
  for (var i = 0; i < TOURS.length; i++) {
    var t = TOURS[i];
    // The slug, not the title: titles get reworded, slugs are the stable key.
    var resp = form.createResponse().withItemResponse(slugItem.createResponse(t.slug));
    var url = resp.toPrefilledUrl();
    rows.push([t.title, ORIGIN_LABELS[t.origin] || t.origin, t.type, url]);
    Logger.log('%s\n  %s', t.title, url);
  }
  sheet.getRange(2, 1, rows.length, 4).setValues(rows);
  sheet.autoResizeColumns(1, 3);
  sheet.setColumnWidth(4, 520);

  Logger.log('---');
  Logger.log('%s links written to: %s', rows.length, ss.getUrl());
  return ss.getUrl();
}

/* ================================================================== *
 *  summarise — which supplier is slipping.
 *
 *  Averages each supplier per tour, ignoring blanks rather than scoring
 *  them zero: a blank means "not part of my trip", and counting it as a
 *  zero would make every day trip look like a failing desert camp.
 * ================================================================== */
function summarise() {
  var props = PropertiesService.getScriptProperties();
  var form = FormApp.openById(props.getProperty('FORM_ID'));
  var slugId = Number(props.getProperty('SLUG_ITEM_ID'));

  var responses = form.getResponses();
  if (!responses.length) { Logger.log('No responses yet.'); return; }

  var byTour = {};
  for (var r = 0; r < responses.length; r++) {
    var items = responses[r].getItemResponses();
    var slug = '(unknown)', scores = {};
    for (var i = 0; i < items.length; i++) {
      var it = items[i], title = it.getItem().getTitle(), val = it.getResponse();
      if (it.getItem().getId() === slugId) { if (val) slug = String(val).trim(); continue; }
      var n = Number(val);
      if (val !== '' && val !== null && !isNaN(n) && n >= 1 && n <= 5) scores[title] = n;
    }
    if (!byTour[slug]) byTour[slug] = [];
    byTour[slug].push(scores);
  }

  // A blank means one of two very different things, and conflating them hides
  // the problem. suppliersFor() says which suppliers a tour ACTUALLY used, so
  // a missing camp score on a day trip is expected, while a missing guide
  // score on any tour is a question someone declined to answer.
  var tourBySlug = {};
  for (var ti = 0; ti < TOURS.length; ti++) tourBySlug[TOURS[ti].slug] = TOURS[ti];

  Logger.log('%s responses across %s tours', responses.length, Object.keys(byTour).length);
  for (var s in byTour) {
    var list = byTour[s], agg = {};
    for (var x = 0; x < list.length; x++) {
      for (var q in list[x]) {
        if (!agg[q]) agg[q] = { sum: 0, n: 0 };
        agg[q].sum += list[x][q]; agg[q].n++;
      }
    }
    var parts = [];
    for (var q2 in agg) parts.push(q2 + ' ' + (agg[q2].sum / agg[q2].n).toFixed(1) + '/5 (n=' + agg[q2].n + ')');

    // Flag a supplier this tour really uses that nobody has rated: either the
    // question is being skipped, or that supplier was quietly absent.
    var tour = tourBySlug[s], gaps = [];
    if (tour) {
      var expect = suppliersFor(tour.cat);
      for (var e = 0; e < expect.length; e++) {
        var label = SUPPLIER_LABELS[expect[e]];
        if (!agg[label]) gaps.push(label);
      }
    }
    Logger.log('\n%s  — %s response(s)\n   %s%s', s, list.length, parts.join('\n   '),
      gaps.length ? '\n   NO RATINGS YET for: ' + gaps.join(', ') : '');
  }
}
